### ISSUE TITLE
FPS: Multiple Spine Animations Performance Hit (CanvasRenderer)

### ISSUE THREAD

**Issue by englercj** [pixijs/pixi-spine#1]
Tracking GoodBoyDigital/pixi.js#1619.

**Comment by adamdanielsdesign** [comment]
***Here's the original post for quick reference***

I've included some sample code that I'm using, To test yourself you'll need a SpinePRO export animation. Increasing the total animations added in the test lines decreases the fps display from the stats.js lib.

Details:
- Using CanvasRenderer at relatively 1498x715

```
<!DOCTYPE html>
<html>
	<head>
	  <meta charset=utf-8>
	  <title>FPS Test</title>
	</head>
	<body>
		<script type="text/javascript" src="stats.min.js"></script>
		<script type="text/javascript">
			var stats = new Stats();
			stats.setMode( 0 );
			document.body.appendChild( stats.domElement );
			var canvas = document.createElement( 'canvas' );
			canvas.setAttribute('style','display: inline-block;');
			canvas.width = 100;
			canvas.height = 75;
			document.body.appendChild( canvas );
		</script>
		<script type="text/javascript" src="pixi.js"></script>
		<script type="text/javascript">			
		
			var loadAni = function(FILENAME,CB_LOADED){
				var assetsToLoader = [
					FILENAME+".png",
					FILENAME+".json",
					FILENAME+".atlas"
				];
				var loader = new PIXI.AssetLoader(assetsToLoader);
				loader.onComplete = function(e){
					console.log(e);
					var obj = new PIXI.Spine(FILENAME+".json");
					loader.onComplete = null;
					CB_LOADED(obj);
				};
				loader.load();
			};//end loadAni
			
			var stage = new PIXI.Stage(0xeeeeee, true);
			var renderer = new PIXI.CanvasRenderer(1498,715,{antialias: true});
			document.body.appendChild(renderer.view);
			function aniFrame(){
				stats.begin();
				renderer.render(stage);
				stats.end();
				requestAnimFrame(aniFrame);
			}//end aniFrame
			requestAnimFrame(aniFrame);
			if(true){
				{
					//change this int to test 				<<< FPS Test
					var totalObjsToAdd = 3;
					
					for(var i=0,l=totalObjsToAdd;i<l;i++){
						loadAni('/assets/bot',function(OBJ){
							if(window.bot == 'undefined' || window.bot == null){
								window.bot = OBJ; 
								bot.x = 350;bot.y = 400;
								stage.addChild(bot);
								bot.state.setAnimationByName(0, bot.stateData.skeletonData.animations[0].name, true);
							}else{
								var b = OBJ;
								b.x = 350;b.y = 400;
								stage.addChild(b);
								b.state.setAnimationByName(0, b.stateData.skeletonData.animations[0].name, true);
							}
							
						});
					}
				}
			}
		</script>
	</body>
</html>
```

**Comment by ivanpopelyshev** [comment]
Current implementation iterates through all animation frames at every render() call. We have to optimize every tmeline to fix that.

**Comment by adamdanielsdesign** [comment]
@ivanpopelyshev tx for the debug!

I haven't dug into it that much just yet, is there an existing data model that it's using other than just raw, for stuff like uv maps? example would be it grouping all the draw calls together first and then rendering them.

**Comment by ivanpopelyshev** [comment]
We can try use SpriteBatch? It will speed up only for webgl, though

**Comment by adamdanielsdesign** [comment]
Well, seems like fixing the excess iterations would work.

For the data model, not sure if it's re-calculating drawing the vert faces at every frame. 
If it is then an option to disable it would be great for when a part is known to not have any moving verts, then it could reuse the same uv map.

**Comment by ivanpopelyshev** [comment]
I'm looking at pixi v3 at the moment. I'll try to debug it with your data later :)

**Comment by ivanpopelyshev** [comment]
Please open your .json file and search for

```javascript
"type": "skinnedmesh"
```

If there is at least mesh - that's your bottleneck :)

**Comment by adamdanielsdesign** [comment]
plenty of those

**Comment by adamdanielsdesign** [comment]
as a possible solution:
a data model consisting of pre-calculated uv's for when the mesh isn't getting dynamically changed.

**Comment by ivanpopelyshev** [comment]
CanvasRenderer + mesh = performance hit.
Do you have that problem with WebGL?

**Comment by adamdanielsdesign** [comment]
on mac/osx chrome browsers it's there for both webgl and canvas, just less with webgl.

**Comment by ivanpopelyshev** [comment]
@adamdanielsdesign ok, that was fixed in https://github.com/pixijs/pixi-spine/blob/gpupatch/gpupatch/SkinnedMeshPatch.js , which will be merged here soon.

**Comment by adamdanielsdesign** [comment]
Awesome! Happy Holidays!
