### ISSUE TITLE
flipX and flipY are not supported in spine v3.

### ISSUE THREAD

**Issue by Luncher** [pixijs/pixi-spine#102]
Why the flipTimeline are not supported in spine v3?

**Comment by ivanpopelyshev** [comment]
Oh right, its not supported in v3, I got rid of them. 

This one has it: https://github.com/pixijs/pixi-spine/tree/d0f55c4d827c61f0e71071e457faca39265adbfd/bin

But I dont guarantee that it works with pixi-v4.

Please get rid of flip timelines

**Comment by Luncher** [comment]
There are other ways to implement this feature?

**Comment by ivanpopelyshev** [comment]
I think of ScaleTimeline . Flip was removed because there was no way to implement it with new bones transform update, it broke everything.

**Comment by Luncher** [comment]
ok, thankyou!
