### ISSUE TITLE
Animation can play the specified number of times it?

### ISSUE THREAD

**Issue by Luncher** [pixijs/pixi-spine#103]
## for example: 

play('attack', 1);

it mean: play animation attack once

**Comment by ivanpopelyshev** [comment]
There's no such thing in vanilla (spine-libgdx, spine-js) runtimes. Fill free to implement it, https://github.com/pixijs/pixi-spine/blob/master/src/SpineRuntime/AnimationState.js

**Comment by cursedcoder** [comment]
can be closed?
