### ISSUE TITLE
can i get the max rect size of the animation?

### ISSUE THREAD

**Issue by Luncher** [pixijs/pixi-spine#104]
can i get the max rect size of the animation?

Typically used for collision detection.

**Comment by ivanpopelyshev** [comment]
I recomment to add BoundingBox in spine editor, animate it that way it always covers your spine anim.

```js
var vertices = spine.skeleton.findSlot("myBoundingBox").attachment.vertices;
//do it every frame:
var bb = new PIXI.Rectangle(vertices[0], vertices[1], vertices[4]-vertices[0], vertices[5] - vertices[1]);
```

**Comment by Luncher** [comment]
I am not familiar with the editor of the spine, the spine editor now implement this feature?

**Comment by ivanpopelyshev** [comment]
@Luncher you can call spine.getBounds() of course, but I recommend to add bounding box in spine and animate it. It's not easy to calculate bounding box in runtime :(

**Comment by Luncher** [comment]
Rectangle size is dynamic computing? Will it affect the efficiency?

**Comment by Luncher** [comment]
@ivanpopelyshev

**Comment by ivanpopelyshev** [comment]
@Luncher well, imagine that every frame we have to add all points (meshes too) and calculate bounding box of them. Its better if we already have bounding box made in spine. Spine cannot do that automatically too, so you have to create boundingbox attachment and animate it :)

**Comment by staff0rd** [comment]
Is that not what SkeletonBounds is for?  I see the implementation, but I can't work out how it works - the typescript definition at least suggests it should be constructed, but doing so fails.

**Comment by ivanpopelyshev** [comment]
@staff0rd whats skeletonBounds?

**Comment by staff0rd** [comment]
@ivanpopelyshev sorry, assumed you wrote this...

https://github.com/pixijs/pixi-spine/blob/master/src/SpineRuntime/SkeletonBounds.js

**Comment by ivanpopelyshev** [comment]
@staff0rd I see it first time. Anyway, we need different kind of bounds, these ones are slow too :)

**Comment by staff0rd** [comment]
@ivanpopelyshev yeah, I started to go down the route of adding a BoundingBox to the spine for performance, but then determined for my own solution that all I needed was to configure a separate hitbox rect for my component.  Works well, except I encountered [this](pixijs/pixi.js#1698).  Looking at a fix now.

**Comment by ivanpopelyshev** [comment]
@staff0rd 

I have a build of pixi with my PR i mentioned to you in that thread. https://dl.dropboxusercontent.com/u/46636530/pixijs/bounds/pixi.js
