### ISSUE TITLE
can we cache the bounds data?

### ISSUE THREAD

**Issue by Luncher** [pixijs/pixi-spine#106]
getBounds API can we cache the bounds data?

**Comment by ivanpopelyshev** [comment]
No :( 

That's why I asked you to include bounding box into spine model itself

**Comment by Luncher** [comment]
can we caculate the max bounds and then cache it?

**Comment by Luncher** [comment]
I use this  mark Dirty rectangle

**Comment by ivanpopelyshev** [comment]
PIXI does it per every frame. If you want to cache it - make your own getBounds() method. By the way , which version of pixi do you use?

**Comment by Luncher** [comment]
`3.0.11`

**Comment by Luncher** [comment]
thanks got it

**Comment by cursedcoder** [comment]
can be closed?
