### ISSUE TITLE
Spine2d 3.3 breaking changes to meshes

### ISSUE THREAD

**Issue by scottmcdonnell** [pixijs/pixi-spine#107]
Exporting a weighted mesh from spine2d 3.3 is now breaking pixi-spine. 

Here is the weighted mesh working with a [3.2 export](http://scottmcdonnell.github.io/pixi-examples/index.html?s=spine&f=dragon_3_2.js&title=Dragon%20Boned%20Mesh%203.2&plugins=pixi-spine)

and now broken with a [3.3 export](http://localhost:8080/index.html?s=spine&f=dragon_3_3.js&title=Dragon%20Boned%20Mesh%203.3&plugins=pixi-spine)

looks like 3.3 json export renames ` "type": "weightedmesh"` to `"type": "mesh"`

**Comment by ivanpopelyshev** [comment]
Thank you, I will fix that in weekend.
