### ISSUE TITLE
Spine2d 3.3 Paths are cool

### ISSUE THREAD

**Issue by scottmcdonnell** [pixijs/pixi-spine#108]
Nice new [Path features in 3.3](https://www.youtube.com/watch?v=1j-Z9gax7zc) - would be great to support them in pixi-spine.

Looks like they are updating the esoteric runtimes at the moment.

**Comment by ivanpopelyshev** [comment]
yeah, Im gonna add it this week. This time for sure.

**Comment by ivanpopelyshev** [comment]
Fixed in a branch
