### ISSUE TITLE
Using more then one atlas in skeleton

### ISSUE THREAD

**Issue by yuriilychak** [pixijs/pixi-spine#110]
Hello. 
I'm developing a farm game with the  Pixi.js framework. 
Can I use more than one texture atlas to create animations, or better, use a texture from Pixi.js resources?
The problem is that I have buildings (factory, cafes, swings, etc.), that have own animation which uses common characters for all of them. The are many characters, that  can be customized (hats, shirts, glasses, etc.).
Add all characters texture in to atlas of each building is a bad idea, because there are a lot of buildings in project, and will be two problems. 

- User traffic, that will grow by several times.
- Max atlas size is 2048x2048, and at one point all the characters with the building simply will not fit there.

Can you describe the solution to my problem, or to suggest that some of your own?

P.S.
Sorry for my poor English :)

**Comment by ivanpopelyshev** [comment]
[link1](https://github.com/pixijs/pixi-spine#how-to-use-pixi-spritesheet-with-it)
[link2](https://github.com/pixijs/pixi-spine/blob/master/src/SpineRuntime/Atlas.js#L16)

Special for that case, pixi-spine has some methods that do not appear in other spine runtimes. 

* construct the atlas manually, pass it to the loader through "metadata" parameter
* change any attachment texture on runtime if you need it

In any case, please look at the sources, don't think about this plugin as a blackbox :)

**Comment by yuriilychak** [comment]
Thanks a lot:)
