### ISSUE TITLE
Reset strategy

### ISSUE THREAD

**Issue by staff0rd** [pixijs/pixi-spine#112]
New to both spine and it's pixi implementation - I have a question regarding how to correctly transition between animations that have different bone/slot (not sure correct terminology) setups.

I have an animation, _walking_, that works fine.  I have another animation, _throw_, that during the animation one of the bones/slots is removed.  When I chain the animations like this;

~~~javascript
this.myCharacter.state.setAnimationByName(0, 'throw', false);
this.myCharacter.state.addAnimationByName(0, 'walking', true);
~~~

The _walking_ animation correctly appears after _throw_, however it's missing the slot/bone that _throw_ removed.

To return the missing bone/slot it I need to do something like this;

~~~javascript
this.myCharacter.skeleton.setToSetupPose();
this.myCharacter.state.addAnimationByName(0, 'walking', true);
~~~

I just saw that `onComplete` is in there - do I need to use that to reset the structure at the end of any _throw_, or is there a better way to do this?

**Comment by ivanpopelyshev** [comment]
I think its spine animation property, not runtime. You have to open it in editor and return that slot in the end of "throw"

**Comment by staff0rd** [comment]
You're right.
