### ISSUE TITLE
Debug compiled "pixi-spine.js" is missing an ending semicolon

### ISSUE THREAD

**Issue by probityrules** [pixijs/pixi-spine#113]
The compiled "pixi-spine.js" file ends without a semicolon which can cause erratic issues when concatenating with other JavaScript files.

Note that "pixi-spine.min.js" ends with a semicolon and doesn't suffer the same potential for bleeding into the next file's opening line of code.

A project I'm working on started throwing peculiar errors, and it took me awhile to figure out that this was the cause, so I wanted to go ahead and post here. I'm using the minified version as a simple workaround at the moment.

**Comment by ivanpopelyshev** [comment]
Any ideas on how to fix that?

**Comment by probityrules** [comment]
I just issued a pull request that offers a potential fix for this issue. https://github.com/pixijs/pixi-spine/pull/114
