### ISSUE TITLE
Is it possible to locally rotate a bone?

### ISSUE THREAD

**Issue by staff0rd** [pixijs/pixi-spine#115]
It seems something like this does nothing;

``` javascript
var torso = skeleton.findBone("torso");
torso.rotation = 90; // seems to have no effect
```

Where as the following works, but it permanently updates the rotation for all animations by updating the setup pose;

``` javascript
var torso = skeleton.findBone("torso");
torso.data.rotation = 90; // bone is visibly rotated
```

Is there any way to rotate a bone without updating the setup pose?

**Comment by ivanpopelyshev** [comment]
No, and I dont think original spine runtime has that :( Please look at the sources and make a method that hacks it, that way it does not interfere with original code, I'll be happy to accept any hacks that help in game production :)

**Comment by staff0rd** [comment]
When you refer to the _original spine runtime_, to what are you referring?  [This](http://esotericsoftware.com/spine-using-runtimes#Manipulating-bones) at least suggests that the runtime should be capable of it.  For the moment I'm just using `bone.data.rotation`, but if it turns out to cause me further trouble i'll look at what I can do to enable local rotation in pixi-spine.

**Comment by ivanpopelyshev** [comment]
Nice :) Try the same thing , but use "rotationIK" variable.

**Comment by staff0rd** [comment]
Tried that, also does nothing.

**Comment by ivanpopelyshev** [comment]
Oh, they changed it in spine v3, and nobody updated that code. Sorry, but you have to hack "Bone.update" method, plesae look in "bone.js". Add there a flag and third variable "rotationOverride" and it'll work :)

**Comment by staff0rd** [comment]
Cheers, i'll take a look

**Comment by ivanpopelyshev** [comment]
OK, are there any ideas how to override rotation in new version?

**Comment by staff0rd** [comment]
@zhishaofei3 looking at my source, I was finding the slot via `skeleton.findSlot` and then rotating it with

```
mySlot.bone.data.rotation = 315; // degrees
Pixi.spine.Spine.update(0);
```

**Comment by zhishaofei3** [comment]
````javascript
app.ticker.add(function () {
  rotation++
  if (rotation > 360) {
    rotation = 0
  }
  lFrontLeg = dragon.skeleton.findBone('L_front_leg')
  if (lFrontLeg) {
    lFrontLeg.data.rotation = rotation // degrees
    // PIXI.spine.Spine.update(0);
    console.log(lFrontLeg.data.rotation)
    dragon.update(0.01666666666667)
  }
})
````
the code does not seem to work, no rotation
Is there a problem with my code?

**Comment by staff0rd** [comment]
Are you rotating the slot instead of the bone?

**Comment by zhishaofei3** [comment]
I findBone or findBone,  but they have no work
