### ISSUE TITLE
listening to events

### ISSUE THREAD

**Issue by kamiljurek** [pixijs/pixi-spine#116]
Hello guys,
I've encountered problem with listening to events. Is there any way of listening to event on particular frame?

Solution from https://github.com/pixijs/pixi-spine/issues/15 doesn't work, and it doesn't dispatch any events.
I think there is some problem with apply function (125 line).

Why is there: this.events.length = 0; on 134 line?

**Comment by cursedcoder** [comment]
hello @kamiljurek, do you still have this issue?
