### ISSUE TITLE
The latest version is not working correctly on IE9

### ISSUE THREAD

**Issue by darting** [pixijs/pixi-spine#117]
![spineboy](https://cloud.githubusercontent.com/assets/4946661/17471740/e3b4de70-5d78-11e6-89ab-e96d3198cc8e.png)

This is the result while I run it on IE9.

If I used pixi-spine.js which I downloaded from here 'https://github.com/pixijs/examples/tree/gh-pages/_site/js/plugins'. It is working.

**Comment by ivanpopelyshev** [comment]
Which pixi version?

**Comment by darting** [comment]
pixi.js:   v4.0.0-rc3
pixi-spine.js: I downloaded from here https://github.com/pixijs/pixi-spine/commit/cb06da4ca76a9f9169fcb40fb557fde7a841596f

**Comment by beblank** [comment]
hi,
i also facing the problem for the ie 9
this is the version taken from the npm package
"pixi-spine": "^1.0.28",
"pixi.js": "^4.0.2"
the spine is not showing anything
just blank scene

and this is the setting for the spine
![spine setting](https://cloud.githubusercontent.com/assets/6060071/18859437/9d4a75b2-84a6-11e6-8428-4b053061d061.jpg)

thanks

**Comment by cursedcoder** [comment]
@darting does it works now?

**Comment by cursedcoder** [comment]
OK, just tested on saucelabs - it doesn't work on IE9

@ivanpopelyshev not sure what's, but overall, does pixi officially support old IEs?

**Comment by cursedcoder** [comment]
@darting @beblank could you please check it this URL works for you http://en.esotericsoftware.com/spine-demos

?

**Comment by darting** [comment]
@cursedcoder Not working on IE9, got error "Float32Array" is undefined.

The following browsers not works well also:

PC:
360 Browser(Version 7.5.2.106) .

Mobile:
Samsung A8 - QQ
Xiaomi Phone - Dolphin

**Comment by darting** [comment]
![image](https://cloud.githubusercontent.com/assets/4946661/22960842/273fd430-f37c-11e6-8487-91c88ec5d246.png)

**Comment by cursedcoder** [comment]
@darting ok so typedarrays aren't supported in IE9, you could try to use a polyfill https://github.com/inexorabletash/polyfill/blob/master/typedarray.js

**Comment by darting** [comment]
@cursedcoder yes thanks, I will uses a polyfill for typedarray, so for this polyfill not gg to including in this lib?

**Comment by cursedcoder** [comment]
@darting it's unrelated to our library and will not be included.

If you just add a polyfill to your build it should work smoothly.
