### ISSUE TITLE
Spine 2 box2d

### ISSUE THREAD

**Issue by whizzkid** [pixijs/pixi-spine#118]
Hello @ivanpopelyshev 

I'm trying to make a spine2box2d routine to help me quickly make ragdolls.

But I'm running into a problem,  example code of the java version doesn't work when I convert it for pixi-spine   and for some reason I can't seam to fathom how I can get from the Spine object/skeleton to current position/rotation of the sprites i see onscreen.

I tried to read the actual sprites on screen, but their rotation and position don't change.  Can't seem to find where to look..

any suggestions would be helpful :)

**Comment by ivanpopelyshev** [comment]
You have to look at sprite.worldTransform. You have to decompose actual rotation and stuff from it, there are methods in "PIXI.Matrix" for that. But there's also a skew, and that's why you can just make them boxes. Make them polygons and use "sprite.worldTransform" and may be "sprite.vertexData" to determine positions of corners.

Anyway, you just have to read code of https://github.com/pixijs/pixi.js/blob/master/src/core/sprites/Sprite.js and 
https://github.com/pixijs/pixi-spine/blob/master/src/Spine/index.js#L182

**Comment by ivanpopelyshev** [comment]
And the main suggestion is: "DEBUG IT LIKE HELL"

**Comment by whizzkid** [comment]
I did :P 
but I kept finding stuff that didn't change (like position and rotations of the sprites that were on screen) 

Ill give it another go, thanks.

**Comment by ivanpopelyshev** [comment]
May be you can take "sprite.calculateVertices" and make new method that uses transform of the bone - that will give you local coordinates of sprite in spine object.

**Comment by ivanpopelyshev** [comment]
Its ok that position/scale/rotation are not changed, transform is directly copied from the bone, and bone transform calculation is very difficult process that depends on spine model version, IK and other things. If you want to use position/scale/rotation, you have to decompose matrix with "PIXI.Matrix.decompose" or something like that.

**Comment by whizzkid** [comment]
Actually, I can just read currentSprite.vertexData because they've already been calculated :) 
Looks good, now to see if i can make a ragdoll

**Comment by whizzkid** [comment]
Thinking forward though. There's no method to stop a Spine animation from updating is there?

**Comment by ivanpopelyshev** [comment]
Its either spine object that updates bone transforms with spine logic, either it is ragdoll. You can convert first to second, but I dont think that you can use spine object AS a ragdoll, because that way you'll have to deal with spine IKs.

**Comment by ivanpopelyshev** [comment]
You can stop spine animation. Just set "spineObj.autoUpdate" to false.

**Comment by whizzkid** [comment]
I'll try :)

For my purposes I want to do a spine -> ragdoll conversion only.   
for picking up a character and dragging him around the screen.
so i need to pause spine (just saw the autoUpdate right before you posted it :)   do my magic. and when the user drops the character, normal spine animation can resume.
and we don't have any special IK or something in our characters, so that should pose no problem.

**Comment by ivanpopelyshev** [comment]
It cant just resume, it will flicker on it.

**Comment by cursedcoder** [comment]
@whizzkid any news on this?
Do you still have any questions?
Or maybe let's close the issue.
