### ISSUE TITLE
License clarification required

### ISSUE THREAD

**Issue by staff0rd** [pixijs/pixi-spine#119]
What's the deal with [the license](https://github.com/pixijs/pixi-spine/blob/master/SPINE-LICENSE)?  Was this code originally from Esoteric?

The license has wording that states no edits are allowed; 

> you may not (a) modify, translate, adapt or otherwise create derivative works, improvements of the Software or develop new applications using the Software

**Comment by ivanpopelyshev** [comment]
I really don't know :) ask EsotericSoftware, its not like they ban custom runtimes, they even asked us to update our stuff for their latest version and gave me free licenses

**Comment by GoodBoyDigital** [comment]
Yeah, they are a pretty cool bunch and as far as i am aware, happy for @ivanpopelyshev to keep smashing out pixi-spine 👍

**Comment by staff0rd** [comment]
So does the license belong here, or is this code base also MIT licensed like pixi.js?

**Comment by ivanpopelyshev** [comment]
@staff0rd I don't know. Can you help with that? What I know is that people have their own implementation and were asking EsotericSoftware to pull specific features from them

**Comment by staff0rd** [comment]
First commits are from @englercj, perhaps he knows?

**Comment by ivanpopelyshev** [comment]
Please write to support@esotericsoftware.com. Don't bother @xerver

**Comment by GoodBoyDigital** [comment]
Leave it with me chaps!

**Comment by englercj** [comment]
> First commits are from @englercj, perhaps he knows?

The original commits I did were using the files (including license) from the distributed Esoteric Software JS library. Their license may have changed since then, but that was the license of *their* distributable at the time.

**Comment by staff0rd** [comment]
Sounds like the license is legit then.

Considering this is the only repo in the pixijs organisation with a commercial license, perhaps the README should be updated to state so, and/or, at least have a warning that per the license you can't contribute/commit to or modify this repo without first obtaining a spine license?

**Comment by cursedcoder** [comment]
ok guys, let's discuss it on #pixi-spine channel
