### ISSUE TITLE
Runtime skin changes

### ISSUE THREAD

**Issue by whizzkid** [pixijs/pixi-spine#120]
Hey there,

I've got a little character in spine and I want to change its head. 
This works nicely if you only have 1 animation by using 
`this.spine.skeleton.setAttachment("Head", "HeadNumber" + aRandomNumber);`

However, if you change an animation, it resets to its original head.
Now in the documentation I've read that you can create a skin at runtime. but I've found no examples of this.

My idea was to either change the existing skin and change the head, or create a new skin with the correct head in place. But I have no idea how to do this.

I'm not even allowed to do:
`var newSkin = new PIXI.spine.Skin("newSkin");`

PIXI.spine.Skin is not a constructor

**Comment by ivanpopelyshev** [comment]
Just hack it. https://github.com/pixijs/pixi-spine#changing-the-texture-the-direct-way-hacks

**Comment by whizzkid** [comment]
Found another solution
Which is a little more in line with the original SPINE documentation. (well.. they tell you you CAN change attachments at runtime, but forget to mention HOW :P )

If you setup your spine animation with skinPlaceHolders you can do it without hacks.
You also need to add all the other images you want to be able to use in the placeholder to the same bone. otherwise they wont be stored as attachments.
You'd have to put the image thats in your initial placeholder in twice though, because otherwise the attachment cannot be found later on. 

![image](https://cloud.githubusercontent.com/assets/323372/17890147/59a31fb8-6934-11e6-8d5b-0d8968bed8c7.png)


Then this code works, even if you play different animations.

```
var skinToModify: PIXI.spine.Skin = this.spine.skeleton.data.skins[1]; // this is my 'personSkin'
skinToModify.attachments["0:headSkinPlaceholder"] = this.spine.skeleton.getAttachmentBySlotIndex(0, "Hoofd" + MathUtils.randRange(0, 3));
this.spine.skeleton.setSkinByName(skinToModify.name);
```

**Comment by ivanpopelyshev** [comment]
Nice! My hacks were made for the other case: people do want to fill extra atlas with extra stuff that wasn't made through spine.

**Comment by whizzkid** [comment]
Yeah, I haven't tried your code but I think i did something similar first.
But when you go from say an idle animation to a walking animation, all the attachments get reset to the one set in the animationdata.

Does that happen with hackTextureBySlotName() as well ?

**Comment by ivanpopelyshev** [comment]
I think hackTexture really changes texture of specified attachment. I dont remember though, i made it 2 months ago

**Comment by whizzkid** [comment]
Hey @ivanpopelyshev 

If you instantiate multiple instances of the same SpineData. the skins sorta get shared.
So if I change 1 skin in 1 object, the other objects skin SOMETIMES also changes.. 
(havent had time to figure out exactly why or how)

Found a workaround, if I create multiple skins in spine (which is a pain) I can fix the problem
Now I'd like to create a new skin in runtime:

`skinToModify = new PIXI.spine.Skin("bla");`

 but I get the error:

`Uncaught TypeError: PIXI.spine.Skin is not a constructor`

shouldn't that work ?

**Comment by ivanpopelyshev** [comment]
right now its PIXI.spine.core.Skin , can you try again?
