### ISSUE TITLE
Spine-ts

### ISSUE THREAD

**Issue by scottmcdonnell** [pixijs/pixi-spine#121]
What is the plan with spine-ts? I had a quick look here at adding some Pixi to it, but have got stuck already. 

Here is [the example ](http://rawgit.com/scottmcdonnell/pixi-spine/spine-ts/pixi/example/) but it is not applying the[ local transform on update](https://github.com/scottmcdonnell/pixi-spine/blob/spine-ts/pixi/src/SkeletonContainer.ts#L262). Not sure of the workings of the new PIXI v4 transforms.

**Comment by ivanpopelyshev** [comment]
Thank you, that will help me to integrate spine-ts. 

!@#$ im stupid!

Check if its PIXI.TransformStatic either PIXI.Transform, not just latter

**Comment by scottmcdonnell** [comment]
I made a little progress - the [TransformStatic helped](http://rawgit.com/scottmcdonnell/pixi-spine/spine-ts/pixi/example/)
Separate [Slot Container class ](https://github.com/scottmcdonnell/pixi-spine/blob/spine-ts/pixi/src/SkeletonContainer.ts)to keep refs to Display Objects.

**Comment by ivanpopelyshev** [comment]
The most difficult part will be loader, it is async.

**Comment by ivanpopelyshev** [comment]
I dont undrestand some typescript stuff regarding modules, I need help with that. 

Currently spine-ts compiles all files from folder somehow and I dont understand how to do it the same way as PIXI does. 

For example, we have module "spine" inside of directory "core", it contains all files in this directory. How can I include this as a module from "index.ts" which will be entry for browserify?

**Comment by ivanpopelyshev** [comment]
@englercj said that Its better to convert module to imports first, so I'll do that.

**Comment by scottmcdonnell** [comment]
It may be best to keep the spine-ts core files untouched so the runtime can be easily updated. What about having the runtimes as a package dependency and importing just the spine-ts/build/spine-core.js?

**Comment by ivanpopelyshev** [comment]
I dont think we can leave them in pure form, there are too many hacks in original pixi-spine for that. I can ask Mario (spine-ts author) to change the way it builds, but for now we have to change everything on ES6 modules manually.

**Comment by ivanpopelyshev** [comment]
Having it as package dep is bad too because I also want to generate TS header automagically.

**Comment by scottmcdonnell** [comment]
It should be possible to keep the hacks and the spine-ts in separate files, leaving data in the the core then the display implementation in the new pixi part. For example I moved the sprites array from the Slot(core) to the SlotContainer(pixi) so that the Slot remains unchanged.

**Comment by englercj** [comment]
If we could keep the original lib as a dependency and apply our hacks to it that would be awesome. You should be able to generate the dts file that includes spine even with it as a dep.

**Comment by scottmcdonnell** [comment]
At the moment the runtimes are missing a package.json [(I opened an issue)](https://github.com/EsotericSoftware/spine-runtimes/issues/711)  
so for the moment I am testing just adding the build/spine-core.js and ts definition file manually and importing it  `import './spine-ts/build/spine-core'` - working so far.

**Comment by ivanpopelyshev** [comment]
OK, that's my branch: https://github.com/pixijs/pixi-spine/tree/spine-ts

**Comment by ivanpopelyshev** [comment]
IT WORKS!

 https://github.com/pixijs/pixi-spine/tree/spine-ts

There are a few changes, I'm going to change API a bit, add deprecated stuff :) Path Constraints are working!

**Comment by scottmcdonnell** [comment]
Super work!

**Comment by ivanpopelyshev** [comment]
Current problems: 

1. RENAMES (according to last pixi-spine)

Atlas to TextureAtlas
SkeletonJsonParser to SkeletonJson

setAnimation to setAnimationWith
setAnimationByName to setAnimation

addAnimation to addAnimationWith
addAnimationByName to addAnimation
hasAnimationByName to hasAnimation

So you'll have problem with "byName" suffix, just remove it from your code.

2. possible rejection of older versions of spine

3. EVENTS, they are just different, but I'll return our API a bit later. Currently you have to add special listener to state, and it must have all functions:

animation.state.addListener({
    /** Invoked when the current animation triggers an event. */
    event : function(trackIndex, event) { alert('event fired '+event.data) }
    
    /** Invoked when the current animation has completed.
     * @param loopCount The number of times the animation reached the end. */
    complete : function(trackIndex, loopCount) {}
    
        /** Invoked just after the current animation is set. */
    start: function (trackIndex) {}
    
        /** Invoked just before the current animation is replaced. */
    end: function (trackIndex) {}
})

**Comment by scottmcdonnell** [comment]
It works great! Check out [Stretchyman ](http://rawgit.com/scottmcdonnell/pixi-spine/spine-ts/examples/stretchyman.html)and [Spineboy](http://rawgit.com/scottmcdonnell/pixi-spine/spine-ts/examples/spineboy.html).

- [source](https://github.com/scottmcdonnell/pixi-spine/tree/spine-ts/examples)

Only thing now working for me is the Stretchman head rotation - setting the [bone rotation](https://github.com/scottmcdonnell/pixi-spine/blob/spine-ts/examples/stretchyman.js#L219) is not updating the sprite rotation?

**Comment by ivanpopelyshev** [comment]
Yeah, we have to add this feature to pixi-spine.

**Comment by ivanpopelyshev** [comment]
So, I think we can close that :) lets work on one rotation in the pther issue

**Comment by ivanpopelyshev** [comment]
That thing: #115
