### ISSUE TITLE
Cannot set property 'tint' of undefined

### ISSUE THREAD

**Issue by erwamartin** [pixijs/pixi-spine#122]
Hi there!

This plugin is great, very useful to export characters from Spine and render them on the web!

However, I'm trying to use pixi-spin to animate a character but I'm having an issue:
> Error: Uncaught TypeError: Cannot set property 'tint' of undefined (pixi-spine.js Line: 193)

Here is the code:

```javascript
PIXI.loader
    .add('character', '../data/character.json')
    .load(function(response) {
      	var spineCharacter = new PIXI.spine.Spine(response.resources.character.spineData);
      	stage.addChild(spineCharacter);
		spineCharacter.scale.set(0.35);
		if (spineCharacter.state.hasAnimation('walk')) {
		    spineCharacter.state.setAnimation(0, 'walk', true);
		}
      	animate();
    });
```

Any ideas on how to fix that?

Thank you!

**Comment by ivanpopelyshev** [comment]
OK, fixed this one and pair of others. Please check it :)

**Comment by erwamartin** [comment]
Excellent, it works now!
Thank you so much :)
