### ISSUE TITLE
Specify premultipliedAlpha parameter using PIXI.loaders.Loader()

### ISSUE THREAD

**Issue by erwamartin** [pixijs/pixi-spine#123]
Hi there!

I'm wondering how I can set the premultipliedAlpha value that can be found using the loadSkeleton(name, initialAnimation, premultipliedAlpha, skin) function? 

I have some issues with transparency that seems to be fixed if I set the "premultipliedAlpha" parameter to "true" in this example: https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-ts/webgl/example/index.html

Thank you!

**Comment by ivanpopelyshev** [comment]
Its always "true" for pixi.

**Comment by ivanpopelyshev** [comment]
Closing it because you can specify premultiply later in PIXI.BaseTexture itself
