### ISSUE TITLE
RENDER WARNING: there is no texture bound to the unit 3

### ISSUE THREAD

**Issue by macguffin** [pixijs/pixi-spine#124]
Hi Ivan just an observation

I was getting this 'RENDER WARNING' when using pixi-spine. It may be due to the fact I'm not using the pixijs loader so might just be might problem.
It looks like the pixi-spine is drawing stuff before the texture has been loaded to the webGL.

Waiting for the texture seems to have fixed it:
````
var waitForTexture = setInterval(()=> {
      if (PIXI.utils.BaseTextureCache['skeleton.png'].hasLoaded) {
                    console.log('LOADED')
                    clearInterval(waitForTexture);
                    //start pixi spine stuff                           
                } else {
                    console.log('NOT LOADED')
                }
            }, 1)
`

**Comment by ivanpopelyshev** [comment]
I need more info, how exactly do you load spine atlas and json? Do you use it in latest version?

**Comment by macguffin** [comment]
I am using the latest version of both your stuff (v1.1.3) and the pixijs stuff (pixi.js - v4.0.3).
The image ,atlas and json created from Spine2d are loaded using preloadjs (not ideal but a legacy thing)
I then get this info from the preloadjs load queue and make the pixi-spine animation.

When it happened it wasn't every time. I've only noticed it with my latest game which is not optimised yet and currently has 4 massive spritesheets. So it might be that their is a lot of webGL stuff happening at once. 


````
static SPINE(jsonData, atlasData, image_baseTexturePath) {
var spineData;
var baseUrl = LoadQ._loadItemsById[jsonData].src.substr(0, LoadQ._loadItemsById[jsonData].src.lastIndexOf('/'));
            // create a spine atlas using the loaded text
 var spineAtlas = new PIXI.spine.core.TextureAtlas(LoadQ.getResult(atlasData), function (line, callback) {
                //pass the image here.
                callback(PIXI.BaseTexture.fromImage(image_baseTexturePath));
            }); //specify path, image.png will be added automatically

// spine animation
var spineJsonParser = new PIXI.spine.core.SkeletonJson(new PIXI.spine.core.TextureAtlasAttachmentLoader(spineAtlas));
var skeletonData = spineJsonParser.readSkeletonData(window.com.camelot.core.iwgLoadQ.getResult(jsonData));
return new PIXI.spine.Spine(skeletonData);
}

**Comment by ivanpopelyshev** [comment]
OK, then its a mystery, your solution has to work.

**Comment by macguffin** [comment]
haha mystery indeed.
