### ISSUE TITLE
PIXI not defined when in a closure

### ISSUE THREAD

**Issue by uorbe001** [pixijs/pixi-spine#130]
We are using browserify to bundle our code, and browserify wraps the code around closures that it then loads as needed. The issue we are having is that pixi-spine is redefining PIXI despite the fact that it needs it to be able to load (on loaders.ts) and it exist globally.

The culprit of our issue is [this line (and other refereces to `var PIXI` on bin/pixi-spine.js ](https://github.com/pixijs/pixi-spine/blob/master/bin/pixi-spine.js#L6). This works fine if you load it outside a closure because `var PIXI` will not override `window.PIXI`, but when loaded inside a closure, `var PIXI` (undefined) will be preferred to the global PIXI (`window.PIXI`) which crashes horridly as it is undefined.  

I have tested it and simply deleting all the references to `var PIXI` in this file makes it work, but it's a terrible hack. I'd like to be able to tell typescript not to define that variable and simply use the global, but I have no clue how to do that in typescript. If someone could point me to how this could be achieved (using the global PIXI instead of declaring a new var PIXI) I'm willing to do the change myself and open a PR, but I need some help 👼 .

**Comment by ivanpopelyshev** [comment]
so we need to somehow load PIXI as an import in pixi-spine, and show pixi-spine as an export. Ugh, that's real pain :) 

My suggestion is that you dont use browserify on pixi/pixi-spine. Test the bundling time, I guess it'll be much faster without PIXI  in your result file

**Comment by uorbe001** [comment]
At the moment, loading pixi-spine as a single separate file is a problem for us since we are using PIXI loaded from another framework we've built on top of it, so the interdependency makes it a big headache. :( 

Other libraries like [pixi-particles](https://github.com/pixijs/pixi-particles/blob/master/src/main.js) are handling the export madness correctly(ish), and they also have a dependency with PIXI. 

Rather than using PIXI as a namespace for everything, isn't it possible to make typescript use Spine (or whatever) as the namespace and then attach that namespace to the global PIXI if it is defined or something similar?

**Comment by ivanpopelyshev** [comment]
I agree

**Comment by uorbe001** [comment]
ah, so this is an issue with spine-ts? Wouldn't simply changing references like this one to [PIXI.spine](https://github.com/pixijs/pixi-spine/blob/master/src/core/Animation.ts#L31) to something like Spine and then exporting this `Spine` namespace do the trick?

**Comment by ivanpopelyshev** [comment]
We have to make sure it works for users who just include "spine.js" in HTML page and use it like "PIXI.spine...". We cant add more requirements for devs who use the simplest approach

**Comment by uorbe001** [comment]
Surely that would work if we did something similar to what pixi-particles is doing? That's simply putting everything in the 'particles' namespace and then [adding it to `module.exports` if defined](https://github.com/pixijs/pixi-particles/blob/master/src/main.js#L16) or [`window` when that doesn't exist](https://github.com/pixijs/pixi-particles/blob/master/src/main.js#L42)? 

The 'simple HTML script' case is supported by this, and so are the browserify, electron and (I believe) AMD require cases. The one I'm not 100% sure can work this way is typescript, maybe someone has an example of this working with TS?

**Comment by ivanpopelyshev** [comment]
Gonna try something today

**Comment by uorbe001** [comment]
@ivanpopelyshev did you get anywhere? I intend to give it a try when I find the time, but have been uber-busy lately.

**Comment by uorbe001** [comment]
I just checked and 576754a5cb79ceeba3ad57f5117f3fd8a0367e90 fixes this issue, thanks @Adamfsk and @ivanpopelyshev!

**Comment by ivanpopelyshev** [comment]
Yeah , but there's another issue - users cant specify spine types in TS :(
