### ISSUE TITLE
Issue with inheriting mesh deform using linked mesh on different skins

### ISSUE THREAD

**Issue by msgopinath** [pixijs/pixi-spine#135]
We are trying to use one mesh to add deform animations to a whole deck of card skins using linked meshes. The skins were working just fine before we added the linked mesh hierarchy on the cards. However, now only the card with the original mesh is showing up and the rest of the card skins are missing.

Spine Version 3.5

**Comment by ivanpopelyshev** [comment]
Ok, found it , try now please.

**Comment by msgopinath** [comment]
Hurrrrey!! It works thanks!! you saved our day !!

**Comment by ivanpopelyshev** [comment]
I hope you didnt lose too much time on that. Original bug in spine-ts was fixed 10 days ago may be, I found about it yesterday.

**Comment by msgopinath** [comment]
Not that much time, good that we reported in this forum :) 
One more quick question: can we some how reverse the animation using setAnimation in pixi-spine code?

**Comment by ivanpopelyshev** [comment]
According to https://github.com/pixijs/pixi-spine/blob/master/src/core/AnimationState.ts , it cant handle reverse looping, you have to modify it :(

As for simple rewind, I think this will work:

```
spine.state.tracks[0].timeScale = -1
```
