### ISSUE TITLE
hasAnimationByName deprecated

### ISSUE THREAD

**Issue by jmlee2k** [pixijs/pixi-spine#138]
Hi,

When using the "hasAnimationByName" function, I get the following warning,

> Deprecation Warning: AnimationState.hasAnimationByName is deprecated, please use hasAnimation from now on.

However, there doesn't appear to be a "hasAnimation" function.  What am I missing?

**Comment by ivanpopelyshev** [comment]
Oh, right, I guess we lost it... lets remove the deprecation ;)

**Comment by cursedcoder** [comment]
can be closed now @ivanpopelyshev
