### ISSUE TITLE
Spine Events not supported

### ISSUE THREAD

**Issue by englercj** [pixijs/pixi-spine#15]
Cross posting GoodBoyDigital/pixi.js#787.

**Comment by mreinstein** [comment]
is this an issue of spine events being supported in the spine runtime, but simply not being exposed to pixi? Or are events simply not supported in the underlying runtime?

**Comment by ivanpopelyshev** [comment]
they are exposed, I just didnt find what's wrong :)

**Comment by mreinstein** [comment]
I think this is already supported actually! this works for me:

```
// animation is the instantiated pixi-spine object

animation.state.onEvent = function(i, event) {
  console.log('event fired!', i, event);
};
```

Unless I'm missing something I think you can close this ticket :)

**Comment by ivanpopelyshev** [comment]
I'll add it to README so there wont be problems :)
