### ISSUE TITLE
How to adjust scale?

### ISSUE THREAD

**Issue by mspanish** [pixijs/pixi-spine#153]
I finally got different resolution of textures/atlases to load, but it didn't affect the scale of the animation. Now the images are just fuzzy :) - Anybody know how to set the SCALE of your spine animation when or before loading into Pixi?

**Comment by ivanpopelyshev** [comment]
I need more info on that, because I know that people often do it wrong way :)

https://github.com/pixijs/pixi-spine/blob/master/examples/choose_skeleton_scale.md

**Comment by ivanpopelyshev** [comment]
If you're resizing your objects depending on resolution you are using (1x, 2x) , you are doing it wrong.

**Comment by mspanish** [comment]
Yeah I really have been throwing spaghetti at the wall, the worst way to do anything!

I tried using the exact code from that .md file - 

`var spineLoaderOptions = { metadata: { spineSkeletonScale: 0.5 } };` - and loading my json with the options, but my crab is still ginormous!

![crab](https://cloud.githubusercontent.com/assets/206150/22857957/26f8c53a-f05d-11e6-91d2-a7a01f1cde9e.png)

**Comment by ivanpopelyshev** [comment]
Looks nice :) Does that skeleton scale option not workign for you?

**Comment by ivanpopelyshev** [comment]
Please check that you re-downloaded it.

**Comment by mspanish** [comment]
Yes beautiful - I just did that and now my crab is just perfect! Thanks a lot, I really appreciate the help. Have a great day!

**Comment by mspanish** [comment]
hey in an unrelated question, can I disable the looping at runtime? Poor crab is awfully distracting for kids if he loops!

**Comment by mspanish** [comment]
sorry, that one was painfully obvious. Just set the 3rd parameter to false.

` crab.state.setAnimation(0, 'animation', false);`

thanks again, I'll be sure to post the demo app when I've got it done - the app will be mostly free, and I hope to target more than just autistic kids, but rather all kids w/ auditory processing issues of any kind.

**Comment by ivanpopelyshev** [comment]
:)
