### ISSUE TITLE
Possible to change skins when using a mesh?

### ISSUE THREAD

**Issue by mspanish** [pixijs/pixi-spine#154]
I've been looking through the docs and must say I'm not sure whether I am supposed to create a linked mesh for each skin I want - or if there is a more efficient way to do this. I have 26 different skins - color variations of a barrel graphic that I'm animating to squish and expand when it eats up one of the letters in my reading app. I can easily switch the barrels within Spine even after applying the mesh by just changing the image path for the mesh object in the tree. But I have no idea if there is a simple way to do this at runtime - or even how to get all of the graphics to output without linking them to bones/slots/etc - which I am not sure how I can do as they wouldn't be the correct size for the mesh.

![barrels](https://cloud.githubusercontent.com/assets/206150/22873071/072f8c4e-f16a-11e6-95be-77765687d079.png)

![spine](https://cloud.githubusercontent.com/assets/206150/22873078/0f07c896-f16a-11e6-9f5d-938580cd5fdd.png)

**Comment by ivanpopelyshev** [comment]
I don't actually use editor myself, I think you better ask @cursedcoder or post it on official spine forum.

[How to change skin](blob/master/examples/change_skin.md)

There's also pixi way, take texture from spine atlas

```
var allRegions= loader.resources['mySpine'].spineAtlas.regions;
var myTexture = null;
for (var i=0;i<allRegions.length;i++) { if (allRegions.name == 'iWantThat') { myTexture = allRegions[i] } }
```

then pass it here:

[How to hack texture](blob/master/examples/hack_texture.md)

**Comment by cursedcoder** [comment]
@mspanish it seems you don't really need skins there.

The idea is that you can set any color at the runtime.

That's how I do it:

```typescript
let slot: Slot = spine.skeleton.findSlot('background');
slot.color.setFromString('#D68F00');
```

**Comment by mspanish** [comment]
Changing just the color was my first thought, as I usually work with SVG - but I have white and black shadows that create the illusion of darker and lighter regions - I guess I could save those pieces as separate slots in Spine, right? Thanks to both @ivanpopelyshev and @cursedcoder for the help here - I don't think my project would get off the ground animation without the help I've already had.  I'll try out all of this stuff today and let you all know how that goes. As everything in my app needs to be done in 26 colors which I'm trying to get the child to learn for the letters - this is a pretty key issue for me!

**Comment by mspanish** [comment]
@cursedcoder is there anything I need to do in order for the meshes to show up at runtime? Just exporting the same way I've done the other animations, the mesh animation doesn't appear.  I've tried fiddling with the color of the keys in the tree at different parts of the animation, to no avail. I guess I should re-read the Spine docs!

**Comment by mspanish** [comment]
Ah I just noticed I used a skinHolder- I bet that is the problem. I'll try messing with that now.

**Comment by mspanish** [comment]
sorry looks like it was a naming issue I had something messed up in my filenames & paths. Mesh showing fine, haven't tested the tinting yet though!

**Comment by mspanish** [comment]
The tinting is great, it should make my workflow a lot easier. Here is a sample of the white barrel tinted for a color. The code I used is this:
`        var barrel = new PIXI.spine.Spine(resources.spineChar4.spineData);`

`var slot = barrel.skeleton.findSlot('a');`
`slot.color.setFromString(color);`

thanks again!!

![screenshot 204](https://cloud.githubusercontent.com/assets/206150/22903134/1020882e-f1e4-11e6-93a1-cf07505170ac.png)

**Comment by ivanpopelyshev** [comment]
@mspanish If you will in need of some re-ordering, look there: https://github.com/pixijs/pixi-display/tree/layers , or older version: https://github.com/pixijs/pixi-display/ . Just save the links, use it when re-arranging chlidren becomes difficult

**Comment by mspanish** [comment]
thank you I'll look at that! Now I'm trying to clean up my file as I've added all of these animations in a big mess, I need to order by scenes as the barrel isn't until scene 2 :)
