### ISSUE TITLE
Best Practice help? Spine animations on idle versus plain sprites?

### ISSUE THREAD

**Issue by mspanish** [pixijs/pixi-spine#156]
@ivanpopelyshev  Hello and thanks for all the help so far - things are moving along! I was hoping for some advice about how to go about things - in my case, I have these 26 letters (eventually in lower and upper case, but for now just lower) - and I have these letters in spritesheets, and now I pulled the letters into Spine to see about animating individual letters. I thought "wow Spine is so great, maybe I can just use for everything!" - so I tried replacing my spritesheet letters with the Spine letter, changing out the attachment to change letters, and using the slot tint to change colors. Works beautifully too - but I noticed there seemed to be a performance drag when I was using these for dragging and dropping, even though I'm destroying stuff after the scene is done - the Spine letters definitely didn't perform as well as the plain sprites. 

So I'm better off using sprites for the dragging and dropping and basics - and only use the Spine letters when I really need to animate them, right?  I hope it's clear enough what I'm trying to say - I guess I'm asking how much overhead does an instance of a Spine sprite have, compared to a plain sprite loaded from an atlas.

Thanks again - I hope to post a link to my project soon.

**Comment by ivanpopelyshev** [comment]
How exactly do you animate the letters? Are they meshes or simple rectangles?

**Comment by mspanish** [comment]
I didn't animate them yet :) But I was thinking of mesh, then adding other elements for each letter to help illustrate

**Comment by ivanpopelyshev** [comment]
I know that current spine can be optimized easily: don't update bones if there's no animation. I will add that mode.

As for meshes, they're a problem. There was gpupatch for spine that moved meshes animation to GPU side and thus 100 spine instances were handled easily.

For now your solution (sprite + spine) is the best.

**Comment by mspanish** [comment]
ok thanks very much!
