### ISSUE TITLE
Add pause and resume methods for Spine.

### ISSUE THREAD

**Issue by englercj** [pixijs/pixi-spine#16]
Cross posting GoodBoyDigital/pixi.js#763.

**Comment by adamdanielsdesign** [comment]
Not sure, however...

Currently this is done by clearing current tracks (**pause**) and then setting the previous state back (**resume**).

However there's probably a method to actually remove the animations play state as it's associated with the requestAnimationFrame (Pixi v3).

**Comment by JaredSartin** [comment]
Any further notes on this? I want to pause my game and stop all motion, but don't want to iterate all entities and clear tracks/start animations every time I pause and resume.

**Comment by ivanpopelyshev** [comment]
I can implement that. You want to stop all spine animations, right?

**Comment by JaredSartin** [comment]
I would love to "stop" them and resume them, mid animation.

**Comment by ivanpopelyshev** [comment]
you can iterate and set "autoUpdate" to false for all of them. I'll add global autoUpdate flag

**Comment by ivanpopelyshev** [comment]
@JaredSartin can you build new version locally and test it, please? :)

**Comment by JaredSartin** [comment]
From what I can tell - it works! Animations pause when I turn off
autoupdate.

On Tue, Dec 15, 2015 at 1:04 PM Ivan Popelyshev <notifications@github.com>
wrote:

> @JaredSartin <https://github.com/JaredSartin> can you build new version
> locally and test it, please? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pixijs/pixi-spine/issues/16#issuecomment-164896099>.
>
-- 
Jared Sartin
*Mobile *(269) 364-1735 | *Twitter* @JaredSartin
<http://twitter.com/JaredSartin>
*Website* <http://jared.sart.in/>

**Comment by ivanpopelyshev** [comment]
Nice! Then I can close it. Will reopen if something goes wrong.

**Comment by Sprutik** [comment]
> Its 2024 , the only way to pause this that I found is this: `import * as SpineRuntime from 'pixi-spine';` and then to pause modify this: `SpineRuntime.settings.GLOBAL_AUTO_UPDATE = false;`

Legend
