### ISSUE TITLE
Correct usage of Typescript Pixi-spine

### ISSUE THREAD

**Issue by jeffscm** [pixijs/pixi-spine#167]
What is the correct way to use the pixi-spine typescript? I always get error trying to use this line of code:

`var dragon = new PIXI.spine.Spine(res.dragon.spineData);`

it says "spine not defined".

**Comment by ivanpopelyshev** [comment]
Hi! There's "bin/pixi-spine.d.ts" file. How exactly did you include it in your program? How did you add "pixi.js.d.ts"?

**Comment by ivanpopelyshev** [comment]
Please look at this page: https://github.com/pixijs/pixi-spine/tree/master/sandbox , we have special sandbox for import-related issues. @cursedcoder is maintaining it :)

**Comment by Scharnvirk** [comment]
Hello,

Can you please update the sandbox link? It leads to 404 now and I too have some trouble using pixi-spine with typescript.

**Comment by ivanpopelyshev** [comment]
Sandbox was removed, instead we use that file for the test: https://github.com/pixijs/pixi-spine/blob/master/test/checkpack.ts

**Comment by ivanpopelyshev** [comment]
This tool:
https://github.com/cursedcoder/checkpack
https://github.com/pixijs/pixi-spine/blob/master/package.json#L32

**Comment by Scharnvirk** [comment]
Thanks for quick reply. I've found that file and tried to do the same and then some with varying, but always wrong, results:

```
import '../bin/pixi-spine.js' //naturally won't work

import 'node_modules/pixi-spine/bin/pixi-spine.js' // Module not found: Error: Can't resolve 'node_modules/pixi-spine/bin/pixi-spine.js'
import 'node_modules/pixi-spine/bin/pixi-spine' // Module not found: Error: Can't resolve 'node_modules/pixi-spine/bin/pixi-spine.js'
import 'pixi-spine' // compiles, but when used, causes
// pixi-spine.js:3016 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
//     at new Skeleton (pixi-spine.js:3016)
//     at new Spine (...)
import 'pixi-spine/bin/pixi-spine.js' //as above
import * as PIXI_SPINE from 'pixi-spine' // error TS2306: File 'D:/dev/dobra-gra/node_modules/pixi-spine/bin/pixi-spine.d.ts' is not a module.
import * as PIXI_SPINE from 'pixi-spine/bin/pixi-spine' //error TS2306: File 'D:/dev/dobra-gra/node_modules/pixi-spine/bin/pixi-spine.d.ts' is not a module.
import * as PIXI_SPINE from 'pixi-spine/bin/pixi-spine.js' //error TS2306: File 'D:/dev/dobra-gra/node_modules/pixi-spine/bin/pixi-spine.d.ts' is not a module.
```

versions of TS and webpack:
"typescript": "^2.4.2",
"webpack": "^3.5.5",

**Comment by ivanpopelyshev** [comment]
You should give more details and ask @cursedcoder  about it.

Personally, I hate import/export and packers.

**Comment by Scharnvirk** [comment]
Nah it is not that bad, they have their quirks... but are workable.

It was all my fault, sorry for the mess here. You can safely delete everything starting with my post.
The one and only thing I did wrong was using incorrect key: I used `myObject.data.data` while I should use `myObject.data.spineData'. Just like in the manual. Then I thought it might be a fault of the loader and that was a shot totally in wrong direction. 

Sorry!

**Comment by BartolomeoItaliano** [comment]
I spend about day trying to solve this:
`import 'pixi-spine'`
Add to the pixi-spine main page tutorial this line for me it was crucial.

**Comment by crossRT** [comment]
Hi @ivanpopelyshev ,
I trying to use PIXI spine in my typescript and having some issues as well.
Here is how I did.
```typescript
import 'pixi.js';
import 'pixi-spine/bin/pixi-spine'

...
private item: PIXI.spine.Spine; <-------- TS2694: Namespace 'PIXI' has no exported member 'spine'.
```

Do you have any clue for me?
Thanks.

**Comment by BartolomeoItaliano** [comment]
change:
`import 'pixi-spine/bin/pixi-spine'`
to:
import 'pixi-spine'

**Comment by crossRT** [comment]
tried. but not work.
Any information you need me to provide?

**Comment by crossRT** [comment]
here's my tsconfig.json
```
{
  "compilerOptions": {
    "outDir": "./dist/",
    "noImplicitAny": false,
    "module": "es6",
    "target": "es6",
    "allowJs": true
  }
}
```

**Comment by ivanpopelyshev** [comment]
It should work. However I recommend to use global imports for both pixi and pixi-spine. You dont have to include big libraries into your bundle.

**Comment by crossRT** [comment]
Hi @ivanpopelyshev 
Sorry for late reply.
May I know what do you mean global imports?
I'm using webpack + typescript

**Comment by crossRT** [comment]
I found two solutions here, but not sure whether it's correct usage or not.

**Solution 1:**
- Uninstall `@types/pixi.js` from node_modules
- Then `import 'pixi-spine/bin/pixi-spine';` in your code.

**Solution 2**
- make sure `"noImplicitAny": false,` set as false in your tsconfig.json
- then use `const Spine = PIXI['spine'].Spine` in your code.

@ivanpopelyshev Please advise ya. =)

**Comment by ivanpopelyshev** [comment]
I have only a small experience with webpack, but I know that everything is done through `webpack.config`. @cursedcoder made `checkpack.ts`, and it somehow works with webpack. You can investigate his lib: https://github.com/cursedcoder/checkpack . That's how I know that pixi-spine works with webpack - i just run his tool and it says: "ok, that thing runs fine in vanilla/webpack/browserify".

Solution #1 is fine, I guess :)

**Comment by Shadowstep33** [comment]
For anyone else who comes across this, this has always worked for me:

```    "files": [
      "node_modules/pixi-spine/bin/pixi-spine.d.ts"
    ]```

placed outside of compilerOptions

**Comment by Vladnzh** [comment]
`{
    "compilerOptions": {
        "module": "none",
        "target": "es6",
        "noImplicitAny": true,
        "removeComments": true,
        "preserveConstEnums": true,
        "sourceMap": true,
        "inlineSources": true,
        "declaration": true,
        "baseUrl": ".",
        "esModuleInterop": true,
        "typeRoots" : ["node_modules/pixi.js", "node_modules/pixi-spine"],
        "types" : ["pixi.js", "@pixi/filter-color-overlay", "pixi-spine"]
    },
    "include": ["**/*.ts"],
    "exclude": ["node_modules"]
}
`
my ts config
