### ISSUE TITLE
Add onComplete callback for Spine

### ISSUE THREAD

**Issue by englercj** [pixijs/pixi-spine#17]
Cross posting GoodBoyDigital/pixi.js#762.

**Comment by adamdanielsdesign** [comment]
Should be:
```javascript
someSpineAnimation.state.onEnd(someCB);
```

**Comment by SlawomirMazgaj** [comment]
Just checking if it's still on TODO list or already done.

**Comment by ivanpopelyshev** [comment]
No, it is not implemented. Do you think we need to (hook it here)[https://github.com/pixijs/pixi-spine#how-to-use-spine-events] or use that every spine object actually is event emitter? That will be pixi-way of things

**Comment by SlawomirMazgaj** [comment]
Hm... just checked `spine.state.onComplete` and it's seems to be working, so that should be good enough for me. It's for single spine animation, isn't it ?

**Comment by ivanpopelyshev** [comment]
Wow! It works! https://github.com/pixijs/pixi-spine/blob/master/src/SpineRuntime/AnimationState.js#L88

Shall we close it?

**Comment by SlawomirMazgaj** [comment]
I think you can close it guys 👍
