### ISSUE TITLE
Cannot read property xxx of undefined when use PIXI.loaders.resources after load spine

### ISSUE THREAD

**Issue by hiepnh** [pixijs/pixi-spine#172]
Hi
I load spine then use PIXI.loaders.resources to create spine Object.
I got error "Cannot read property 'res/spine/skeleton.json' of undefined"

If i use 'resources' instead of PIXI.loaders.resources, It work.
I want to preload spine data first when start game then create Spine Object later( not in onLoaded ).
is there anyway to do this ?

```
var loaderSpine = new PIXI.loaders.Loader(); 
loaderSpine.add("res/spine/skeleton.json");
loaderSpine.once("complete", onLoaded);
loaderSpine.load();

function onLoaded(loader, resources) {
    //Cannot read property 'res/spine/skeleton.json' of undefined
  **// work** 
    var spineClock = new PIXI.spine.Spine(resources["res/spine/skeleton.json"].spineData);
// not work Cannot read property 'res/spine/skeleton.json' of undefined
 var spineClockError = new PIXI.spine.Spine(PIXI.loaders.resources["res/spine/skeleton.json"].spineData);

}
......
**sometime in game loop**
var spineClock = new PIXI.spine.Spine(PIXI.loaders.resources["res/spine/skeleton.json"].spineData); 
=> //Cannot read property 'res/spine/skeleton.json' of undefined


```

**Comment by ivanpopelyshev** [comment]
Because in your case, resources are "loaderSpine.resources" .

**Comment by hiepnh** [comment]
Yes. I know that.

>  var spineClock = new PIXI.spine.Spine(loaderSpine.resources["res/spine/skeleton.json"].spineData);

loaderSpine is local. I want to create Spine Object in another js file. Something like this

> var spineClock = new PIXI.spine.Spine(PIXI.**xxx**.resources["res/spine/skeleton.json"].spineData);

is there a global namespace for spine resources ?
Thank you

**Comment by ivanpopelyshev** [comment]
You can use shortcuts, "loaderSpine.add('name1', 'path_tp_spine.json')", then you can just use "name1" instead of full path

There was cache but I removed it some time ago. If you want to load just resources one-by-one, you can use a global loader and then

```
globalLoader.add('spine15', 'res/spine/skeleton15.json', localOnLoad)
```

**Comment by hiepnh** [comment]
Thank you so much 👍

**Comment by ivanpopelyshev** [comment]
wow, I'm a telepath!
