### ISSUE TITLE
Color tinting

### ISSUE THREAD

**Issue by gregmax17** [pixijs/pixi-spine#175]
Sorry, this is more of a question than a issue report. (didn't know where else to ask...)

I'm wondering if its possible to color tint some parts, the same way its possible to color tint some parts in unity.

**Comment by ivanpopelyshev** [comment]
So in unity you can tint sprite even if its not tinted in Attachment?

**Comment by gregmax17** [comment]
In Unity when adding Spine's sample warrior in armor to the scene, there is this in the inspector:
[http://imgur.com/iHFfAMA](url)

I'm able to change the eye, mouth, head colors, etc. I'm looking for this kind of availability. Is it doable?

**Comment by ivanpopelyshev** [comment]
According to https://github.com/pixijs/pixi-spine/blob/master/src/Spine.ts#L317

```
tintRgb[0] = r0 * slot.color.r * attColor.r;
```

you can just find slot index, take 

```
spine.skeleton.findSlot('LEG').currentSprite.tint = 0xff00ff;

**Comment by ivanpopelyshev** [comment]
New page! 

https://github.com/pixijs/pixi-spine/blob/master/examples/change_tint.md
