### ISSUE TITLE
Spine clipping

### ISSUE THREAD

**Issue by macpooh** [pixijs/pixi-spine#179]
Some time ago Spine introduced [clipping masks for spines](http://esotericsoftware.com/spine-changelog#v3-6-13-beta). Does support of this feature scheduled in nearest future?

**Comment by ivanpopelyshev** [comment]
pixi-spine is up-to-date with spine-ts, but pixi implementation lacks masks. I'm gonna add them soon if you are able to test them :)

**Comment by macpooh** [comment]
It would be highly appreciated. just let me know if u need something further.

**Comment by michalochman** [comment]
@ivanpopelyshev I have just run into this issue and I have created very simple test case if that helps:

https://codepen.io/michalochman/pen/PjVjRr?editors=0010

This is how it looks like:
![image](https://user-images.githubusercontent.com/1628450/28158188-340b7898-67b9-11e7-807c-971bc0a040ad.png)

This is how it should like:
![image](https://user-images.githubusercontent.com/1628450/28158168-227b8668-67b9-11e7-9d0d-b2e061b76843.png)

**Comment by ivanpopelyshev** [comment]
That'll help me to debug, thank you!

**Comment by ivanpopelyshev** [comment]
OK, so I studied their clipping algorithm and understood that we need better clipping handling in pixi first. Probably as a separate plugin. With current implementation its not easy.

**Comment by ivanpopelyshev** [comment]
@michalochman please check the latest version. Also I didnt make special tests, but I hope there are no stupid errors.

I implemented clipping through PIXI.Graphics, it must work with Canvas2d too.

**Comment by michalochman** [comment]
@ivanpopelyshev I have updated my test case on CodePen, seems to be working!

**Comment by macpooh** [comment]
hey. It works, but if its static. though DeformTimeline seems working, vertices keep updating on each frame, but its have no visual representation. I'm debugging right now, but if you have any suggests - would be cool)
animation used in attachment
[clip_animation.zip](https://github.com/pixijs/pixi-spine/files/1152323/clip_animation.zip)

[link to pen](https://codepen.io/macpooh/pen/owOmYK) clipping not updated, as you can see here.

**Comment by ivanpopelyshev** [comment]
OK, then its a bug, good test. Will look at it soon.

**Comment by ivanpopelyshev** [comment]
Fixed in 1.5.3

**Comment by macpooh** [comment]
It works fine! thanks a lot
