### ISSUE TITLE
Spine events parameters scope issue (event.target)

### ISSUE THREAD

**Issue by sHAYM4N** [pixijs/pixi-spine#180]
Not sure if there is a workaround for this that I've missed but found it hard to find the documentation on the parameters for the spine events... trackIndex, entry etc..

In my project I have a series of icons that play specific icons, (these are all created as prototypes) I have set an event listener on a specific animation to then reset to another animation once complete.  Unfortunately the scope doesn't allow for the icon even to be referenced inside the event listener "this" just returns the actual event, event.target returns undefined, so there doesn't seem to be a way that I can access the actual icon that the listener is attached to?

eg....

    this.iconWin = function (delayMe, lastIcon) {
        this.spineIcon.state.clearTracks();
        this.spineIcon.state.addAnimation(1, 'win', false, delayMe);
        this.spineIcon.state.tracks[1].listener = {complete: function(event){
                console.log(event);
                // HOW CAN I REFERENCE (this.spineIcon) from this block?
            }}
}

Sorry I know this may not be a PIXI problem, but struggling to find any reference for this..

**Comment by ivanpopelyshev** [comment]
```
this.iconWin = function (delayMe, lastIcon) {
    this.spineIcon.state.clearTracks();
    this.spineIcon.state.addAnimation(1, 'win', false, delayMe);
    this.spineIcon.state.tracks[1].listener = {complete: (event) =>{
            console.log(event);
            // HOW CAN I REFERENCE (this.spineIcon) from this block?
        }}
}
```

**Comment by sHAYM4N** [comment]
@ivanpopelyshev genius!  Many thanks :D
