### ISSUE TITLE
Typescript definitions broken in 1.5.1

### ISSUE THREAD

**Issue by vkarponen** [pixijs/pixi-spine#182]
The scope in 
bin/pixi-spine.d.ts: 1192 & 1202
`declare module pixi_spine.core {`
is wrong. It should be PIXI.spine.core like in all the other declarations.

**Comment by ivanpopelyshev** [comment]
Something is wrong with our build process, sorry :)

**Comment by ivanpopelyshev** [comment]
Fixed in 1.5.2
