### ISSUE TITLE
repeat animation for certain times

### ISSUE THREAD

**Issue by lirhtc** [pixijs/pixi-spine#183]
Hi, 
I am a beginner to pixi-spine and I have a problem with repeating an animation for a certain time. I know I can make an animation keep repeating (loop = true) but can I just repeat it twice? 

Also I could find a document or tutorial about pixi-spine so I just read around when I want to learn something new. Is there a better way to learn how to use pixi-spine for a beginner? 

Many thanks

**Comment by ivanpopelyshev** [comment]
All special pixi-spine featurez are described in https://github.com/pixijs/pixi-spine/blob/master/examples/, including events that have loops count param. 

For spine runtimes features in general, please follow esotericsoftware spine docs and forum - pixi-spine has the same methods as any other spine runtime (libgdx, unity, spine-ts,...)

the best collection of examples is for spine-ts: https://github.com/EsotericSoftware/spine-runtimes/tree/3.6/spine-ts , pixi-spine is based on it.

**Comment by badlogic** [comment]
*ducks and covers*

Thanks for making pixi-spine!

**Comment by lirhtc** [comment]
Very appreciate! The information and link are very helpful. Thanks for all your work @badlogic @ivanpopelyshev
