### ISSUE TITLE
Console said that spinedata is undefined.

### ISSUE THREAD

**Issue by hyunsooda** [pixijs/pixi-spine#185]
Hello, I'm student of south korea.
I have a problem at presently as that above title said.

<img width="766" alt="2017-08-02 2 23 31" src="https://user-images.githubusercontent.com/12508269/28837989-c6b19680-7729-11e7-9ece-fc5a0a9b3e81.png">

<img width="646" alt="2017-08-02 2 23 55" src="https://user-images.githubusercontent.com/12508269/28837993-cc95c95e-7729-11e7-9897-bb0b93af2667.png">

<img width="1156" alt="2017-08-02 2 24 11" src="https://user-images.githubusercontent.com/12508269/28837995-cec19820-7729-11e7-8c19-b609bb017324.png">

I had tried example which your git site provided but, was not working like above screenshots.
I also tested a number of pixi version but was not working as well.
I wonder the reason which was not working.

Thank you.

**Comment by ivanpopelyshev** [comment]
Are there corresponding textures in your folder? Also, please check that powerup-pro.json actually has link to "powerup.atlas" inside

**Comment by hyunsooda** [comment]
I tried most of examples of Spine which provided in basic.
but, also not working.
The only problem is that none spinedata property of resource data.

**Comment by ivanpopelyshev** [comment]
Look in the "network" tab and check if all the resources were actually loaded.

**Comment by hyunsooda** [comment]
Oh my god!! I found reason that have been not working.
I'm using Mac and simply dragged file of json into my workspace(pixi_exam).
network state was not bad(304) but,  file which dragged was slightly broken.
I have removed the file and once again properly copied(ctrl+c), afterward pasted(ctrl+v) into my workspace. 
finally, atlas file and png file were added into worksapce by myself and exactly working.

Thank you.

**Comment by ivanpopelyshev** [comment]
As I said: you need three files and they have to reference each other. I had a suspision that you've made an anchor instead, but I dont know if macos has same thing as windows

**Comment by hyunsooda** [comment]
yes.
thank you for your assistance.
Have a nice day.

**Comment by ivanpopelyshev** [comment]
Btw, look at http://www.html5gamedevs.com/topic/31613-wip-mad-world-cross-platform-mmorpg/ , these guys are making korean mmorpg on pixi with spine.

**Comment by hyunsooda** [comment]
Wow!!! this promotion is so wonderful that I'm exciting!
I was about to making 2d game, I was impressed after watching game which made by korean.
Also they seems like to have exceptional performance and smooth English skills.

Thank you for providing to me imformative info.
