### ISSUE TITLE
Adding display object to slot container in rotates and skews the added object

### ISSUE THREAD

**Issue by sotnight** [pixijs/pixi-spine#186]
When I am adding a display object to a slot container, whether it is another spine object or just a sprite, the added display object always get rotated and skewed. So in order for it to be displayed correctly I then need to rotate and skew it like below, and then also reposition it. Anyone who knows why this is so and if there is a better way to do this so that I don't need to rotate and skew it?
```
let spineObject:Spine = new Spine(spineData);
spineObject.slotContainers[0].addChild(sprite);
sprite.rotation = Math.PI;
sprite.skew.y = Math.PI;
```

**Comment by ivanpopelyshev** [comment]
```
var sprite;
var mat = new PIXI.Matrix();

//do it every update!
sprite.parent.transform.copy(mat);
mat.invert();
mat.tx = 0; mat.ty = 0;
sprite.transform.setFromMatrix(mat);
```

now its not scaled/rotated, AT ALL. If you want to leave scale then

```
var scale = sprite.transform.scale;
scale.set(1,1);
sprite.transf.rom.scale.set(1, 1);
//or preserve aspect ratio
scale.set(1, scale.y / scale.x);
```

**Comment by sotnight** [comment]
Thanks! I got it to work by doing:
```
var sprite;
var mat = new PIXI.Matrix();
sprite.parent.localTransform.copy(mat);
mat.invert();
sprite.transform.setFromMatrix(mat);
```
