### ISSUE TITLE
Pixi-Spine Documentation @ some.github.io/pixi-spine/docs

### ISSUE THREAD

**Issue by adamdanielsdesign** [pixijs/pixi-spine#19]
This the next major project that I will be working on concerning pixi-spine.

The concept is to go through and detail all of the pixi-spine plugin as to what each class, method, and property does, with detailed documentation.

**Changes:**
- Use yuidoc instead of jsdoc
  * Though yuidoc may be less accurate, the intent for this project is to set up the docs as to what the pixi-spine plugin should work/read like, rather than how it currently does. (as there may be numerous changes later/ or soon).

**Summary:**
The intent overall for this would use documentation temporarily as more of an overall concept/thesis type deal, rather than real hardcore documentation that is exactly how it is in the code. So figure the documentation at first wouldn't be pushed to the public as the "where to go" for answers( as it would be a work in progress ). Though later it would be a valid source for detailed info.

**Why yuidoc?**
I'm suggesting yuidoc because it will separate documentation from the source code and allow for what the intent is to play out(conceptually frameworking what the source code should work like, read like, and have it's usage be). This loosens the need for source code to match up.

**Down the road?**
Once there  is a framework laid out as to what pixi-spine is, my opinion is that more and more of it's flaws will be exposed and can thus be fixed much faster than currently. Where currently perhaps there is no direct all-encompassing solution for a problem( as solutions are getting done one by one and generally only relating to issues submitted ).

**Comment by englercj** [comment]
IMO it should just be a `gh-pages` branch on this repo. 

You can manually specify types and name just like in yuidoc in jsdoc, just jsdoc *also* provides static analysis that yuidoc doesn't. To be consistent with pixi.js and because jsdoc has better tooling, I recommend using jsdoc still.

**Comment by adamdanielsdesign** [comment]
@englercj 
Also, I'm saying yuidoc, because currently there are many existing jsdoc comments, that are currenlty helpful(so leave em in for now). yuidoc would be a way to have a co-existing set of documentation.

**Comment by adamdanielsdesign** [comment]
@englercj 
```gh-pages``` as markdown?

**Comment by adamdanielsdesign** [comment]
@englercj @ivanpopelyshev 

- Need 'gh-pages' branch

Here's the dev branch I've set up:
https://github.com/adamdanielsdesign/pixi-spine/tree/gh-pages

Then the assoc site:
http://adamdanielsdesign.github.io/pixi-spine/

**Comment by ivanpopelyshev** [comment]
@adamdanielsdesign cant wait to see the first version :+1:

**Comment by ivanpopelyshev** [comment]
Need help?

**Comment by adamdanielsdesign** [comment]
@ivanpopelyshev Yeah tx!
Haven't really got started on this just yet.

I was gonna go with jsdoc. The yuidoc move maybe would just be extra work considering the concept was to convert it to jsdoc later anyways.

I'll try to the base template and initial setup going this weekend.

Also, I need the branch ```gh-pages``` created at https://github.com/pixijs/pixi-spine/tree/gh-pages for me to start a pull request on.

**Comment by adamdanielsdesign** [comment]
Also, currently I've been looking for a solution for how to approach doc management over multiple branches, like this scenario.

nodegit.org seemed like it might be a solution, for auto updating the branch from the gulp config. However not sure.

The other option was to just manually update the docs when they get to out of date.

**Comment by englercj** [comment]
OR you can just use git subtree :)

https://gist.github.com/cobyism/4730490

Put a script in the repo and just run it to update the docs ad-hoc.

**Comment by adamdanielsdesign** [comment]
@englercj  @ivanpopelyshev 

I sent a feature request to github for adding a github.io root path option to the repo's settings.

If implemented it would allow for a github.io site to be hosted using files located in the master branch of whatever directory, without the need additional scripting and maintenance.

For now I think just manually updating stuff is the same as setting up a script for nodegit or writing some bash.

**Comment by adamdanielsdesign** [comment]
Got response, the requests were submitted to the github team for review or their queue. So we'll see!

**Comment by adamdanielsdesign** [comment]
@englercj  @ivanpopelyshev 

Opened 2 pull requests:
- https://github.com/pixijs/pixi-spine/pull/25 << docs gulp/config files
- https://github.com/pixijs/pixi-spine/pull/26 << gh-pages branch

Status:
- Later will add a gulp or bash script to handle git subtree( would reduce the copy/pasting ).
- Updated adamdanielsdesign.github.io/pixi-spine

**Comment by ivanpopelyshev** [comment]
Ok, merged #25 then created gh-pages branch. Now what?

**Comment by adamdanielsdesign** [comment]
Probably...
- create a gh-pages branch
- then it should work to merge or I'll make another pull request at that point.

**Comment by adamdanielsdesign** [comment]
may need to create a new repo called ```pixijs.github.io```

**Comment by adamdanielsdesign** [comment]
the pull request should delete the files.

**Comment by adamdanielsdesign** [comment]
basically need to delete all the files from the newly create gh-pages branch then merge the pull request.

**Comment by adamdanielsdesign** [comment]
Also,
Current Usage ( as there isn't a script added just yet ):
- clone the pixijs/pixi-spine repo
- clone gh-pages branch into gh-pages folder ```git clone https... gh-pages```
- run ```gulp docs``` to generate docs into gh-pages folder
- cd into gh-pages
- git push to gh-pages branch
- note: a ```git subtree``` script would reduce a lot of this.

**Comment by adamdanielsdesign** [comment]
pull: https://github.com/pixijs/pixi-spine/pull/27

**Comment by adamdanielsdesign** [comment]
just a sec making a fresh pull.

**Comment by adamdanielsdesign** [comment]
updated, new pull at: https://github.com/pixijs/pixi-spine/pull/28

**Comment by ivanpopelyshev** [comment]
It is working, YAY!

**Comment by adamdanielsdesign** [comment]
@englercj  @ivanpopelyshev 

In the contributions section, I'm only showing up for a README.md file a ways, back can this be fixed?

https://github.com/pixijs/pixi-spine/graphs/contributors

**Comment by englercj** [comment]
@adamdanielsdesign Most of the graphs only have to do with the default branch (master).

**Comment by adamdanielsdesign** [comment]
@englercj 
No, it looks like it may be an error with github actually.

This pull notice that my icon(16x16) shows up near the commit:
https://github.com/pixijs/pixi-spine/pull/3

While this merge it doesn't, it shows the default github icon(16x16):
https://github.com/pixijs/pixi-spine/pull/8

**Comment by adamdanielsdesign** [comment]
Sent a contact to github to see *wut up wit dat* lol.

**Comment by adamdanielsdesign** [comment]
@englercj Got response, pretty sure I'm using an old email in my ssh.

**Comment by adamdanielsdesign** [comment]
Alright fixed it, my author email was using old email.
```git config --global user.email```

Also, ```default``` (master) and ```gh-pages``` branches are the only branches that count as a commit.

**Comment by adamdanielsdesign** [comment]
@englercj  @ivanpopelyshev 

**Update:** I got email today from @NathanSweet ( the orig dev of the runtime ) and invited him to contribute to the docs if he likes. So we'll see!

**Comment by ivanpopelyshev** [comment]
@adamdanielsdesign You're the man :+1:

**Comment by ivanpopelyshev** [comment]
@adamdanielsdesign hey. Are you even alive?

**Comment by adamdanielsdesign** [comment]
yeah, skype me: adamdanielsdesign
alive and well!

**Comment by gaplo917** [comment]
@englercj 

http://pixijs.io/pixi-spine documentation is dead.

**Comment by ivanpopelyshev** [comment]
@gaplo917 

Use docs for spine-ts and esotericsoftware runtimes.

+ pixi-specific: https://github.com/pixijs/pixi-spine/tree/master/examples

**Comment by gaplo917** [comment]
@ivanpopelyshev Thanks for your information. I am a new comer to Spine and have no idea that `pixi-spine` is using `spine-ts`.

Please update the Wiki (maybe refer some links to spine-ts / spine Runetimes guides). It may help new comers.

https://github.com/EsotericSoftware/spine-runtimes/tree/3.6/spine-ts
http://esotericsoftware.com/spine-runtimes-guide
