### ISSUE TITLE
Clipping defaults

### ISSUE THREAD

**Issue by jmlee2k** [pixijs/pixi-spine#194]
When creating a clipping attachment in the Spine editor, the default end slot is itself, which will cause all the draw slots to be clipped.

However, in the runtime, when the slot is set to itself, nothing gets clipped, since it never adds anything into the masked container.

I took a look in an attempt to put in a PR, but I'm not familiar enough with the code to do it properly.  Hopefully it's an easy fix.  Basically, if the end slot is set to itself, it should just put everything after it into the masked container.

NOTE: As a workaround for anyone experiencing this, you can simply set the end slot to the top slot in the draw order (which accomplishes the same thing as the default behavior).

**Comment by ivanpopelyshev** [comment]
Oh, that's interesting. Make a PR? :)
