### ISSUE TITLE
Flipping breaks in IE11

### ISSUE THREAD

**Issue by probityrules** [pixijs/pixi-spine#196]
We're running into an issue in IE11 where setting the container's scale in `x` to -1 results in cracking along polygons, almost like there's a rounding or flooring error of some sort. We created the spine facing right, but set its container's `scale.x` to -1 when the spine should face left. This works fine in most browsers, but in IE we're seeing the following (made things semi-transparent to more clearly show what's going on):

![image](https://user-images.githubusercontent.com/1324745/29973216-ce3bc034-8efc-11e7-8502-0a009fe9bf9a.png)

Any recommendations on how to address this?

**Comment by ivanpopelyshev** [comment]
Is is webgl or canvas?

**Comment by probityrules** [comment]
It appears to be the CanvasRenderer.

**Comment by ivanpopelyshev** [comment]
Its very hacky thing: https://github.com/pixijs/pixi.js/blob/dev/src/mesh/canvas/CanvasMeshRenderer.js#L121

It does not round, but browser itself behaving differently when doing masking with fractional vertices.

I suggest you to investigate how many people from your target auditory has webgl enabled. If its more than 99%, just drop the canvas support.

**Comment by ivanpopelyshev** [comment]
Also, I'd like to point out to EsotericSoftware position on canvas:

http://esotericsoftware.com/blog/spine-ts-released#spinets-Canvas

> Due to the limitations of the Canvas API, shearing, mesh attachments, and tinting are not possible and therefore not supported. If you really want mesh attachments, we have included an experimental renderer that can render meshes. While it works correctly in Google Chrome, it may exhibit filtering artifacts along triangle edges in some other browsers.

Pixi actually allows more than original spine-ts runtime.

**Comment by probityrules** [comment]
Thanks! I did a bit of investigation and found that one of our libraries was auto-choosing CanvasRenderer for IE11. I overrode that bit and everything now works as expected.
