### ISSUE TITLE
How do you load a single image from the spritesheet (skeleton.png)

### ISSUE THREAD

**Issue by pizzae** [pixijs/pixi-spine#198]
I know you can load Spine animations with the three files (.png, .json, .atlas), but I want to get some textures from the .png file and use them as static images elsewhere.

How do you do this?

**Comment by ivanpopelyshev** [comment]
As you see in https://github.com/pixijs/pixi-spine/blob/master/src/loaders.ts#L70 , if you load a model, you can access its atlas through "resources['myModelName'].spineAtlas"

This atlas has regions: https://github.com/pixijs/pixi-spine/blob/master/src/core/TextureAtlas.ts#L35

And each region has a texture: https://github.com/pixijs/pixi-spine/blob/master/src/core/Texture.ts#L89

**Comment by ivanpopelyshev** [comment]
You can also load only atlas , without model, just take a few lines from this example: https://github.com/pixijs/pixi-spine/blob/master/examples/preloaded_json.md

**Comment by pizzae** [comment]
Thank you!

For anyone else, this is the code I used to create a new Sprite, using a texture from my sprite sheet:

`    this.sprite = new PIXI.Sprite();
    this.sprite.texture = PIXI.loader.resources.spineSkeleton.spineAtlas
        .regions[5].texture; `
