### ISSUE TITLE
resolution question

### ISSUE THREAD

**Issue by geddski** [pixijs/pixi-spine#199]
I'm using Pixi with a resolution of 2, and exporting object from Spine with a scale of 1. 

When I load my assets, they're showing up in the canvas four times bigger than they should. Any idea what I'm doing wrong?

**Comment by ivanpopelyshev** [comment]
yes, you forgot autoresize on renderer, your CSS width/height must not be multiplied.

**Comment by geddski** [comment]
oh gosh that was it. Had a border set to visualize it and that was removing my height & width of 100%. Thanks!

**Comment by ivanpopelyshev** [comment]
We're lucky to find it out that fast. There are many possible problems with resolutions ;)
