### ISSUE TITLE
how to accomplish zOrder?

### ISSUE THREAD

**Issue by geddski** [pixijs/pixi-spine#202]
Is there a way to set one pixi object to draw on top of another pixi object?

**Comment by ivanpopelyshev** [comment]
Easy way: https://github.com/pixijs/pixi-display/wiki
Normal way: https://github.com/pixijs/pixi-display/

why did you post it in pixi-spine?

**Comment by geddski** [comment]
Ah ok that makes sense, just reordering the children. Thanks!

**Comment by ivanpopelyshev** [comment]
yep, solution  depends on your task complexity. There are multilple solutions.

**Comment by ivanpopelyshev** [comment]
Also, for spine its betetr to just edit it in editor, there's z-order there.

**Comment by geddski** [comment]
Makes sense. In my case I needed to make one spine object sit between the draw order of two slots of another spine object. I ended up just adding another Sprite and matching it's position.

**Comment by ivanpopelyshev** [comment]
Oh, that's case for pixi-display, sorting through containers. That's good that you solved it through easier way.
