### ISSUE TITLE
AnimationState

### ISSUE THREAD

**Issue by klaun76** [pixijs/pixi-spine#205]
Hi.

I've implemented adding listeners as instructed in https://github.com/pixijs/pixi-spine/blob/master/examples/spine_events.md (because of deprecation warning)
They work perfect in 1.5.8 version. 
But when i updated to 1.5.9 method AnimationState#addListener is not accessible anymore. 
I did log spine.state to console and as i see there are less functions/properties in state now.
Could you please instruct what do i need to change to make events working back again ?

thanks in advance
.mrtn

**Comment by ivanpopelyshev** [comment]
That's strange, because there were no changes in that file in 1.5.8-1.5.9. 

That function still exists both in JS and TS.D file. Can you make example?

**Comment by klaun76** [comment]
Thanks for an answer. I'll investigate more on my own. We use spines within large GWT project so it would take some time to create simple example. I'll get back to the issue when i'll have more time. Because your answer indicates that problem is probably between my computer and chair.
FYI: Thumbs up for good work. We recently updated spines from 1.1.3 to 1.5.8 and perfomance is significant. Thanks for all efforts. :-)

**Comment by ivanpopelyshev** [comment]
GWT? wow. I thought I'm the only one who still uses it in games (gameofbombs.com) :)

As for performance, current version is based on `spine-ts` official package which is better than previous official runtime. At the same time, we have special features for pixi apps. 

I work on new plugin that enables extra features for spine: https://github.com/gameofbombs/pixi-heaven , for now it supports dark-light tint (spine3.6) but you can also use dark tint on pixi sprites. New GPU PATCH is under development, it'll speed up deformed meshes seriously.

**Comment by klaun76** [comment]
Thanks for headsup info. (main reason for gwt is that java is only way to keep 20 ppl working together on serious code, and its easier to find java coder than js :-))

**Comment by ivanpopelyshev** [comment]
Well, you can move to typescript if your app is front-only. If its backend, all model logic should stay in java. 

Also I recommend Kotlin, they've added multi=platform projects some time ago: http://kotlinlang.org/docs/reference/multiplatform.html 

I was one of early testers of kotlin 1.1 coroutines, submitted a number of critical issues, and I know for sure that Kotlin dev team are really the best.

**Comment by klaun76** [comment]
Thank you ivan for patience and little chit chat that we had. Of course bug was on my side. Shame on me.

**Comment by ivanpopelyshev** [comment]
I'm glat its resolved. Have fun with GWT, dont forget to look if you can migrate it to kotlin.
