### ISSUE TITLE
Clipping mask does not apply the correct mask if the mask itself was marked as end slot.

### ISSUE THREAD

**Issue by Querijn** [pixijs/pixi-spine#208]
In Spine, if the clipping mask itself was marked as the end slot, everything in the draw order above it applies the mask. In pixi-spine, nothing applies the mask in this case.

I'm going to investigate it, see if I am wrong somehow. Gonna make a PR if needed.

We're on version 3.6.48, PIXI Spine is on a recent master pull.

**Comment by ivanpopelyshev** [comment]
I thought it was fixed, strange. Are you sure you use latest pixi-spine?

**Comment by Querijn** [comment]
Probably not the latest, but probably about a month old. I was trying to setup a debug environment for this, but unfortunately had to do other small tasks. I'll try the absolute latest master after that and see if it fixes the issue.

Thanks for the fast response, I'll get back to you in a couple of moments.

**Comment by Querijn** [comment]
Hey there, just checked it out. The differences between our version and the latest don't seem to update it in any way.

The current that seems to work is a change in SkeletonJSON.ts, where I check if the name of the endslot is the same as the mask name. I'm not sure if names are unique identifiers, so I am going to make a pull request so that you can have a look at it :)

**Comment by ivanpopelyshev** [comment]
Yep, that's interesting. Currently this line checks it: https://github.com/pixijs/pixi-spine/blob/master/src/Spine.ts#L405

**Comment by Querijn** [comment]
Expected result:
![image](https://user-images.githubusercontent.com/3397066/33546574-a6276fe2-d8e1-11e7-902f-e0e499ad0a77.png)

Without it: 
![image](https://user-images.githubusercontent.com/3397066/33546657-e127e41e-d8e1-11e7-8d02-f413a803b15b.png)

I see that line, let me debug what happens there.

**Comment by ivanpopelyshev** [comment]
Nice. I'll check why that line above I mentioned isnt working properly. I'm afraid to make changes to SkeletonJson because that file is 1:1 from spine-ts and I'll forget about it later.

**Comment by Querijn** [comment]
Changing the contents of that if-statement to `clippingAttachment.endSlot = null;` also works as a fix. Debugging the data, the objects seem identical, but then again, I don't know the results of the comparison between two objects.
