### ISSUE TITLE
Animation seem to behave differently on the canvas renderer of PIXI

### ISSUE THREAD

**Issue by Querijn** [pixijs/pixi-spine#213]
Hey there, back again.

I have an object in my game, which looks differently in the canvas renderer, as seen here:
http://irule.at/testing/masks/

The green one is the WebGL renderer, which looks correct. The red one is the canvas renderer, which makes (I assume) "battleship_ver" copy the color of "ripple_front" below it in the render order.

Seems to happen on latest Firefox, latest Chrome and the initial supplied version of Internet Explorer and Edge on Windows 10.

**Comment by Querijn** [comment]
[masks.zip](https://github.com/pixijs/pixi-spine/files/1611162/masks.zip)

Here's the above code, but available in a zip folder.

**Comment by ivanpopelyshev** [comment]
pixi 4.5.1 , I'm sure that bug was fixed in latest release. I remember how I fixed `tint` for canvas.

**Comment by Querijn** [comment]
So this is an issue with Pixi, and not Spine? Because we're not on the latest Pixi version, I reckon.

**Comment by ivanpopelyshev** [comment]
OK, now that's interesting. Its probably a bug in pixi.js , ill look into it.

**Comment by ivanpopelyshev** [comment]
I forgot that issue was fixed but not released yet. pixijs.download/dev/pixi.js - there we go :)

**Comment by Querijn** [comment]
Hey there, seems like we have another issue. It seems the mask doesn't get applied to the animation when sinking. If you click on either animation, the sinking animation starts but doesn't actually show the sinking mask on the canvas renderer.

**Comment by ivanpopelyshev** [comment]
It works here: http://irule.at/testing/masks/ . Are you sure?

**Comment by Querijn** [comment]
Really? Weird, this is what it looks like for me:

![2018-01-16_09-29-44](https://user-images.githubusercontent.com/3397066/34979022-67cd407e-faa0-11e7-863e-76170a6f6cb3.gif)

**Comment by ivanpopelyshev** [comment]
It looks same for me. Whats the difference?

**Comment by Querijn** [comment]
After the explosions in the gif, a mask goes over the ship as if it goes underwater. The issue is, it's not being applied to the canvas renderer one.

![ezgif-4-13be744db3](https://user-images.githubusercontent.com/3397066/34979883-0054a434-faa3-11e7-908a-f8c4b38e8445.gif)

Expected final result:
![afbeelding](https://user-images.githubusercontent.com/3397066/34979897-0afe903e-faa3-11e7-80af-40dc18bd7c7d.png)

The blue tint should be applied to the left one as well

**Comment by ivanpopelyshev** [comment]
Is blue tint at the mask?

**Comment by Querijn** [comment]
Yup, it's called `mask ver` if I recall correctly

**Comment by ivanpopelyshev** [comment]
Pixi canvas renderer doesn't support colors on masks. It is possible to achieve that, its just no one implemented colored or sprite masks for it.

**Comment by Querijn** [comment]
Ah, that would be the issue then. Thanks.

**Comment by ivanpopelyshev** [comment]
Do you really need it, did you find workaround?

**Comment by Querijn** [comment]
Well, it's not a huge issue. The boats going invisible was arguably a higher bug. On the water, they look slightly different from non-sunken boats, so it's not huge.

**Comment by Querijn** [comment]
This issue is fixed, so I closed it. If I wish to make a PR for that implementation for colored masks for PIXI canvas, would that be possible?
