### ISSUE TITLE
PERFORMANCE TEST:  PIXI SPINE vs PIXI ANIMATION

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi-spine#214]
I noticed that he starts having trouble from 350 Objects Spined.

I am interested a little closer to this plugin in pixi, I would like to know what can afect and  impact the performance.
its it the resolution of the png, or the complexity of the exported Dada ?
In my test i used the huge demo sprite, but i would like to know all tricks to get more performance.
the difference, if I use **Pixi sprite animation.**, the engine can hold over 4000 complexe animated rendering elements + bones !
and with pixi spine , only 350 from the test i made.
And strange thing , if i put over 400 SPINE, FPS will fixed to 30 !!!
here test with 
x350 **PIXI SPINE**
https://youtu.be/qoYMQunGiF8
VS
x5000 **PIXI ANIMATION**
https://imgbox.com/Xce2TziQ

What that affects performance and especially what are the tips to optimize it.
Thank you.

ps: test are based on 60fps

**Comment by ivanpopelyshev** [comment]
Do you use meshes? They break pixi batching.

Look at https://github.com/pixijs/pixi-spine/blob/master/src/core/Bone.ts#L89, that transform is calculated for every bone, every frame. How many bones each of your animations have?

**Comment by djmisterjon** [comment]
for the moment am not sure, I study the application only since 2 hours.
The walk animation from test seem have about 14 bones.
So if i understand , more bones the Object have for a animation , more calculation need.

it good  to know that,  thank a lot.
did you have another good tricks and recommendation?

**Comment by ivanpopelyshev** [comment]
Do you have meshes or not?

**Comment by djmisterjon** [comment]
yep only one mesh seem setup for head
![sans titre](https://user-images.githubusercontent.com/24865815/35186720-b2709f10-fde6-11e7-9e99-ca6d1e0a3a95.png)

**Comment by ivanpopelyshev** [comment]
Try remove that mesh.

**Comment by djmisterjon** [comment]
ok, for my project art, I did not intend to use mesh, but these good to know.
thank a lot for all those tips.
if anyone has more trick to maximize performance. You're are welcome

**Comment by ivanpopelyshev** [comment]
Yeah, I know how to optimize it with meshes but its really hard ;) I had version for pixi-v3, you have to wait for pixi-v5 and new pixi-spine plugin.

**Comment by djmisterjon** [comment]
is it for sonne ? this years ?
