### ISSUE TITLE
pixi-spine broken with Spine generated atlas?

### ISSUE THREAD

**Issue by ESPWarren** [pixijs/pixi-spine#215]
I am using pixi-spine.js 1.5.11  and pixi.js version 4.7
I have purchased Spine Pro.

I am using the sample code from the 'Walking Animation' demo in the 'Examples' section of your Github site. I have put the spineBoy json, png and atlas files in a local folder. When the code references the 'spineBoy' json then the animation works perfectly. So the 'player code' is working.....

In that same folder I have also placed the assets for my own animation of a shepherd ('shepherd.json', shepherd.png' and 'shepherd.atlas'). These were generated from Spine. I just used the default settings in spine when I choose 'export'. (i.e. I checked the 'Create Atlas' box).

When I run the page, I get this error:

"Error: Texture Error: frame does not fit inside the base Texture dimensions: X: 337 + 245 = 582 > 1 and Y: 51 + 150 = 201 > 1"

It *seems* to my (newbie) eye that it is mis-calculating the sixe of the base texture (1 !)

I noticed that earlier versions of pixi-spine only worked with specific versions of Spine - so I tried rolling my version back and re-exporting the animation assets - I still get the texture error above...

Any help very gratefully received - I have been googling this for three hours now...

Thanks

**Comment by ivanpopelyshev** [comment]
It should work. Give me a fiddle or a zip file.

**Comment by ESPWarren** [comment]
That's a kind offer Ivan.

But now I feel a bit stupid....

I was putting these files into a new folder to zip up, and tested it - it (almost) worked....and I subsequently fixed the minor issue..

It seems that this was some weird Firefox caching issue. I have had this before and set my cache to 0 mB - it seems that when I forced the browser to reload from a different location, the glitch went..

Sorry for the hassle..thank you again...

Nick

**Comment by ivanpopelyshev** [comment]
And that's how its done! :)

"Have you tried turning it off and on again?"
