### ISSUE TITLE
dragonBones export spine , not work properly with IK ?

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi-spine#216]
is that these normal that when i export JSON spine 3.3 from DragonBone pro, my animation break and not play IK ?

do i absolutely need buy spine pro for export correct Json work with this pixi-spine ?

**Comment by ivanpopelyshev** [comment]
this version is for 3.5. 

3.3 and 3.4 had breaking changes regarding IK.

**Comment by ivanpopelyshev** [comment]
I have an old branch for 3.3, you should try it: https://github.com/pixijs/pixi-spine/tree/1.1-spine3.3

**Comment by djmisterjon** [comment]
ok thank i will make i try now thank

**Comment by djmisterjon** [comment]
with this version i get a 
**pixi.js:4735** Uncaught Error: Cannot add resources while the loader is running.
i use the loader example from demo, but maybe this version are too old ?

```javascript
PIXI.loader
    .add('SSA/actor/a1/dbProject/player1_player1.json') // ,spineLoaderOptions)
    .load(onAssetsLoaded);
    var Cage = new PIXI.Container();
    
    function onAssetsLoaded(loader,res) {
// stuff
}
```
also what do you think about this , it can work for my case ?
https://gist.github.com/dmknvk/dbb4fc4979d214453a066c68cfe310bb

**Comment by ivanpopelyshev** [comment]
Oh, right, you have to change the code for latest pixi-v4. Please modify the loader, add new resources to parent. Just look at old implementation of loader and new one, and backport it.

**Comment by djmisterjon** [comment]
I do not have the expertise to do this kind of manipulation unfortunately.
Thanks anyway, you answered my question, I think I do not have the choice to switch to sprite 2d pro, hoping not to fall on another major problem with this soft.
