### ISSUE TITLE
spine 2D Mesh bug

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi-spine#218]
Hi, at the moment of testing, there seems to be an interpretation bug in the Runtimes about mesh.
Mesh seems to be getting crazy.

I have take a screen video to show you the bug, what i can do for fix this ?
The bug appear at 1:00min
https://youtu.be/67YTPC8IhDw

thank

**Comment by ivanpopelyshev** [comment]
What's your spine editor and pixi-spine runtime version?

**Comment by djmisterjon** [comment]
_the version are not indicate in the pixi-filters.js_
but i download the last one and try again
**pixi-spine:** 1.4.0
**spine pro:** 3.6.52
**pixi.js:** 4.6.2

following your advice on performance, I tried to minimize the vertices
There are only 14 for an acceptable rendering animation.
![vertice](https://user-images.githubusercontent.com/24865815/35770740-e07b72c8-08ee-11e8-9ebb-1ee01f8fc5c3.jpg)

the vertices have BONES with a weight
![weigth1](https://user-images.githubusercontent.com/24865815/35770746-f82fe12e-08ee-11e8-85b0-73ab797d66a9.jpg)

and all vertices and hairBones are controlled by a MASTERCONTROLER like a joystick, for make the animation of the hair.
This is an experimental case.
![controler](https://user-images.githubusercontent.com/24865815/35770751-1e493be4-08ef-11e8-8280-1d8832527bb3.jpg)

**Comment by djmisterjon** [comment]
the problem is more visible on this print screen
at Left the idle ok, at right the idle but bugged vertice ?
![aefaefaeg](https://user-images.githubusercontent.com/24865815/35770845-3764c588-08f1-11e8-98e2-e1e0e8cd6eee.jpg)

**Comment by ivanpopelyshev** [comment]
ok then, give me that model and ill study it.

**Comment by djmisterjon** [comment]
ok not problem i can share you on a cloud, on skype or email ? i don't have your email

**Comment by ivanpopelyshev** [comment]
yeah, remove it

**Comment by djmisterjon** [comment]
ok thank a lot , i know your very buzzy.
I will still try to start at 0 with another technique.
Faith that you would have no solution.
it was a prototype to try to understand some techniques with your plugin.
I maybe overcomplicate the **Bones** and the **transform_constraint** on mesh .

**Comment by djmisterjon** [comment]
@ivanpopelyshev 
Good I isolate the problem!
This occurs when you are targeting **constraints** on **meshes** rather than on bones. (and also have a Bones that control all mesh and child bones)
this is not really a problem, because by replacing all **transform_constraint** for target only bones to bones the result are perfect and its fix.

I just need avoid target **meshs** with **transform_constraint**.
for my animation goal, this is not a issue, but for someone who wants a super complexe animations, it could cause him problems.

I can progress now :).
Thank you for your time.
I keep you update if I hit another wall.
