### ISSUE TITLE
TrackEntry missing AnimationStateListener ?

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi-spine#220]
it seem to miss the class **AnimationStateListener** when return TrackEntry?
http://esotericsoftware.com/spine-api-reference#TrackEntry-listener
![trackentry-missing](https://user-images.githubusercontent.com/24865815/35788571-fa84d572-0a03-11e8-8bc1-0032dc6920b3.jpg)

**Comment by ivanpopelyshev** [comment]
Ok, whats the problem? :)

**Comment by ivanpopelyshev** [comment]
How can I fix it?

**Comment by djmisterjon** [comment]
I think it was a misunderstanding on my part, because I was starting.
But these resolutes.
I thought I could inject listener with this property, but you can not.
take a look the message code from Nate.
http://esotericsoftware.com/forum/Best-way-for-random-animations-9892


His message misled me a little, but I finally found the right way.
```javascript
    this.GUI.state.setAnimation(0, 'idle', true);
    this.GUI.state.setAnimation(1, 'show', false);
    this.GUI.state.tracks[1].listener = { 
        complete: function(trackEntry, count) { alertify.dismissAll(); alertify.warning('CORE LOADING COMPLETE',2); pixiPME.startCORE(); }
    }
```
