### ISSUE TITLE
Spine export settings?

### ISSUE THREAD

**Issue by dovy** [pixijs/pixi-spine#221]
I keep trying to get my Spine to export. I was successful in loading it, but the canvas is black and nothing shows up. Am I doing something wrong?

**Comment by ivanpopelyshev** [comment]
Make sure you have json file, image file and atlas file. 

Make sure that app can show one of exports from https://github.com/pixijs/examples/tree/gh-pages/required/assets/spine

**Comment by dovy** [comment]
Using spine 3.6.52.

Here's a page I'm trying to load my export into:
https://cryptopaws.github.io/index.html

Again, no errors in the console. Everything's fetched. Just never loads.  :(

**Comment by ivanpopelyshev** [comment]
Solved.

```js
goblin.scale.set(0.1);
goblin.position.set(app.screen.width/2, app.screen.height);
```

**Comment by ivanpopelyshev** [comment]
I've got it when I asked for `goblin.getBounds()` and saw big numbers. also Y was big negative and "y+height" was less than zero.

**Comment by dovy** [comment]
Fantastic. Now I need to see if I can load this as a SVG so it's not so blurry...

**Comment by ivanpopelyshev** [comment]
Are you ready to re-render all svg parts when scale changes? Pixi has only one vector renderer - Graphics. 

Its possible to make, and if you solve all the problems, please share it with community - you'll be our hero!

**Comment by ivanpopelyshev** [comment]
Its possible to make, and if you solve all the problems, please share it with community - you'll be our hero!
As always, my sentences are both inspirational and sarcastic. That task belongs to the higher difficulty of pixi tasks.

**Comment by ivanpopelyshev** [comment]
Basically, that's an artifact that is part of "The Holy Flash Resurrection"

**Comment by dovy** [comment]
One more question. As I grow the canvas my animations looks stretched. How do I have the scene auto-adjust proportionately to account for scale?

**Comment by ivanpopelyshev** [comment]
You have to call `renderer.resize` and pass `innerWidth` and `innerHeight` there, instead of changing canvas CSS. Btw, pixi can change css for you with "autoResize:true" options in renderer.

**Comment by dovy** [comment]
I noticed that works fine for the scene, but not for the elements with scale. So I did a bit more JS magic with height and ratio and it works pretty well.

https://cryptopaws.github.io/

**Comment by ivanpopelyshev** [comment]
So far I didnt see any good scaling solution, its always project-dependent.

**Comment by dovy** [comment]
Agreed. Is there any way to detect the current height/width of a skin? If so I could dev a generic solution. The issue is the positioning is kind of weird. But if I had those details given the default scale, we could make a height scale and adjust all sprites accordingly.

**Comment by ivanpopelyshev** [comment]
(0,0) is at the same place as in spine, coordinates are the same as in spine, so you have to apply same scale to all spine models.

Now, I consider that you just have spine files from chinese animators and you dont know what to do with their scale:

How do you think its possible to define a height of something complex and animated? The height changes every frame.

Pixi `getLocalBounds()` method takes into account all the meshes and rectangles. However, it takes only current frame, and I dont know if that satisfies you.

The only good way is to beat the artist^W^W^W ask the artist to put it there. and it'll be accessible through https://github.com/pixijs/pixi-spine/blob/master/src/core/SkeletonBounds.ts - that class is from original `spine-ts` runtime and it takes into account only BoundingBoxes but pixi runtime does not use that class, you have to create an instance, pass `spineObj.skeleton` to it, update when you need it.

I expect a donation to https://www.patreon.com/user?u=2384552 after my detailed answer :)

**Comment by dovy** [comment]
@ivanpopelyshev thanks for the details. I did not expect to get the animated height/width but the base height/width. From there you can derive a ratio of that size to the scene and adjust accordingly. 

I will donate. You've done great work here. I may also in the short future donate some resources to make Pixi.js work with SVG and spine.  ;)

**Comment by ivanpopelyshev** [comment]
@dovy please define base height/width. I might use that definition in future :) Thank you!
