### ISSUE TITLE
Read atlas from cache.

### ISSUE THREAD

**Issue by congtung10t2** [pixijs/pixi-spine#224]
the last time what I did is here: https://github.com/pixijs/pixi-spine/pull/222 
but i see at L6664, it's still read atlas file again. but I'm not sure this will read from cache or read from file as new one.  I guess it read as new one.
I stored atlas file at host so every skeleton should read atlas once instead of read again. How can I do it? (just for optimization). As I see, it read png file once, but it keep reading atlas file again.

**Comment by congtung10t2** [comment]
should we take out the atlas loading from json loading?  when we can load atlas first. When we load a json file, we just point it to atlas file.

**Comment by ivanpopelyshev** [comment]
Please look again, there's a way to specify whole atlas. Once you load atlas, then you load all your json files. I'm busy right now, I'll respond later.

**Comment by congtung10t2** [comment]
I saw we already have a way to load image first and json later. but it's not good to me. cause what i want is load .atlas file directly instead of each attachment.

**Comment by ivanpopelyshev** [comment]
Try this one: https://github.com/pixijs/pixi-spine/blob/master/examples/preload_atlas_image.md#how-to-use-generated-or-preloaded-base-textures

Just preload necessary textures and then load all spine objects.

**Comment by congtung10t2** [comment]
thanks ivan but what i want is we load from .atlas file. cause I have big game, i cannot load 1 by 1 image. and what i get from artist is atlas file with a lot of image inside, it's not a single image

**Comment by ivanpopelyshev** [comment]
Those two images are pages of same atlas, you just need an object with "page_0" and your atlas.

I still didnt look in your issue, I'm very busy. I'm just suggesting existing solutions.

**Comment by congtung10t2** [comment]
ok. my point is optimization. I want combine many animation to use 1 atlas file with once time reading atlas file. At your suggest, you load many images, that mean it will increase number of file. I don't want to increase number of file.

**Comment by ivanpopelyshev** [comment]
It works with one image. If you cant understand how to do it based on https://github.com/pixijs/pixi-spine/blob/master/examples/preload_atlas_image.md#how-to-use-generated-or-preloaded-base-textures , you have to wait when I have free time to make a demo for you.

**Comment by congtung10t2** [comment]
hmm. look like we have some mistake. 
what i want is simple like: I have an atlas file: abc.atlas
then i have 2 json file: 123.json 345.json
now i want read abc.atlas file first, added to loader. How can i do it? (atlas file export from spine2d).
after that,  how can I do to load skeleton file with that atlas already done loaded. 
Sorry for my bad english make you can't understand :(

**Comment by ivanpopelyshev** [comment]
```
loader.add('atlasImage', 'abc.png', (loader, resource) => {
    // i dont remember if first paramer is actually loader here
    loader.add('spine1', { metadata: { metadata_from_that_example_for_abc_png })
        .add (...)
});

loader.load();
```

**Comment by ivanpopelyshev** [comment]
Also, if you have custom logic for loading, please just copy my Spine loader and make your own. You have to understand how it works anyway.

**Comment by ivanpopelyshev** [comment]
You can preload whole atlas and then specify it with `{metadata: {spineAtlas: atlas}}`

**Comment by congtung10t2** [comment]
this is what i want: https://github.com/pixijs/pixi-spine/pull/229.
I preload whole atlas text. then I create skeletonData from raw atlas text file. 
Thank you for your kind support

**Comment by ivanpopelyshev** [comment]
Good job!

Congratulations on becoming pixi-spine contributor.

pixi-spine npm package version 1.5.13.

Do you want to add example for other people, as well?

**Comment by congtung10t2** [comment]
ok I will do it. thanks @ivanpopelyshev

**Comment by congtung10t2** [comment]
@ivanpopelyshev after you merged it https://github.com/pixijs/pixi-spine/pull/232 
we can close this issue as well. thanks

**Comment by lancety** [comment]
hi @ivanpopelyshev , after reading  these commonts and confirmed I am using the #229 version code,  I have a question about a issue caused by the duplicated atlas loading

```js
pixiApp.loader.add(spineName, spineUrl)
            .load(function (loader, resources) {
                const spine = new Spine(resources[spineName].spineData);

                spine.skeleton.setSkinByName('default');
                spine.skeleton.setSlotsToSetupPose();

                _setAnimation(spine, defaultAnim);
                resolve(spine);
            })

```

I am using above code to load and create Spine.   By checking the logic with several breakpoint, I can see the sequence is 
- call loader.add of the assetName
- it trigger loading assetName.atlas
- after atlas loaded it triggers loading the png file
- after the png file it triggers some callbacks which then calls add assetName.atlas again 

It is ok it blocks loading the load of atlas, but with that error, the ".load" callback of above sample code wont be triggered.  Is there any solution to make the above callback work? 
Cheers~~

**Comment by ivanpopelyshev** [comment]
Sorry, you have to debug it yourself, Im currently away from the project. Please ask at https://github.com/pixijs/pixijs/discussions

Yes, there is a solution, no, i dont remember where was it. If you find, make PR to put it in `examples` so other people will know :)

**Comment by lancety** [comment]
I will make workaround fix for now. Thanks for quick response~  :)

**Comment by congtung10t2** [comment]
@lancety: Hello, 
here is my example for preload atlas text seperate. it's working fine 4 years ago but not sure still worked now 
https://github.com/pixijs/spine/blob/master/examples/preload_atlas_text.md

**Comment by lancety** [comment]
thanks for quick response @congtung10t2 , my understanding about the example is - the options allow me to pre load atlas.  then use it with json to load rest.
I am trying to use load callback to create spine when it is finish loading. but no matter which way I use, it finally will call "createSkeletonWithRawAtlas" in #229 , and "createSkeletonWithRawAtlas" will later causing the exception of duplicated atals loading, which fail the callback in '.load'

I made a noob solution by using interval and try catch as a quick fix ;D 

```js

        try {
            pixiApp.loader.add(spineName, spineUrl);
            pixiApp.loader.load();
        } catch (err) {
            console.error(err);
        }
        const interval = setInterval(()=>{
            const resource: iPixiLoaderResource = pixiApp.loader.resources[spineName];
            if (resource.spineDataReady) {
                const spine = new Spine(resource.spineData);

                spine.skeleton.setSkinByName('default');
                spine.skeleton.setSlotsToSetupPose();

                _setAnimation(spine, defaultAnim);
                clearInterval(interval);
                resolve(spine);
            }
        }, 50)

```

**Comment by lancety** [comment]
I just reviewed the example again, I guess the purpose of this example is saying - load json and atlas data first, then use them to make spine like this link, right?   https://github.com/pixijs/spine/blob/master/examples/preloaded_json.md

**Comment by congtung10t2** [comment]
Not sure I understand you but step 1 just for loading raw text. 
Step 2 will load json as the animation. 
Example: There are 5 animations (5 json) using same atlas file, you need to load the atlas file first. 
Step 2 will do 5 times with 5 json file. 
it means atlas - json is 1-n relationship. 
Hope it will help you. At that time, I think it difference, I'm not sure about the example you give me. It can be another problem.

**Comment by congtung10t2** [comment]
the purpose of loading raw atlas text is reducing the number of request to the same atlas file. Which cause the traffic for server. Not too much functionality at it

**Comment by lancety** [comment]
my game dont have that 1-n case yet, but good to know I can do it this way.
as Ivan said, I guess my code might have bug causing atlas being loaded twice, or maybe it is known issue.  I will use interval as solution for now until need to improve it.  
thanks for your explaination 👍
