### ISSUE TITLE
compute maximum width height animation

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi-spine#228]
hi, its possible to compute or calculate the maximum bounds (width height) of animation, without use a bgBox in the editor?
I need a way to calculate a ratio but from the full animation.
![sans-titre-1](https://user-images.githubusercontent.com/24865815/36993227-42702c50-207b-11e8-84eb-28e40e412f90.jpg)
thank

**Comment by ivanpopelyshev** [comment]
I recommend put a bounding box  inside spine editor, and override width/height props to look for this thing. Its possible and I explained it either on forum, either here. I cant find it here, must be on forums somewhere.

**Comment by djmisterjon** [comment]
#104

**Comment by djmisterjon** [comment]
ok, it's really a shame because I wanted to avoid editing all demo spine object for my experimentation.

**Comment by djmisterjon** [comment]
@ivanpopelyshev 
I have offered a possible solution in JAVA, but I have a good deal to translate. Can you tell me if these possible with vorte module.
Think of them as I am good, because I block, I can't not find a way for compute frames.
Original post here: http://esotericsoftware.com/forum/compute-maximum-width-height-animation-10028
You have also a video that show what am trying to do.
```javascript
      // Check ratio and set Sprite Size for fit in Cage rectangle
    function resizeSpriteRatio(spine,w,h,sW,sH){
        console.log4('containerSpine: ', spine);
        let fps = 1 / 15;
        let time = 0;
        let currentAniName = spine.state.tracks[0].animation.name; // get the name of animation player in track 1
        let animation = spine.spineData.findAnimation(currentAniName);
        while (time < animation.duration ) {
            console.log(`time: ${time} width: ${spine.width}`);
            animation.apply(spine.skeleton, time, time, false, null, 1, false, false);
            spine.skeleton.updateWorldTransform();
            //array.forEach(element => { }); //? spine.state.tracks[0].attachmentThreshold ?
        time += fps;
        }
        // TODO: old code to merge
        //var ratio = Math.min(w/sW, h/sH); // fit to BG Scale
        //if(ratio<1){ spine.scale.x = ratio, spine.scale.y = ratio };
    };
```

thank a lot ivan

**Comment by djmisterjon** [comment]
ok finaly solved youpi!
thank a lot for help, now it work good, i need to draw a Bounding Box at frame 0 that say limit of the animation.

```javascript
      // Check ratio and set Sprite Size for fit in Cage rectangle
    function resizeSpriteRatio(spine,w,h,sW,sH){
        console.log('containerSpine: ', spine, spine.width);
        var slot = spine.skeleton.findSlot('size');
        if(slot){
            let vertices = slot.attachmentVertices;
            let rec = new PIXI.Rectangle(vertices[0], vertices[1], vertices[4]-vertices[0], vertices[5] - vertices[1]);
            var ratio = Math.min(w/rec.width, h/rec.height);
            if(ratio<1){ spine.scale.x = ratio, spine.scale.y = ratio };
        }
    };
```
![spine animation](https://user-images.githubusercontent.com/24865815/37008677-44751430-20b1-11e8-817e-22ca1ec2c8cc.gif)
