### ISSUE TITLE
importing Spine json doesn't work when filename has url-parameters to prevent cachingissues

### ISSUE THREAD

**Issue by Friksel** [pixijs/pixi-spine#235]
Not sure if this an issue of pixijs loader, or pixi-spine. So I report it on both sides.
When using pixijs with spine-js and using the loader for importing the Spine json file the file cannot be parsed when we use a versionstring in the filename.
So this works:
`this.data.loader.add('goblins',  'spine/goblins.json');`
but this doesn't:
`this.data.loader.add('goblins',  'spine/goblins.json?v=1.0.1');`

I understand the loader is looking for its atlas and spritesheet files with the same name as the json, but it would be better in my opinion to be able to keep the version in to prevent caching issues, like we can use with images and javascript as well.

### Expected Behavior
The loader interprets the filename, knows there are parameters attached and adds the parameters back to the atlas and spritesheet files during load. That way we can be sure we prevent caching issues when changing the url parameters-string.

### Current Behavior
Loading halts, throwing errors in the console saying it cannot find the 'root'-filter.

### Possible Solution
Load the json with the url parameters attached, then add those parameters to the url of the files it needs to load with the json. 

### Steps to Reproduce
Add `?v=1.0.1` to the json in the loader-add

- `pixi.js` version:  4.7.3 (together with spine-js)
- Browser: Chrome
- Device: Desktop

**Comment by ivanpopelyshev** [comment]
Good idea. Can we add this thing to metadata as an extra parameter?

Alternatively, you can just use metadataAtlasSuffix and your custom async image loader that adds `?v=1` for the image.

You can debug here: https://github.com/pixijs/pixi-spine/blob/master/src/loaders.ts#L32 , or try wait a few weeks when i have time to solve it personally.

**Comment by Friksel** [comment]
Hi @ivanpopelyshev . Thanks for your quick reaction. I was already writing a follow up, because I just found out the errors are not there anymore after removing the dots from the url parameter.
Because I was using `?v=1.0.1` , it was throwing errors and stopped loading, but when I changed it into `?v=1` it does at least load without errors. Which makes sense since the loader obviously strips out the extension to change it to .atlas or .jpg/.png etc.
Looking at devtools the url parameter doesn't make it to the spritesheet and .atlas-files though, so at the moment it seems 'versioning' to prevent caching issues doesn't work this way.

Would indeed be great if there would be some way to do this without having to change the filename itself (which is far from ideal with git-versioning of that file, because it looses the history everytime the file changes).
Not sure what you mean by metadata as a parameter; does the loader uses some metadata object? Having some setting sounds like a good solution!

My suggestion would be to have some boolean setting per loader-add to allow url-parameters (also with dots) from the file-url and copy then to both the .atlas-url and spritesheet files linked. Or maybe in the add-method of the loader an extra optional parameter for setting a version of the file (string) that gets copied to the .atlas and spritesheets linked to the json.

Thanks again. For now I just change the filename to prevent caching problems, so I'm not really in a hurry. But would be great to have some better way in the future, so I'll keep an eye on the changelogs. Thanks again! Also for your great work on the project. Pixi really keeps innovating and it really is my number one choice for pixelworks online, I love it!

**Comment by ivanpopelyshev** [comment]
`loader.add('something', { metadata: { .. } } )` , metadata is passed to middleware that I referenced. Look at examples : https://github.com/pixijs/pixi-spine/tree/master/examples .

Every time someone finds another good case for spine, they make PR for me to add something in metadata and examples. 

Its a loading logic and not math, its not possible to make `vanilla` implementation that satisfies everyone. That's why I accept those kind of PR's.

**Comment by ivanpopelyshev** [comment]
However, I think that your case is actually covered by this field in pixi resource loader: https://github.com/englercj/resource-loader/blob/master/src/Loader.js#L52

**Comment by Friksel** [comment]
Yes, indeed, loader.defaultQueryString as you're pointing out is exactly what I need and an even better solution to what I was looking for! Now I only have to set the version once for all assets with
`loader.defaultQueryString = `v=${version}`;` Nice!

Thanks for your help! Case closed! :)
