### ISSUE TITLE
Event-datavalues are parsed directly in the event, instead of in event.data

### ISSUE THREAD

**Issue by Friksel** [pixijs/pixi-spine#237]
Custom event data variables (`intValue`, `floatValue`, `stringValue`) are there inside the `event.data`-object, but are never filled with the actual data. The actual three values seem to go directly into the event-object instead.

So this is how each event-object looks like:
![eventobject devtools](https://user-images.githubusercontent.com/3089978/38668939-5f867406-3e45-11e8-8bf2-adc23a3ab362.JPG)

I would expect to find all custom values and the eventname inside the `event.data` object, not directly in the `event`-object. Or else; all data values (including the event-name) directly inside the event-object having no data-object at all.

This looks wrong to me since we're having redundant data that will never be filled and used.

This is how the event-part of the json looks like:
![events json](https://user-images.githubusercontent.com/3089978/38669249-27e83362-3e46-11e8-9b7a-be77ca0d7df9.JPG)

I'm using latest versions of both PIXI as pixi-spine.

**Comment by ivanpopelyshev** [comment]
Can you please look in the spine-ts 

https://github.com/EsotericSoftware/spine-runtimes/tree/3.6/spine-ts/
https://github.com/EsotericSoftware/spine-runtimes/tree/3.7-beta/spine-ts

whether its the case for official spine runtimes too?

**Comment by Friksel** [comment]
I'm using Javascript, not Typescript. But I will take a look

**Comment by ivanpopelyshev** [comment]
You can load your spine file in one their runtimes (webgl or threejs), like you do it with pixi-spine and see what appears in console.

**Comment by Friksel** [comment]
That is strange, they're doing the same thing:

![event](https://user-images.githubusercontent.com/3089978/38669820-85a1f5aa-3e47-11e8-9e4c-724f8f50dd98.JPG)
![eventdata](https://user-images.githubusercontent.com/3089978/38669824-86e4d112-3e47-11e8-8fde-9e8cabd25486.JPG)

I hardly believe it makes sense having all three custom variables (intValue, floatValue and stringValue) in both the event-object itself as well as in the data object within. There is only one way to set these values from within the spine editor.

**Comment by ivanpopelyshev** [comment]
Can you please create an issue there and reference this issue in it?

**Comment by Friksel** [comment]
Yes, I'm already writing one

**Comment by Friksel** [comment]
https://github.com/EsotericSoftware/spine-runtimes/issues/1100

**Comment by Friksel** [comment]
EsotericSoftware/spine-runtimes/#1100

**Comment by Friksel** [comment]
EsotericSoftware/spine-runtimes#1100

**Comment by Friksel** [comment]
@ivanpopelyshev Just got a reaction on the matter:

> It's not wrong. EventData contains the default values for the event in the setup pose. When you add an animation to a skeleton, and key an event, you can set values of these properties specifically for this key of the event, which can deviate from the default values.

So that's actually really clever and useful!

Case closed ;)
