### ISSUE TITLE
convertToNormal 

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi-spine#239]
I do not know if it's a good idea, but it works well on my side, maybe add to the library.
Simply add the suffix you wish in spines2D slots to identify the normal ones.
```javascript
        Spine.prototype.convertToNormal = function (normalSuffix) {
            for (let i = 0, len = this.skeleton.slots.length; i < len; i++) {
                const slot = this.skeleton.slots[i];
                const slotContainer = this.slotContainers[i];
                if(normalSuffix){ //normalSuffix attach to a slots name ex:"_n"
                    if(slot.attachment && slot.attachment.name.indexOf(normalSuffix)>-1){
                        slotContainer.parentGroup = PIXI.lights.normalGroup;
                        slotContainer.isNormal = true;
                    }else{
                        slotContainer.parentGroup = PIXI.lights.diffuseGroup;
                        slotContainer.isNormal = false;
                    }
                }else{
                    delete slotContainer.parentGroup;
                    delete slotContainer._activeParentLayer;
                }
            };
        };
```

++ a method for hide or show normal slots if need

```javascript
        Spine.prototype.hideNormal = function (normalSuffix) {
            for (let i = 0, len = this.skeleton.slots.length; i < len; i++) {
                const slot = this.skeleton.slots[i];
                const slotContainer = this.slotContainers[i];
                if(normalSuffix){ //normalSuffix attach to a slots name ex:"_n"
                    if(slot.attachment && slot.attachment.name.indexOf(normalSuffix)>-1){
                        slotContainer.renderable = false;
                    }
                }else{
                    slotContainer.renderable = true;
                }
            };
        };
```

**Comment by ivanpopelyshev** [comment]
Sorry, I was too busy with 3d. You have to wait when i have time to debug that thing. That place is very difficult to debug, I remember that i had problems there. Maybe ill just make spine-lights integrations personally.

**Comment by djmisterjon** [comment]
@ivanpopelyshev 
Thanks you very much, I put it in standby for now.
And bravos for the new super 3d rendering, I share your achievement.
You are super.
I will experiment this camera engine when I would be there in my project.
I will probably try to merge your camera plugin with simple physic plugin from .
https://github.com/schteppe/p2.js#demos

Your work really allows us to start having interesting content for those who do not wish to launch with Unity engine.

**Comment by djmisterjon** [comment]
Also tell me is you want a model with normal integration.
Just tell me where i can download the spineBoy , and i will build for you 2 kind of normal spineboy for help you.
I see for now 2 kind of workflow compatible with spine and normal.
one with SKIN normal, and other one with Slot normal.

If you don't have share source link for spineBoy, tell me i will made you one for you can also publish in Demo 
http://pixijs.io/examples/#/spineNormal/

Just tell me , i want help you and and reduce your workload.

**Comment by djmisterjon** [comment]
For normal skin , i think we should wait the next release.
You can see it not available for now, but inside are inside the column **Ready**.
`Allow multiple skins to be active at once`
https://waffle.io/EsotericSoftware/spine-editor

If I understand correctly, we will can add normal skin Attachment at the same time rendering the diffuse skin Attachment ? maybe.
