### ISSUE TITLE
is there a usage example? this module isnt working for me

### ISSUE THREAD

**Issue by mreinstein** [pixijs/pixi-spine#24]
I'm trying to use pixi-spine as a commonjs module. I have pixi.js@3.0.2 and install pixi-spine@1.0.1. My code looks like this:

```coffeescript

pixi = require 'pixi.js'
spine = require 'pixi-spine'


animation = new spine 'assets/spine.json'
```

this throws an error at run time:

```
Uncaught TypeError: object is not a function
```

Any idea why this won't work? While I appreciate have more modular includes, pulling this out of core pixi with no examples on how to use it is kind of rough. :/

**Comment by ivanpopelyshev** [comment]
They changed something in PIXI 3.0.2, require isnt working anymore.

@englercj help please!

**Comment by ivanpopelyshev** [comment]
Also, just passing filename wont work, AnimCache has been removed in 3.0.2, I asked @englercj about it, I will return it soon.

At the current moment, 

```javascript
assetLoader = new PIXI.loaders.Loader();
assetLoader.add('spineBoy', 'assets/spineBoy.json');
assetLoader.load(function (loader, resources) {
   //create the stage
   stage.addChild(new PIXI.spine.Spine(resources.spineBoy));
});
```

**Comment by englercj** [comment]
Just because PIXI is now global doesn't mean your exports should no longer work.

The thing about not being able to `require('pixi.js')` *only applies to plugins*. User code can require all day long.

The first thing I notice about your code @mreinstein is that you are not sure of what the export of this module is. Here is what is exported:

https://github.com/pixijs/pixi-spine/blob/master/src/index.js

So you are treating that object as if it were a function, and that is why you get that error. But just like @ivanpopelyshev mentioned, you can't just pass a string because `AnimCache` isn't implemented yet. You will need to load the spine data via the loader then pass it as the first param to a new spine object.

What you are looking for is `new spine.Spine(loadedSpineData);`.

**Comment by mreinstein** [comment]
I've tried updating the code but it still isn't working:

```javascript
loader = new pixi.loaders.Loader();
loader.add('spineCharacter', 'spine-data-1/HERO.json');

loader.load(function (loader, resources) {
  var animation = new spine.Spine(resources.spineCharacter);
});
```

I get this console error when constructing the animation variable:

`Uncaught TypeError: Cannot read property 'length' of undefined`

Which is on this line  https://github.com/pixijs/pixi-spine/blob/master/src/SpineRuntime/Skeleton.js#L10

**Comment by mreinstein** [comment]
Hmm so one thing I've noticed; a new version of pixi-spine hasn't been published to npm since April 1 (1.0.1.) 

That's the version I have installed. Is it possible that the code is stale, and needs to be updated on npm?

**Comment by ivanpopelyshev** [comment]
Yes, I dont know how to update it in npm. Try github version, we just changed it two days ago. @englercj can you update it please?

**Comment by englercj** [comment]
Sure, sorry about that! I'll have to add you as a publisher to that module.

**Comment by mreinstein** [comment]
I've upgraded to 1.0.2, and I'm still getting the error. I've also tried changing one line to:

```javascript
var animation = new Spine(resources.spineCharacter.data);
```
Any ideas?

**Comment by mreinstein** [comment]
Ok, I've figured out why this isn't working. Here's how I fixed it:

```javascript
var animation = new Spine(resources.spineCharacter.spineData);
```

**Comment by cinkonaap** [comment]
I am trying to get it running without require JS:

`<script src="bower_components/pixi/bin/pixi.js"></script>`
`<script src="libs/pixi-spine.js"></script>`

and while loading page I get 

`Uncaught Error: Cannot find module 'pixi.js'` @ `_prelude.js:1`

**Comment by englercj** [comment]
That was my fault, forgot to update the builds on the latest version. Just released v1.0.3, please try that one.

**Comment by cinkonaap** [comment]
@englercj works like a charm :+1:

**Comment by mreinstein** [comment]
@englercj  thanks for adding a usage example. I was about to fork and add a README but you beat me by 25 mins. :)
