### ISSUE TITLE
[Question] Where is the doc/API reference?

### ISSUE THREAD

**Issue by birdkingz** [pixijs/pixi-spine#247]
Hi, I'm new to Spine and Pixi. May I know where can I read about the complete doc of pixi-spine API reference/tutorial besides the one that I found in [examples](https://github.com/pixijs/pixi-spine/tree/master/examples) folder?

**Comment by ivanpopelyshev** [comment]
there's no doc on pixi-spine API. You've found examples for deep pixi - spine integration. 

1. [pixi examples](http://pixijs.io/examples/#/spine/dragon.js)
2. Original [spine-ts](https://github.com/EsotericSoftware/spine-runtimes/tree/3.6/spine-ts/) runtime.

**Comment by birdkingz** [comment]
But I couldn't find any example on how to trigger **events** which setup in Spine.

**Comment by ivanpopelyshev** [comment]
https://github.com/pixijs/pixi-spine/blob/master/examples/spine_events.md

**Comment by birdkingz** [comment]
OMG, I must have missed out this example. 
Sorry, it's my bad.
