### ISSUE TITLE
Clipping mask never applied in runtime rendering

### ISSUE THREAD

**Issue by kulabros** [pixijs/pixi-spine#252]
I'm having problem with clipping mask, that is not applied in runtime as expected. I've tried my custom animation and also demo example - assets and code (spineboy - clipping demo) and the problem is the same - in editor and also in skeletonviewer is everything ok and masked. But, in pixi.js runtime rendering not. I'm on: pixi.js 4.6.2. (or 4.8.0.), pixi-spine 1.4.2., editor 3.6.52. Assets are loaded with pixi loader and new Spine instance is created with spineData when it's assets are loaded, added to stage.. And clipping mask is never drawn, even with the demo example assets.. What's wrong, do I miss something, or is it versions problem, or? Thanks for help:)

**Comment by smikheiev** [comment]
@kulabros I suppose this issue can be closed? :)
