### ISSUE TITLE
Possible to create Pixi.spine without atlas?

### ISSUE THREAD

**Issue by birdkingz** [pixijs/pixi-spine#262]
As title, when I export Spine, I didn't select "Create atlas" option because I want Spine to load individual textures instead of atlas.
But I noticed when I load .json it will return an error saying Invalid from TextureAtlas.

Is that possible for me to create Spine object without providing atlas?

**Comment by ivanpopelyshev** [comment]
https://github.com/pixijs/pixi-spine/blob/master/examples/dynamic_texture_atlas.md

**Comment by ivanpopelyshev** [comment]
even more, its possible to stitch whatever textures you want in runtime with pixi-super-atlas which is part of https://github.com/gameofbombs/pixi-heaven

**Comment by birdkingz** [comment]
Hmm, it's pretty close to what I'm looking for but I was thinking is that possible to just pass in an empty atlas.
Once the spine is created then I'll set each texture manually via `hackTextureBySlotName`?

**Comment by ivanpopelyshev** [comment]
no problem, just make an object with names of textures and values of `PIXI.Texture.EMPTY`

**Comment by ivanpopelyshev** [comment]
There are many ways to do that, you should look through all examples and maybe the source code of loader.

**Comment by birdkingz** [comment]
Got it!
Thanks :D

**Comment by birdkingz** [comment]
Hmm, sorry to reopen this issue because I'm facing a weird issue here.
If I created the empty atlas like this
```
const waterAtlas = new PIXI.spine.core.TextureAtlas();
    const waterImages = {
        'body_water_03': PIXI.Texture.EMPTY,
        'claw_water_03': PIXI.Texture.EMPTY,
        'legs_water_03': PIXI.Texture.EMPTY
    }
    waterAtlas.addTextureHash(waterImages, true);

PIXI.loader
    .add('water_body_3, 'body_water_03.png')
    .add('water_claw_3', 'claw_water_03.png')
    .add('water_legs_3', 'legs_water_03.png')
    .add('water, 'skeleton.json', { metadata: { spineAtlas: waterAtlas }})
    .load(onAssetsLoaded);
```
In `onAssetsLoaded()`

```
this.crab = new PIXI.spine.Spine(spriteManager.getSpineData('water_crab'));
this.crab.scale.set(0.1, 0.1);
this.crab.position.set(this.app.renderer.width * 0.5, this.app.renderer.height * 0.5);
this.crab.skeleton.setSkinByName('water');
this.app.stage.addChild(this.crab);

this.crab.hackTextureBySlotName('claw_water_03', spriteManager.getTexture('water_claw_3'));
this.crab.hackTextureBySlotName('claw_water_3', spriteManager.getTexture('water_claw_3'));
this.crab.hackTextureBySlotName('legs_water_03', spriteManager.getTexture('water_legs_3'));
this.crab.hackTextureBySlotName('legs_water_3', spriteManager.getTexture('water_legs_3'));
this.crab.hackTextureBySlotName('body_water_03', spriteManager.getTexture('water_body_3'));
```

I don't see any thing appear in the canvas.

**Comment by ivanpopelyshev** [comment]
I have no idea. You have to debug it, what exactly is stored in `water_claw_3` when its passed to hackTexture, maybe width/height are not set because texture wasnt loaded yet, that can affect things. I didnt think about whether texture is loaded when i made `hackTextureBySlotName`, it does not track it.

**Comment by ivanpopelyshev** [comment]
Then it should work. 
I dont nknow how your SpriteManager works.

**Comment by birdkingz** [comment]
After some investigation, the issue will only happen on newly created Spine.
`this.crab = new PIXI.spine.Spine(PIXI.loader.resources['water_crab'].spineData);`

Because during new spine creation
`slot.currentSprite` is `null` 

which make it falls to `else` statement in the following codes in `hackTextureBySlotIndex`

```
if (slot.currentSprite && slot.currentSprite.region != region) {
                this.setSpriteRegion(attachment, slot.currentSprite, region);
                slot.currentSprite.region = region;
            }
            else if (slot.currentMesh && slot.currentMesh.region != region) {
                this.setMeshRegion(attachment, slot.currentMesh, region);
            }
            else {
                slot.tempRegion = region;
                slot.tempAttachment = attachment;
            }
```

Somehow after the first render/update,
then `slot.currentSprite` is no longer `null`. So calling `hackTextureBySlotIndex` again will no longer fall into `else` statement.

Any idea how can I bypass this problem?
Sorry if the explanation is confusing.

**Comment by ivanpopelyshev** [comment]
call `spine.update(0)`

**Comment by birdkingz** [comment]
Awesome! Finally got it works!
Thank you so much!
