### ISSUE TITLE
Is trimming from the bottom rather than the top intentional

### ISSUE THREAD

**Issue by adam-regan** [pixijs/pixi-spine#267]
TextureAtlas.ts, Line 188
``` javascript
let trim = new PIXI.Rectangle(offsetX, originalHeight - height - offsetY, width, height);
```
I have an issue where the calculation ```originalHeight - height - offsetY``` is offsetting the whitespace  from the bottom of the texture rather than the top as expected. Shouldn't this value just be using ```offsetY```?

**Comment by ivanpopelyshev** [comment]
That's how spine atlas files are parsed.

**Comment by adam-regan** [comment]
Ok that makes sense, we're using a custom exporter to create our atlas files. Our offset in the atlas file already did the conversion to make it pixi friendly  which is why we're seeing the inverse. That makes sense, thank you.

**Comment by ivanpopelyshev** [comment]
Put your stuff in TextureAtlas according to https://github.com/pixijs/pixi-spine/blob/master/examples/dynamic_texture_atlas.md  and https://github.com/pixijs/pixi-spine/blob/master/src/core/TextureAtlas.ts#L43

Use `addTexture` and `addTextureHash` to add pixi textures in spine atlas.

**Comment by ivanpopelyshev** [comment]
You can also make your own loader based on https://github.com/pixijs/pixi-spine/blob/master/src/loaders.ts , which treats atlas differently
