### ISSUE TITLE
UglifyJS error

### ISSUE THREAD

**Issue by goldenratio** [pixijs/pixi-spine#279]
UglifyJs throws error, below is the error message.

> In strict mode code, functions can only be declared at top level or immediately within another function.

https://github.com/pixijs/pixi-spine/blob/ae7bf4a521947d2d87d47e9d7d36216407a4fa29/src/loaders.ts#L106

Some details regarding build tool,
Typescript + webpack + uglifyjs-webpack-plugin

**Comment by goldenratio** [comment]
changing to function expression, fixes UglifyJs error.
```
const done = () => {
  callback(cachedResource.texture.baseTexture)
}
```

Can I make a PR?

@ivanpopelyshev  @cursedcoder

**Comment by IngenuityGaming** [comment]
Hi @ivanpopelyshev , any update on this issue?
We face this while compiling

**Comment by ivanpopelyshev** [comment]
Make a PR , I am not nitpicking on those things, I accept users suggestions :)

**Comment by abhishekrathore03** [comment]
@ivanpopelyshev PR created

**Comment by ivanpopelyshev** [comment]
OK, so, you want me to rebuild everything and publish in npm?

**Comment by abhishekrathore03** [comment]
Yes, please if possible

**Comment by ivanpopelyshev** [comment]
Done, 2.1.9
