### ISSUE TITLE
Root Bone rotation flipped in 1.5.20

### ISSUE THREAD

**Issue by rich-earth** [pixijs/pixi-spine#290]
Hi,  

Setting rotation on a root bone, is behaving differently on latest version 1.5.20 

Eg.  Set the rotation of a root Bone of a skeleton 30 deg ( in spine IDE, rotates whole skeleton anticlockwise 30)

1.5.19 is correct:  
https://www.pixiplayground.com/#/edit/KMb5DIicjvjvGbcgcfSOb

1.5.20 ( 30 becomes -30, rotating clockwise instead )
https://www.pixiplayground.com/#/edit/32hwIwe42aY3RujwFX~af

**Comment by ivanpopelyshev** [comment]
i've adapted many changes from 3,7 spine-ts, and he removed flipX flipY , however I still use it because pixi had different coordinate system. Guess I have to fix that thing.

**Comment by ivanpopelyshev** [comment]
Oh, never mind, found it :)

**Comment by ivanpopelyshev** [comment]
Here we go, 1.5.21: https://www.pixiplayground.com/#/edit/gCqb5MgPl6nM7Nth_unwm

Thank you for noticing that!

**Comment by ivanpopelyshev** [comment]
I dont remember if you have invite to pixijs slack. Give me your email in case you need it :)

**Comment by ivanpopelyshev** [comment]
ping @rich-earth

**Comment by rich-earth** [comment]
Thanks,  there were some other issues with flipping scales on bones with "noScale" as well, latest made it worse.. 
'disable inherit scale'  fix from Spine-ts seems to be a problem.  I'll submit a PR...

**Comment by rich-earth** [comment]
Example of the the flipping problem -  I don't think there is anything wrong with the data but could be wrong. PR submitted gets it back to normal.. 

Correct in 1.5.19
https://www.pixiplayground.com/#/edit/WYYcneu_xio7gmprip1dl

1.5.20 Feet/head/legs flipping x scale and root rotation wrong in 
https://www.pixiplayground.com/#/edit/bhnLpIsV9SX9Sr7MGpyt2

1.5.21 flipping x+y
https://www.pixiplayground.com/#/edit/_4MPHGG7Lt_f4syrjZzqf

**Comment by ivanpopelyshev** [comment]
Well, shit, it was a real bug in spine-ts: https://github.com/EsotericSoftware/spine-runtimes/issues/1379

Your `rotation = -rotation` fix was kinda wrong.
