### ISSUE TITLE
Mesh issues in 2.0.0-alpha + pixi v5 rc3

### ISSUE THREAD

**Issue by roninsi** [pixijs/pixi-spine#293]
Hi,

Using Pixi v5 rc3 with pixi-spine 2.0.0-alpha works well for spines without meshes and it breaks on spines that include meshes (http://esotericsoftware.com/spine-examples-raptor).

If I understand correctly whole mesh rendering was reworked for v5 and pixi-spine doesn't reflect those changes.

We are moving to pixi from another engine that didn't support meshes and are tying to evaluate everything new that could benefit us and designers when creating new stuff. Is updating pixi-spine anywhere on roadmap in the next 6 months?

 Thank you!

**Comment by ivanpopelyshev** [comment]
As soon as we release v5 this or next week. 

pixi-spine has almost everything that original spine runtime has, especially spine-ts.

Problems:
1. sounds, we have no sounds.
2. double-tint (dark-light) , need to update pixi-heaven plugin as well

**Comment by ivanpopelyshev** [comment]
Actually you can use spine from `master` branch instead, I saw several projects that use it with with v5.rc2 meshes. 

`2.0.0-alpha` is older test for PixiJS `5.0.0-alpha3`.

**Comment by ivanpopelyshev** [comment]
However there might be problem with loader, that's what that alpha branch fixed. Unfortunately I cant help you right now because I'm getting dogpiled by v5 issues.

**Comment by roninsi** [comment]
Thanks for quick replay!

We are in no rush, so as along there is a plan to also update pixi-spine, we are happy to wait.

Tried your suggestion and used spine  master + rc3 and there are some issues:
- DRAW_MODES.TRIANGLES moved
- missing tintRgb on slot in update function

Fixing/commenting out parts that were throwing errors I was able to atleast render boy+harnes without raptor mesh.

**Comment by ivanpopelyshev** [comment]
Thank you for the input!

**Comment by roninsi** [comment]
Using 2.0.1 build the raptor spine loads and animates correctly with exception of raptor body, which doesn't seem to be rendered at all. 
![raptor_2 0 1](https://user-images.githubusercontent.com/21121476/58005055-103c5680-7ae5-11e9-92b7-ee9385c7f5e4.jpg)

**Comment by roninsi** [comment]
Everything seems to be working with 2.0.2 build
