### ISSUE TITLE
ClippingAttachment Spine not updated with version 5 of pixi

### ISSUE THREAD

**Issue by bjindal4** [pixijs/pixi-spine#295]
The following line
 var vertices = slot.currentGraphics.graphicsData[0].shape.points;

gives an error where graphicsData (Spine.prototype.updateGraphics) is undefined with pixi version 5. Please update the line as:

var vertices = slot.currentGraphics.geometry.graphicsData[0].shape.points;

**Comment by ivanpopelyshev** [comment]
oops, sorry!

**Comment by ivanpopelyshev** [comment]
OK, please try new build in `bin` folder of this repo. Also please test it on animated masks, because `dirty` and `clearDirty` also had wrong parent.

**Comment by bjindal4** [comment]
Thank you. I will test it and let you know.

**Comment by bjindal4** [comment]
```
 geom.currentGraphics.dirty++;
          geom.currentGraphics.clearDirty++;
```

the currentGraphics are defined in slot and not the geometry. Please check this once again. this thing was fine earlier.

**Comment by ivanpopelyshev** [comment]
ok, please try again and test it :) I'm ready to publish it as new version of spine for v5 when you confirm the fix

**Comment by bjindal4** [comment]
thanks again!  :) this is working fine.
