### ISSUE TITLE
PixiJSv5 Mesh issue

### ISSUE THREAD

**Issue by org07c00h** [pixijs/pixi-spine#299]
Hi, i have a strange bug with PixiJSv5 and pixi-spine plugin from master branch.
The animation works fine with PixiJSv4 and pixi-spine v1.5.21.

here are examples:
http://org07c00h.github.io/pixi-spine-bug/pixi5.html
http://org07c00h.github.io/pixi-spine-bug/pixi4.html

**Comment by ivanpopelyshev** [comment]
something is wrong with UV's, texture-related stuff. Thank you for the demo, im gonna fix it asap.

**Comment by majinge78467** [comment]
@org07c00h 
I met the same problem,Thank you !! I change my spine.js to 1.52.21

**Comment by ivanpopelyshev** [comment]
Fixed. please try 2.0.1

**Comment by org07c00h** [comment]
@ivanpopelyshev 
I tried 2.0.1 and now there is nothing on the screen. also there is a bunch of webgl warnings
`[.WebGL-000001A148E8DC60]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 0`
http://org07c00h.github.io/pixi-spine-bug/pixi5_2.0.1.html

**Comment by ivanpopelyshev** [comment]
it looks like i put the wrong build. I had your example working on my computer..

**Comment by ivanpopelyshev** [comment]
I've tested only batched meshes, I made a mistake :)

OK, fixed, `2.0.2` .

**Comment by org07c00h** [comment]
It works now. Thank you.

**Comment by ivanpopelyshev** [comment]
I'm happy that we have users who can help with QA :)
