### ISSUE TITLE
Using colour correction on ios9 causes assets to appear/disappear at random.

### ISSUE THREAD

**Issue by jsysnowy** [pixijs/pixi-spine#302]
Hey,

When using spines which have color correction/transparency applied to them, the assets just appear/disappear in and out of existence randomly.

Only seems to devices running on ios9.   

https://gyazo.com/3b01ec52c10e63360408f06ead6462a4
https://gyazo.com/d8b01649b86c9722c6a20924066c3b4d

First gif shows the blending colour (bottom right) which seems to cause the issue.
Second gif shows issue on ios 9 device.

Any ideas why this might be, or a way i can disable spines using this on ios9 would be great thanks.

**Comment by ivanpopelyshev** [comment]
Yo! There's light/dark tint. Dark tint is not supported on pixijsv5, and v4 needs extra plugin pixi-heaven. That plugin wasnt updated to v5 yet.

As for why its disappearing - I can make a guess but it depends on the pixi version that you use. Please give me more details.

**Comment by jsysnowy** [comment]
Hey thanks for the reply.

I'm using pixi v4.8.8 and pixi-spine v1.5.22.  I think these are latest releases of both.

For this animation we need the tint to go yellow, and other times all we are doing is changing the transparency of images and it's causing it.

Only fix we have had so far is completely removing any usage of the color correction from our spine files and using different colored assets for now but, which does fix the problem of assets disappearing but it isn't ideal.

**Comment by ivanpopelyshev** [comment]
OK, just to check something : can you try 4.8.7 too ?

Also, maybe that will help : https://github.com/gameofbombs/pixi-heaven/#how-to-use-with-spine , add `pixi-heaven` as dependency and use `PIXI.heaven.spine.Spine` . Its shader and batcher are different. 

One extra hack with heaven that might help in case you are using meshes:

```
PIXI.heaven.settings.SPINE_MESH_PLUGIN = 'spriteHeaven';
``` 

Try those actions separately please.

**Comment by jsysnowy** [comment]
Hey thanks again,

I'm not in the office until tomorrow morning now sorry. Will try all your suggestions and get back to you soon as i can try these.

Appreciate the time in advanced.

**Comment by ivanpopelyshev** [comment]
Its not the first time we solve issues like that. Some shaders and blendmodes affected by old versions of iOS strangely.

**Comment by ivanpopelyshev** [comment]
Please give me minimal skeleton to look, i want to see which animation timelines do you actually use.

**Comment by jsysnowy** [comment]
Hey again,

Whats the best way i can send you this? Do you have a discord or something that will make chatting easier perhaps? Will make one that causes the issue and send one over.

Still testing other PIXI versions etc but no luck yet, seems to always happen as far as i can tell.
Give me 30 mins or so for this though sorry; been a busy day so far 😓 .

**Comment by ivanpopelyshev** [comment]
ivan.popelyshev@gmail.com , yeah i can meet you in html5 gamedev discord: https://discord.gg/bnckxk

**Comment by jsysnowy** [comment]
I'm adding some debugging into pixi-spine itself, so far i've discovered when the issue occurs, the slot.color properties in the update function inside `Spine.ts` are set to NaN when the assets disappear.  Going to try find out why this is next...

**Comment by jsysnowy** [comment]
Looking more, seems `alpha` and `blend` are undefined when it happens in function apply in `Animation.ts`, which cause these to be NaN.. still looking deeper

**Comment by jsysnowy** [comment]
Ok this is weird now - if i put a log in AnimationState.ts, line 162

```
if (i == 0 && (mix == 1 || blend == MixBlend.add)) {
    for (let ii = 0; ii < timelineCount; ii++) {
        if (mix !== 1 || blend !== 1) {
            console.log( mix, blend);
        }
        timelines[ii].apply(skeleton, animationLast, animationTime, events, mix, blend, MixDirection.in);
    }
}
```

then the bug completely goes away ...  spooky.  Not changing or touching anything else.. was just trying to log out what the values are.   No idea why... 👻

**Comment by ivanpopelyshev** [comment]
Please report that issue to @badlogic and check if main runtime https://github.com/EsotericSoftware/spine-runtimes/tree/3.7/spine-ts does have that bug too! 

looks like webkit bug again. @badlogic knows about them.

**Comment by jsysnowy** [comment]
Okay - i'll try chase this up.. not the first time i've seen bugs just disappear when you log them out, but i think those were all on ie11.  Thanks :)

**Comment by ivanpopelyshev** [comment]
https://github.com/pixijs/pixi-spine/blob/master/src/core/Utils.ts#L263

try swap consolelog to `utils.webkit602BugfixHelper(mix, blend)`

**Comment by jsysnowy** [comment]
Hey @ivanpopelyshev , just tested with this you've sent and it does fix the issue :) 

Should i open a PR with this included?

**Comment by ivanpopelyshev** [comment]
Here we go: https://github.com/EsotericSoftware/spine-runtimes/issues/1401
