### ISSUE TITLE
Play multiple animations together

### ISSUE THREAD

**Issue by jiroler** [pixijs/pixi-spine#303]
Hello
I am from #178 
I trying run two animations together like
```javascript
var otto = new PIXI.spine.Spine(res.otto.spineData);
otto.state.setAnimation(0, 'speak', true);
otto.state.setAnimation(1, 'moveHair', true);
```
but playing only second animation.
Maybe the problem is version compatibility?

I using:
pixi v4.8.7
pixi-spine v3.7
Spine 3.7.94

**Comment by ivanpopelyshev** [comment]
It should work. More details please

**Comment by jiroler** [comment]
I made a test repository with a demo page, please see here https://github.com/jiroler/jiroler.github.io.

**Comment by jiroler** [comment]
@ivanpopelyshev Added separate animations and made global variables for convenience https://jiroler.github.io/

**Comment by jmlee2k** [comment]
It's possible that both the win and winEffect animations have keys which cancel each other out, for example, there may be keys in winEffect which detach the bird images, and vice-versa.  Do the animations play together properly when adding them as separate tracks in the Spine preview panel?

**Comment by ivanpopelyshev** [comment]
Oh right i forgot about several issues including this one. @jmlee2k thank you!!!

**Comment by jiroler** [comment]
Thanks for the answer, I will ask the animators
