### ISSUE TITLE
Two color tinting, `darkColor` supported?

### ISSUE THREAD

**Issue by doup** [pixijs/pixi-spine#306]
Hi, I'm trying to two color tint a slot once the animation is running and it looks like it's not working. This is what I'm doing:

```typescript
setColor(color: string) {
    this.animation.skeleton.findSlot('body').color.setFromString(color);
    this.animation.skeleton.findSlot('body').darkColor = new PIXI.spine.core.Color(0, 1, 0);
}
```

The texture I'm using is B/W with gradients. The main color is set correctly but the dark one is not working. I expected to see the black parts replaced by green.

Packages:
- `"pixi-spine": "^2.0.3"`
- `"pixi.js": "^5.1.0"`

Any tip is appreciated,
Thank you!

**Comment by ivanpopelyshev** [comment]
v5? not yet. for v4 it was supported in pixi-heaven. 

With 5.1 release it'll be easy to port that ColorTransform thingy this week.

**Comment by ivanpopelyshev** [comment]
I'm stumbling across problems, but im working. Do you need two-tint with mesh or only with sprites?

**Comment by ivanpopelyshev** [comment]
Almost there

**Comment by ivanpopelyshev** [comment]
Yo! Please try new version of pixi-heaven, https://github.com/gameofbombs/pixi-heaven

**Comment by doup** [comment]
It works perfectly. At the beginning I didn't notice I needed to use `Spine` from the `heaven` namespace, but once I had it right it works fine.

Here an example, notice that the characters outline it's not black but it's a darker version of the skin color:
![xedap-two-tint](https://user-images.githubusercontent.com/188612/62026900-9c9d8080-b1dc-11e9-90b0-b8d31573b5cd.jpg)
