### ISSUE TITLE
Animated clipping masks don't work in Pixi5

### ISSUE THREAD

**Issue by jmlee2k** [pixijs/pixi-spine#307]
Clipping masks will remain as they were during the setup pose, and any animations applied to them (either translations or vertex deformations) won't apply.

I've made a test case for this [here](https://github.com/jmlee2k/pixi5-spine-mask-anim-test), including a very ugly hack which "fixes" the problem, but not in any way that should be used in production :).  

There are 3 pages which demonstrate the issue (see the readme in the repo for links):
- Pixi4 - everything works fine
- Pixi5 - masks are not updated during animations
- Pixi5 + spine hack - everything works as expected

You can play 2 animations with the buttons below the canvas, one plays an animation where the mask's parent bone moves, and the other plays an animation where the individual verts of the mask are animated.  In both animations, the circle at the bottom just moves to show that it is actually playing.

I've tested it with Pixi 5.0.0 as well as the latest version (5.1.0), and both have the same issue.

Spine.updateGraphics correctly computes the vertices, and the shape within the object is updated, but it looks like the graphics object itself never gets updated, so the new verts are never sent to the GPU.

As you can see, my [hack](https://github.com/jmlee2k/pixi5-spine-mask-anim-test/blob/70e63d5e143d165793ed91fba880dd78e99457bc/thirdparty/v5/pixi-spine-hack.js#L7240-L7247) clears the graphics and draws a new polygon each time it updates.  It's ugly and non-performant, but it does show that the only issue is that the graphics aren't being updated.

@ivanpopelyshev, hopefully you can figure out what's going on here.  I spent awhile looking at it myself, but it's way over my head.

**Comment by ivanpopelyshev** [comment]
I totally forgot about graphics polygon modifying!!!! We just need a few lines from `graphics.geometry.clear()` method and it'll be ok :)

**Comment by ivanpopelyshev** [comment]
I appreciate spent time, but in this particular case you could just say "graphics updates are broken". I know we cant always rely on telepathy, just notify me before next time, ok? Maybe I'll deduce the problem from just a few words.

Btw, the same was said to me by one of chromium webgl maintainers :)

**Comment by jmlee2k** [comment]
Sure, I had to make the test case anyways to make sure it wasn't anything else we were doing that broke it.

Do you think this is a quick fix?  We're trying to update to pixi5, and this is one of the last issues we have.

**Comment by ivanpopelyshev** [comment]
Yes, its a quick fix, just give me to rest this hour :) I'm very tired after gym.

**Comment by jmlee2k** [comment]
Of course, take your time, and thanks in advance!

**Comment by ivanpopelyshev** [comment]
im looking at it

**Comment by ivanpopelyshev** [comment]
i published 2.0.4  in npm and uploaded the result in this repo too. 

Your report was very detailed and I figured out whats wrong, and it actually tied to http://www.html5gamedevs.com/topic/9374-change-the-style-of-line-that-is-already-drawn/

**Comment by jmlee2k** [comment]
Thanks for the quick response and fix, I'll try it out first thing tomorrow!

**Comment by ivanpopelyshev** [comment]
I'll make PR to PixiJS tomorrow, I want to add https://github.com/pixijs/pixi-spine/issues/307 in it. Just in case someone changes graphicsData directly.

**Comment by jmlee2k** [comment]
Sorry for the delay, the fix works great, thanks for the quick response!
