### ISSUE TITLE
Error with import

### ISSUE THREAD

**Issue by Gaboa** [pixijs/pixi-spine#308]
I've tried PIXIv5 and had an error when tried to import pixi-spine

```js
import * as PIXI from 'pixi.js'
import 'pixi-spine'
```
Error message:
Uncaught ReferenceError: PIXI is not defined

Also I saw this error in your Travis CI log.

**Comment by diegoclerici** [comment]
Hi @Gaboa. Maybe related to: #297 !??

**Comment by ivanpopelyshev** [comment]
```
import * as PIXI from 'pixi.js'
global.PIXI = PIXI; //or window.PIXI = PIXI;
require('pixi-spine');
```

**Comment by Gaboa** [comment]
@ivanpopelyshev thank you. Your solution works well for me!

**Comment by mercem** [comment]
I confirm that `require` fix the problem. Thank you!
