### ISSUE TITLE
an example of using a pixi mask with spine?

### ISSUE THREAD

**Issue by mreinstein** [pixijs/pixi-spine#31]
I'm trying to place a mask on a spine object, but I'm a bit confused due to the anchoring of spine objects being treated a bit differently. Can anyone shed some light on this?

**Comment by ivanpopelyshev** [comment]
Spine objects are anchored by point (0,0) in spine editor :)

**Comment by mreinstein** [comment]
@ivanpopelyshev it seems that spine objects are anchored to bottom center (0.5, 1) not 0,0 as far as I can tell.

**Comment by ivanpopelyshev** [comment]
@mreinstein Spine editor has its own coordinate system. (0,0) in that system is an anchor.

**Comment by mreinstein** [comment]
but what do I do at runtime, in my game? How do I set up a mask that partially obscures my spine animation? do I attach the mask to the spine object directly?

**Comment by ivanpopelyshev** [comment]
As far as I know Spine object is simple Container. Attach mask directly.

**Comment by cursedcoder** [comment]
`spine.mask = graphics || sprite` should be fine
