### ISSUE TITLE
Deprecation Warning "Use region.texture from now on"

### ISSUE THREAD

**Issue by codingchili** [pixijs/pixi-spine#311]
Hello,

Using pixi v5 with latest build on master branch 2522be1.

I see the following error in the console after loading my spine models.

```
VM8999:6367 Deprecation Warning: @Hackerham: I guess, if you are using PIXI-SPINE ATLAS region.offsetY, you want a texture, right? Use region.texture from now on.
get @ VM8999:6367
RegionAttachment.updateOffset @ VM8999:7903
SkeletonJson.readAttachment @ VM8999:5498
SkeletonJson.readSkeletonData @ VM8999:5432
_parseSpineData @ VM9008:136
_loadSpriteFrom @ VM9008:109
(anonymous) @ VM9008:75
(anonymous) @ VM9007:75
value @ VM8997:8
e._onComplete @ VM8997:8
(anonymous) @ VM8997:8
s @ VM8997:8
AtlasParser.use @ VM8999:8640
...
```

I have a single model and this message is logged 600 times, probably affecting startup performance?

**Comment by ivanpopelyshev** [comment]
Thanks, I'll look soon

**Comment by ivanpopelyshev** [comment]
OK, please test 2.1.2 or the file in "bin/" folder of this repo.

**Comment by codingchili** [comment]
Thanks! Got the version from NPM and I no longer see the warning.

The compiled scripts in /bin isn't updated on the master branch.
