### ISSUE TITLE
Changing skins only works the first time

### ISSUE THREAD

**Issue by damy90** [pixijs/pixi-spine#318]
Hi,
For some reason spines often become misaligned when you change the skin.
I tried the recommendations from an old issue and short of initializing a new spine nothing worked:
https://github.com/pixijs/pixi-spine/issues/96
I tried the same thing in the webgl runtime and it works.
I'm attaching my test with the webgl runtime and pixi side by side. Both are set to change the skin after 2 seconds. App specific code is in demo-pixi.js and demo-webgl.js.
[pixi-spine-bug-report.zip](https://github.com/pixijs/pixi-spine/files/3810247/pixi-spine-bug-report.zip)

**Comment by ivanpopelyshev** [comment]
> I tried the same thing in the webgl runtime and it works.

That kind of reports are the best. You are candidate for prestige award  "bring joy to Ivan's github life" of this week.

I'll look at it soon-ish.

**Comment by ivanpopelyshev** [comment]
Yes, I see the misalign, need to debug it. Just simple sweep around the code didnt help.

**Comment by eXponenta** [comment]
Hi, @damy90, can you attach original spine project?

**Comment by ivanpopelyshev** [comment]
We have an idea that it might be one of new features that we forgot about, so we need to look it in editor :)

**Comment by damy90** [comment]
[prize_count_up_01.zip](https://github.com/pixijs/pixi-spine/files/3820066/prize_count_up_01.zip)

**Comment by ivanpopelyshev** [comment]
@damy90 yep, a bug. https://github.com/pixijs/pixi-spine/pull/319 - you can take it from "fix" branch of this repo, @eXponenta included a build.

I'll review it in sunday.

**Comment by damy90** [comment]
Great! Thanks for responding so quickly.

**Comment by ivanpopelyshev** [comment]
published in 2.1.4

**Comment by ivanpopelyshev** [comment]
Re-opening because people might need that

**Comment by probityrules** [comment]
I'm running into this issue with mesh attachments: the first `setSkin` works correctly for all attachments, but subsequent calls only work for those attachments that aren't meshes. All mesh attachments show up distorted (unless the skin is set back to the original in which case it's fine again):
![skins](https://user-images.githubusercontent.com/1324745/72771455-f355a700-3bce-11ea-92a2-12e5f2cf3717.gif)
Any guidance would be helpful; thanks!

**Comment by ivanpopelyshev** [comment]
Hi! I believe it was fixed , which version of pixijs and pixi-spine do you use?

**Comment by ivanpopelyshev** [comment]
It should work. This case is difficult, so I ask you to find a minimal example for me. Maybe it was here in issues already and bug just appeared again. Maybe you have to take some spine resources and make "https://codesandbox.io/" demo out of it. Maybe just "zip" file.

**Comment by probityrules** [comment]
Sure, I've pulled out the relevant pieces and put them here: https://codesandbox.io/s/quizzical-gates-xr648

You can see it in action here: https://xr648.csb.app/

I have it going through 6 skins, swapping out every 5 seconds.

In this example, I dropped the atlas, skeleton JSON, and the image (as a data uri) into the code (because I was running into CORS issues on codesandbox) but those sources are also included in the assets folder if needed for perusal.

**Comment by ivanpopelyshev** [comment]
OK, i see it, i hope to fix it this week

**Comment by damy90** [comment]
Hi, I see a similar issue with the latest pixi and pixi spine versions for another spine. My old example still works as expected on the new version. In the new animation this time the text shadows are not reset properly. I'm attaching a new side by side comparison.
[pixi-spine-bug-report 5.2.2020).zip](https://github.com/pixijs/pixi-spine/files/4158232/pixi-spine-bug-report.5.2.2020.zip)

**Comment by ivanpopelyshev** [comment]
@damy90 yeah, we still need to fix it and I hope this weekend then :) Thank you for extra report!

**Comment by maximgavrilov** [comment]
Why not just remove `else` in this line?

https://github.com/pixijs/pixi-spine/blob/cebc9f0b755e64a0c1fb602749adb08e52efde39/src/Spine.ts#L308

**Comment by damy90** [comment]
@maximgavrilov this didn't solve the problem for me. The text shadow from my last demo still looks odd
![image](https://user-images.githubusercontent.com/5158658/88668287-19fb1a00-d0eb-11ea-81da-257232a6d9e2.png)
@ivanpopelyshev Is this going to be fixed soon? Or should I just create new spine objects instead of changing skins when that happens

**Comment by ivanpopelyshev** [comment]
Hello! thanks for reminding. I will try to fix it this weekend :)

**Comment by tbrebant** [comment]
> Hello! thanks for reminding. I will try to fix it this weekend :)

We are having the same issue. Thanks a lot!

**Comment by damy90** [comment]
I tried destroying the spines and initializing new ones instead of changing the skin but there are often console errors when you destroy a spine. I guess if you don't do too many instances and don't clean up it could be safe.

**Comment by aapavlov1994** [comment]
I'm using
pixi-spine@2.1.11
spine-editor v 3.8.99
pixi@5.3.8
Bug still appears in all cases where you try to change mesh attachment.
