### ISSUE TITLE
Is it possible to Hot Swap spine texture/atlas?

### ISSUE THREAD

**Issue by st3v0** [pixijs/pixi-spine#320]
Hi,

We're attempting to build a progressive loading system where the app first loads a low-quality small texture and then loads a high-quality one after. At the moment we can do this easily with pixi textures by simply updating the texture to point at a different baseTexture and then disposing of the old base texture.

Spine is a bit of a different beast though as there could be animations playing when we want to do the switch, and the switch should be seamless and not impact the active animations, skins, etc... All the user should see is the textures get crispier. 

Obviously the atlas is tightly coupled to the texture/s. Is it possible to have an active spine animation playing, load a separate higher quality texture/atlas and then switch them out. Without effecting the active spine animations?

I was thinking maybe generate a new SkeletonData and then somehow update the existing Spine instance with it, maybe...

Any help would be greatly appreciated.

**Comment by st3v0** [comment]
I've created an [example](https://codesandbox.io/s/pixi-spine-test-pub-k98r0?fontsize=14&hidenavigation=1&theme=dark) using spineboy of what i'm trying to achieve.

There are 2 spine version of him, spineboy1 which is the normal one and spineboy2 where his colors are inverted and the texture is at 50% scale.  Both the spinedata is loaded and when you click him it should switch his textures only not affecting the active animations.

Right now the example swaps his skeleton which half kinda works, but it's probably not the best approach.

**Comment by st3v0** [comment]
Never mind I found the wonderful `hackTextureBySlotName()` which seems to do exactly what i need

**Comment by ivanpopelyshev** [comment]
Yep, it was made by several users as a hack that doesnt exist in official spine runtime , but people really need it :)

**Comment by st3v0** [comment]
Hmm So I found a problem with this. It doesn't work if the spine has skins. I set the skin in my new skeleton to match the old skeleton but the slots attachments don't update correctly and are missing specific attachments which are part of the skin.

**Comment by st3v0** [comment]
Okay so, looks like I need to do the following to get the slot.attachments to update correctly when skins are involved:

```javascript
newSkeleton.setSkinByName(oldSkeleton.skin.name);
newSkeleton.updateWorldTransform();
```
