### ISSUE TITLE
setAnimation does not work correctly when Spine visibility is changed

### ISSUE THREAD

**Issue by themoonrat** [pixijs/pixi-spine#322]
Start at the official Spine example: https://pixijs.io/examples/#/plugin-spine/spineboy.js
And change the code to
```
const app = new PIXI.Application();
document.body.appendChild( app.view );

// load spine data
app.loader
	.add( 'spineboy', 'examples/assets/pixi-spine/spineboy.json' )
	.load( onAssetsLoaded );

app.stage.interactive = true;

function onAssetsLoaded( loader, res ) {
	// create a spine boy
	const spineBoy = new PIXI.spine.Spine( res.spineboy.spineData );

	// set the position
	spineBoy.x = app.screen.width / 2;
	spineBoy.y = app.screen.height;

	// play animation
	app.stage.addChild( spineBoy );

	app.stage.on( 'pointerdown', () => {
		if ( spineBoy.visible ) {
			spineBoy.visible = false;
			setTimeout( () => {
				spineBoy.visible = true;
              			spineBoy.state.setAnimation( 0, 'jump', false );
			}, 500 );
		}
	} );
}
```

What _should_ happen is that the Spine is set invisible for half a second; then after that half a second is finished, it shows the Spine, and then it jumps.

What you see is that he goes invisible for half a second; then after it re-appears, it's already half way through the jump animation.

I believe this will be because of time deltas not updating whilst the spine is not visible (updateTransform is not called) and it tries to 'catch up' when it's shown, and goes through 500ms worth of updates, which now includes they jump animation. By the time the frame is rendered, he's now mid jump.

**Comment by ivanpopelyshev** [comment]
Yes, its a known issue, the problem is that DELTA becomes VERY big, because updateTransform() is not called. I know how to fix that, possibly :)

Workaround: 
```js
spine.visible = true;
spine.lastTime = 0;
```

**Comment by themoonrat** [comment]
@ivanpopelyshev How about if I submitted a PR that added a getter / setter for visibility, that automatically set lastTime to 0 when visibility is set to true? Can you think of any negative side effects for this?

**Comment by themoonrat** [comment]
Ok, just realised the stupidity of my suggestion, you obviously can't have a setter / getter the same name as the property

**Comment by ivanpopelyshev** [comment]
> automatically set lastTime to 0 when visibility is set to true?

I thought about it week ago - actually you can, just add extra property `_visible` there. I think that'll be acceptable. However if user just stops his render loop or removes PARENT of spine - that'll be a big problem =)
