### ISSUE TITLE
Issue with easings not working when extreme ease is used.

### ISSUE THREAD

**Issue by jsysnowy** [pixijs/pixi-spine#327]
I'm running into a weird issue when using extreme values in the graph editor in my spine animations.  The easing sometimes seems to not be being used, and instead it's just defaulting to use a linear easing instead.  Seems if i reduce the strength of the easing, the issue resolves - and also it only seems to be on certain animations which is causing it, but when the issue does happen it's reproducible 100% of the time. 

Below I'm showing a few images of the easing being used, the expected result and actual result in a test scenario.  

Ease applied in spine:
![EasingIssue](https://user-images.githubusercontent.com/28527653/70244126-babb5480-176b-11ea-9516-87991cdb3200.PNG)
Gif: https://gyazo.com/3b482e3c49a44255f75606cb3c21d050

Expected output as seen through spine app: 
Gif: **https://gyazo.com/010754e8cdf2dd2c0d2d4968b793a55b**

Actual output as seen through PIXI:
Gif: https://gyazo.com/f208ce5899f1c27cda1f2722e2c2f512

I've been poking around in the pixi-spine to try and see if i can find out where the issue is, but no luck yet.  I'll keep taking a look for now, but if anyone has any ideas where this issue might be coming from then that'd be real useful :) Thanks

**Comment by djmisterjon** [comment]
what is your code, did you have any mix duration ?

**Comment by jsysnowy** [comment]
Hey - in PIXI we are just loading in, creating, and playing an animation, We haven't changed the default mix or played any previous animations on it.  The animation is looping and always having the same effect.

**Comment by jsysnowy** [comment]
I've done some investigating, i think this is actually something to do with the way the json is formed in spine itself. 

When you have the graph editor handles dragged extremely steep, it seems the exported json just isn't including the curve at all, therefore it's thinking it should be Linear in pixi-spine.  I don't think the bug is in pixi-spine itself.

I logged out the root json which pixi-spine is using, and you can see here the values for curve are set to 0 when using the extreme easing curves, as well as no normalCurves property existing:

With extreme easing:
![curvesare0](https://user-images.githubusercontent.com/28527653/70252417-50a9ac00-1779-11ea-9b90-b9c78a06211d.jpg)

Without extreme easing:
![curvesarecorrect](https://user-images.githubusercontent.com/28527653/70252437-57d0ba00-1779-11ea-8315-0d701dc513bb.jpg)

**Comment by ivanpopelyshev** [comment]
Usually for that kind of bugs its better to test on https://github.com/EsotericSoftware/spine-runtimes/tree/3.8/spine-ts , and report it there.

**Comment by jsysnowy** [comment]
Cool yeah - will do.  Thanks; i put it on here before properly investigating it, though it's apparent now that it's not the fault of pixi-spine.  will close this and raise over there :)

**Comment by ivanpopelyshev** [comment]
Its fine to ask before you investigated it, because I have mighty telepatic ability that produces easy answers in most cases. In your case, it didnt work :(

**Comment by macguffin** [comment]
Hi Ivan - did a bit of digging with Snowy and this is what we discovered.
You have this function readCurve which determines if you need to build a bezierCurve or not.

> SkeletonJson.prototype.readCurve = function (map, timeline, frameIndex) {
>     if (!map.curve)
>                     return;
>                 if (map.curve === "stepped")
>                     timeline.setStepped(frameIndex);
>                 else {
>                     var curve = map.curve;
>                     timeline.setCurve(frameIndex, curve, this.getValue(map, "c2", 0), this.getValue(map, "c3", 1), this.getValue(map, "c4", 1));
>                 }
>             };


when one of these extreme curves is exported map.curve ===0 so `  if (!map.curve)` is just returning.
It might be that `  if (map.curve === undefined)` would be better as when a curve is LINEAR is is not exported.

Thanks

**Comment by ivanpopelyshev** [comment]
Hm, it was changed: https://github.com/EsotericSoftware/spine-runtimes/blob/3.8/spine-ts/core/src/SkeletonJson.ts#L787

Here: https://github.com/EsotericSoftware/spine-runtimes/issues/1537

Issue was fixed month ago. 

It looks like you were right, its a bug, its just i didnt take updates from spine-ts for a month.

**Comment by ivanpopelyshev** [comment]
It doesn't mean you've lost the time due to me being lazy, you have to know the instrument and be able to debug it anyway :)

**Comment by ivanpopelyshev** [comment]
Oh, wow, I mistaken, i didnt update it for 3 month!

**Comment by macguffin** [comment]
The amount of time you save us all with this project is immeasurable - happy to be able to help.

Thanks as always
:)

**Comment by ivanpopelyshev** [comment]
@macguffin i dont remember, do you need it for pixi-v4 or v5? Because I'm patching v5 right now, gonna publish 2.1.7 in a minute

**Comment by macguffin** [comment]
I am on 5 now @jsysnowy are you guys on 5 yet?

**Comment by jsysnowy** [comment]
Yeah we're on v5 - i think we've only seen the issue on v5.

**Comment by ivanpopelyshev** [comment]
OK, 2.1.7 published, I applied changes from upstream, there were also some Animation/AnimationState changes, not only SkeletonJSON curve stuff

**Comment by jsysnowy** [comment]
Thanks a lot @ivanpopelyshev and @macguffin for helping debug that :) 

And yeah what @macguffin said, thanks for your continued service with helping the PIXI community - it's awesome what you do
