### ISSUE TITLE
Possible rendering issue?

### ISSUE THREAD

**Issue by Senglean** [pixijs/pixi-spine#328]
Adding spine objects to a Pixi Container results in a lot of noise in the chrome fps counter while rendering the spine objects to a render texture removes the noise + significant fps gain. 

Is this a known thing?

<img width="384" alt="Screenshot 2019-12-11 at 4 19 08 PM" src="https://user-images.githubusercontent.com/47624883/71556216-caaa1980-2a35-11ea-8a5f-78980d13a722.png">

left pixi container / right render texture

**Comment by ivanpopelyshev** [comment]
Yep, `spine.update()` is kinda heavy. How many elements did you spawn, 100?

**Comment by Senglean** [comment]
40 objects

> Yep, `spine.update()` is kinda heavy. How many elements did you spawn, 100?

40 objects

**Comment by eXponenta** [comment]
How many slots and bones your spines has?

**Comment by Senglean** [comment]
@eXponenta simple spine objects no rigging

**Comment by ivanpopelyshev** [comment]
Can you record 10 seconds on a profiler? I'd like to know if its GPU-bound or CPU-bound

**Comment by Senglean** [comment]
[Profile-20200102T112439.json.zip](https://github.com/pixijs/pixi-spine/files/4015551/Profile-20200102T112439.json.zip)

sorry for the delay here is a 10sec profiler

**Comment by ivanpopelyshev** [comment]
Ok, I see `6.7s idle` , its good. Most of the time it calculates mesh vertices position - I'm sorry, nothing that can be done about that, unless I finally stop being lazy and apply that old GPU-patch branch that moves that to the shader. Its not easy, that thing is 5-year old, it worked only for some spine models and had limitations. Only a few customized spine runtimes have that.

If your FPS is hurting even at 67% idle, that may mean that bottleneck is fillrate - number of pixels drawn - that one is easy to fix. Just don't draw big models.

**Comment by Senglean** [comment]
Thank you for reviewing!

**Comment by ivanpopelyshev** [comment]
Actually, you can try to use simple rects instead of meshes in places that don't need to be morphed.

**Comment by Senglean** [comment]
i will forward to our designers

**Comment by ivanpopelyshev** [comment]
Oh, right, and you have mask there. If you switch 40 times to stencil and back - its fine, just extra drawcalls. 100 models with masks may be a problem on mobile device.
