### ISSUE TITLE
spine 3.6 + pixi 5 which version of pixi-spine should be used

### ISSUE THREAD

**Issue by zifenggao** [pixijs/pixi-spine#330]
Use  pixi-spine 3.8 version , report such an error `PixiJS Spine plugin supports only format for Spine 3.8. Your model has version 3.6.53. Please look in pixi-spine repository README for another branch.`

Use pixi-spine 3.7 version , report such an error `mesh.uvBuffer.update is not a function`.

Use pixi-spine 3.6 , report such an error `pixi-spine-3-6.js:7008 Uncaught TypeError: Cannot read property 'TRIANGLES' of undefined at Spine.createMesh (pixi-spine-3-6.js:7008)`

**Comment by ivanpopelyshev** [comment]
https://github.com/pixijs/pixi-spine/tree/pixi5-spine3.7 should work. 

Its the one in https://pixijs.io/examples/#/plugin-spine/dragon.js , works even with `spine-3.3` models.

`mesh.uvBuffer.update` - first time I see that. More details please? PixiJS version?

**Comment by zifenggao** [comment]
I use Pixi v5.0.0，plugin-spine uses this https://github.com/pixijs/examples/blob/gh-pages/pixi-plugins/pixi-spine.js . Spine animated version is 3.6.53.  The error like that.

![](http://qiniu.xiaozi1931.com/qiniu_picGo/20200109113933.png)

![](http://qiniu.xiaozi1931.com/qiniu_picGo/20200109114037.png)

**Comment by zifenggao** [comment]
Solved, I replaced PIXI 5.0 with PIXI 5.2！
