### ISSUE TITLE
Constraint problems

### ISSUE THREAD

**Issue by petterhyden** [pixijs/pixi-spine#34]
Having strange behaviour when using Constraints. Especially with chained/interconnected constraints.
The sprites get rotated and are not inline with the original animation.
Tried to have all constraints on the root node and it is working better, but there are still issues with positioning and rotation.

I've tried the same animation with Esoterics Spine JS runtime and everything is working with it.

Setup a test project available at http://bugs.kodbyran.se/pixi-spine-20150519

The spine source files is available on 
http://bugs.kodbyran.se/pixi-spine-20150519/spine-animation_20150519_01.zip

I'm using the latest pixi and pixi-spine (master branches)

![screen shot 2015-05-19 at 11 20 36](https://cloud.githubusercontent.com/assets/1153342/7699573/229faa2c-fe19-11e4-9d6e-ecde8d395cd7.png)

**Comment by petterhyden** [comment]
Added an example of the same animation running with the Spine JS runtime from Esoteric:
http://bugs.kodbyran.se/pixi-spine-20150519/spine-runtime.html

**Comment by Shadowstep33** [comment]
We were having a problem with this as well. It seemed when double bone constraints where used, it fixed the problem. Take a look at the Spine example of spine boy riding a raptor. Hopefully this helps

**Comment by petterhyden** [comment]
Been away on holiday. Have a bit to catch up on, so I will try the double bone constraints fix later this week. Still consider this to be a bug that need fixing!

**Comment by ivanpopelyshev** [comment]
Ok. I'll do as always: look at java runtime :+1:

**Comment by petterhyden** [comment]
:+1:

**Comment by petterhyden** [comment]
Tried everything from double bone constraints, removing some constraints but not getting it to work consistently. Some times images are turned what ever I do (most of the time).
Created another even simpler example without animation and still getting the problem.
One image, one bone and one constraint.
![screen shot 2015-06-01 at 10 11 44](https://cloud.githubusercontent.com/assets/1153342/7908605/b91e17c2-0846-11e5-9558-8cac44f7fb64.png)
![screen shot 2015-06-01 at 10 03 33](https://cloud.githubusercontent.com/assets/1153342/7908606/bd364ba4-0846-11e5-892d-c14bce57cdab.png)

Available at: http://bugs.kodbyran.se/pixi-spine-20150601/
http://bugs.kodbyran.se/pixi-spine-20150601/spine-animation_20150601_01.zip

**Comment by ivanpopelyshev** [comment]
I'm trying to solve it

**Comment by ivanpopelyshev** [comment]
Ok, now Im sure that issue is in skins

**Comment by ivanpopelyshev** [comment]
Nope, still cant find it. Can you show me how it supposed to look like?

**Comment by petterhyden** [comment]
Great that you are on it!
If you look at the images above the rendered image gets rotated -90 degrees when I add a constraint to it. You can grab the zip file which contains the spine source.

**Comment by ivanpopelyshev** [comment]
I have the source, but I didnt install spine editor

**Comment by ivanpopelyshev** [comment]
Ok, found it. look at the build: https://dl.dropboxusercontent.com/u/46636530/pixi-spine/pixi-spine.js

**Comment by petterhyden** [comment]
It's not much in the source. I created the simplest example possible with just 3 bones, 1 image and 1 constraint.

**Comment by ivanpopelyshev** [comment]
That build works with raptor. Is that correct?

**Comment by petterhyden** [comment]
Yes, the raptor works. I'm unable to understand what I've done differently.
I tried applying just one constraint to a bone in the spine boy example and it fails to. The image gets rotated.

**Comment by ivanpopelyshev** [comment]
Yep, its IkConstraint bug. Wait for commit and new build :)

**Comment by ivanpopelyshev** [comment]
Fixed in #e162b09ab2

**Comment by petterhyden** [comment]
:+1:
