### ISSUE TITLE
chang skeleton setAttachment attachmentName type

### ISSUE THREAD

**Issue by Magikarp-2020** [pixijs/pixi-spine#342]
https://github.com/pixijs/pixi-spine/blob/fdcaab3f3002e0258571929a6be60db84bbb0b19/src/core/Skeleton.ts#L446-L463

I see that there is a judgment on the `null` parameter in this method. Can I add a `null` statement?

```
 setAttachment (slotName: string, attachmentName: string | null) { 
```

OR

```
 setAttachment (slotName: string, attachmentName?: string) { 
```

**Comment by ivanpopelyshev** [comment]
Yep

**Comment by ivanpopelyshev** [comment]
Second :)

**Comment by Magikarp-2020** [comment]
https://github.com/pixijs/pixi-spine/pull/344

this is my pr

**Comment by ivanpopelyshev** [comment]
ok then, I uploaded new version to npm yesterday but i dont feel like I want to update it once more because of extra `?` , lets wait for something serious

**Comment by Magikarp-2020** [comment]
ok~
