### ISSUE TITLE
Attachment returns to setup pose state after each animation

### ISSUE THREAD

**Issue by krtr** [pixijs/pixi-spine#346]
According to:
http://en.esotericsoftware.com/forum/slots-do-not-go-away-when-starting-a-new-animation-1040

I need to explicitly call `skeleton.setToSetupPose()` but it appears that the attachment is being reset to its setup pose state by itself

Scenario:
3 Animations : `FadeIn`, `Thunder`, `FadeOut`

`FadeIn`: attaches attachment and fades it in
`Thunder`: animations that does not touch faded in attachment
`FadeOut`: fades out and detaches attachment

What happens is faded in attachment disappears right after `FadeIn` ends

Expected behaviour: Attachment remain in state that they were left with previous animation until `skeleton.setToSetupPose` (or equivalent)  is called

## Video: 
https://streamable.com/7gsn99

You can see that fully dark clouds disappears after `FadeIn` animation 

## Repo with spine project:
https://github.com/krtr/pixi-spine-bug/

spine project in: https://github.com/krtr/pixi-spine-bug/tree/master/data

**Comment by krtr** [comment]
Dope sheets from each animations:
![image](https://user-images.githubusercontent.com/8374421/88552981-084f3f00-d025-11ea-9d29-c23511a1008e.png)
![image](https://user-images.githubusercontent.com/8374421/88553007-143b0100-d025-11ea-89de-dedf49a506c5.png)
![image](https://user-images.githubusercontent.com/8374421/88553038-1e5cff80-d025-11ea-91e3-75df45122944.png)

**Comment by ivanpopelyshev** [comment]
Hi!

to speed up the process, you can do the following: confirm that it works differently in spine-ts. https://github.com/EsotericSoftware/spine-runtimes/tree/3.8/spine-ts

then it means its pixi-spine bug and not the spine editor stuff that was changed somewhere between 7 years ago (your forum link) and today.

**Comment by krtr** [comment]
Spine-ts has identical behavior as pixi-spine
https://streamable.com/x173f1

Ok I'm closing issue here then

**Comment by ivanpopelyshev** [comment]
Then you can pester in that repo about correct behaviour, maybe its actually bug, there were cases like that ;)
