### ISSUE TITLE
FFD Keyframe issue?

### ISSUE THREAD

**Issue by Shadowstep33** [pixijs/pixi-spine#35]
This is more or less a question wrapped in a possible bug report. Whenever I have vertices keyed in on the dopesheet in spine, as in only a handful of vertices, the animation won't play in pixi. More specifically, the layers with the mesh that has animated vertices do not appear. This also breaks all other spine animations that have a mesh in them (by making those layers disappear); similar to the bug I reported here https://github.com/pixijs/pixi-spine/issues/10 but without the WebGL warning. I just generally want to know if anyone has experienced the same thing and whether the issue is more likely error rooted in Spine, Pixi, or the application I am developing.

I am using pixi 3.0.6 and the latest pixi-spine

**Comment by simonTadram** [comment]
I fixed couple issue regarding ffd animation in pixi-spine where meshhas partial vertices keyed. It was not working at all previously, but now for all the scenes I got it work fine.
Make sure you have my latest fix that has been merged 2 days ago. If you still have the bug  and if it is a possibility for you you could share a simple scene that demonstrate the problem.

**Comment by Shadowstep33** [comment]
I believe I have the most recent build, I downloaded it from the master branch recently. I will see what I can do about getting you an example.

**Comment by Shadowstep33** [comment]
The problem occurs whenever there are keyed meshes.
NOT when you key a bone that deforms a mesh, that still works. 
It's only when you key a meshed attachment that the rendering problem occurs.
Here is a screenshot of what I mean by "keying a meshed attachment":

http://imgur.com/q3kp3LX

and here is an example page demonstrating the problem. https://monsterisland.chimeracompanygames.com/secure/landing/raptor2

When you remove those keys from the dopesheet all-together like this: 
http://imgur.com/uDZXLJj

then it works just fine. Here's an example of it working without the keyed mesh attachments (but still with bones deforming meshes)

https://monsterisland.chimeracompanygames.com/secure/landing/raptor1

each example was exported using "non-essential data" and "pretty print" so that you can more easily look though the json and import it into spine if needed (you'll have to supply the images, but those are in the spine examples directory)

**Comment by simonTadram** [comment]
@Shadowstep33  I fix the problem in this pull request https://github.com/pixijs/pixi-spine/pull/36
you need to build locally to test it or just do the modification locally in your built file to test (1 line modified)

Let me know if you still experience problem

**Comment by ivanpopelyshev** [comment]
@simonTadram 
Merged. I'll change some minor things and rebuild it.

**Comment by ivanpopelyshev** [comment]
@simonTadram Ok, done.

**Comment by Shadowstep33** [comment]
Okay, so some problem is definitely fixed now, but there still seems to be a(nother) problem afoot.

https://monsterisland.chimeracompanygames.com/secure/landing/raptor2

The legs dont flash anymore but the body never shows. When I try to add a Spine obj with a similar problem into my application, it causes other Spine objects to break. The problem seems to be some sort of interruption and/or interaction between Spine objects and/or Spine layers. 

If you notice on raptor2, the top of his leg connection compresses a bit - this is not supposed to happen as there is a FFD of some of the meshe's vertices that is not visually animating.

**Comment by simonTadram** [comment]
fixed in https://github.com/pixijs/pixi-spine/pull/40

**Comment by ivanpopelyshev** [comment]
@simonTadram I dont know how did we not see this before :+1:

**Comment by Shadowstep33** [comment]
Not sure if the newest change got built, but I edited the file according to #40 and everything looks good on raptor2! Thanks.

**Comment by ivanpopelyshev** [comment]
Ok, build is done

**Comment by Shadowstep33** [comment]
Im unsure if this is related or unrelated, so I'll ask about it here and open a new ticket if need be:

Seems like the final weird behavior is some vertices moving unexpectedly when other vertices are keyed. https://monsterisland.chimeracompanygames.com/secure/landing/raptor2

On raptor 2, some vertices on the jaw are keyed. You can observe the weird behavior by looking at the raptors knees and arms

**Comment by simonTadram** [comment]
humm, I didnt got that bug when I tested it. Ill check sometime this
weekend maybe

**Comment by Shadowstep33** [comment]
Ok thanks! I'll check back later

**Comment by simonTadram** [comment]
Ok it is fixed in https://github.com/pixijs/pixi-spine/pull/42
I checked with original implemenation in libgdx and now it should behave the same way.

Let me know if you have other trouble

**Comment by ivanpopelyshev** [comment]
@simonTadram done.

**Comment by Shadowstep33** [comment]
raptor2 is now working exactly as anticipated :)

**Comment by Shadowstep33** [comment]
Well, aside from the other two tickets I raised ;)

#38 & #39

**Comment by Shadowstep33** [comment]
Actually, I may have been a bit pre-emptive. Though the unintended knee deformation isn't happening anymore, the intended jaw deformation isn't helping either

**Comment by simonTadram** [comment]
Could you be more specific, I looked quickly at the original .spine file
demo and they look pretty much the same

may be send me a couple grabbed frame & highlight the difference or
something.

Thanks

**Comment by Shadowstep33** [comment]
yes, here is an example of what should be happening

http://monsterisland.chimeracompanygames.com/secure/spine/creatures/plant/2_uncommon/raptor_2/raptor2.gif

**Comment by SharpleafCC** [comment]
the example we (me and @Shadowstep33 ) have on the links he proved are modified examples of the original spine demos. Referencing the demo that comes with spine wont work in these cases. 
We have modified the raptor to exaggerate the problem that we are having with other animations we are making for our project.
The Raptor_2 that @Shadowstep33 has been linking to has been altered from its original demo to have the lower jaw stick out very far and then retract. The gif he just posted is the expected outcome. While ugly and impractical, it was made to exaggerate the problem of keyed meshes not deforming.

**Comment by ivanpopelyshev** [comment]
@simonTadram Ok, its my turn to check whats wrong. Lets see if I can see the problem faster than you :)

**Comment by SharpleafCC** [comment]
competition! I like it! :+1:

**Comment by ivanpopelyshev** [comment]
@SharpleafCC where's code/resources of your version of demo?

**Comment by SharpleafCC** [comment]
@ivanpopelyshev 
@Shadowstep33 is in the process of uploading it and will link to it shortly

**Comment by ivanpopelyshev** [comment]
Ok, I pull-request #42 is bullshit, it does not fix anything

**Comment by simonTadram** [comment]
@ivanpopelyshev  I agree

**Comment by Shadowstep33** [comment]
@simonTadram @ivanpopelyshev let me know if this works for y'all. Sorry it took so long, I'm not used to Git :S

**Comment by ivanpopelyshev** [comment]
@Shadowstep33 then you could use dropbox :)

Can you just share this small project through dropbox please? That way we wont copy files There and back again.

**Comment by ivanpopelyshev** [comment]
I see possible problems and I'm checking other runtimes.

**Comment by Shadowstep33** [comment]
https://www.dropbox.com/sh/hqrjc9yo0td1kcm/AADrFxETtzmRqFUCjqP3ybUna?dl=0

it's currently uploading

**Comment by ivanpopelyshev** [comment]
@Shadowstep33 
I believe I changed the code that way it corresponds to official libgdx runtime. Please checkout latest pixi-spine.js.

**Comment by ivanpopelyshev** [comment]
@Shadowstep33 I dont see demo code there

**Comment by Shadowstep33** [comment]
Ok, seems to be working now (for real)! Sorry I'm so illiterate when it comes to sharing code X_x

**Comment by ivanpopelyshev** [comment]
@Shadowstep33 Share minimal demo through dropbox is the fastest and easiest way to fix that stuff. Then we can git it.

Ok, nice!

**Comment by SharpleafCC** [comment]
@ivanpopelyshev and @simonTadram, thank you for your help resolving this issue!
