### ISSUE TITLE
spine.hackTextureBySlotName('arm', myTexture, { width: 100, height : 100 }); There is no effective. 

### ISSUE THREAD

**Issue by W-went** [pixijs/pixi-spine#359]
//Region attachments are tricky: they must have width and height, specify it if your texture differs from old one
spine.hackTextureBySlotName('arm', myTexture, { width: 100, height : 100 });
Invalid size setting
There is no effective.

 PixiJS 5.1.3 
 pixi-spine  master

**Comment by W-went** [comment]
> //Region attachments are tricky: they must have width and height, specify it if your texture differs from old one
> spine.hackTextureBySlotName('arm', myTexture, { width: 100, height : 100 });
> Invalid size setting
> There is no effective.
> 
> PixiJS 5.1.3
> pixi-spine master

**Comment by ivanpopelyshev** [comment]
Did you try to debug it?

**Comment by W-went** [comment]
> Did you try to debug it?

Texture replacement is fine
Size is no effective

**Comment by ivanpopelyshev** [comment]
I can debug it in weekend if you provide a demo, but i recommend to actually place some breakpoints and try to figure out which variables are wrong , maybe you see it in 30 minutes.

Also, i dont remember how exactly size affects this thing.
