### ISSUE TITLE
how realize physics effect on pixi-spine?

### ISSUE THREAD

**Issue by W-went** [pixijs/pixi-spine#370]
I want to use pixi-spine with physics effect， how should I do? thx :-)

**Comment by ivanpopelyshev** [comment]
Oh, its easy ! 
1. Just take your favorite physics engine (p2, box2d, whatever)
2. learn how to make game engine that uses both pixi and this physics and copies values from one to another , like i do in this absolutely easy demo for novices - https://codesandbox.io/s/unruffled-haze-l4tlj
3. Add spine to the mix, add constraints based on bones, map every spine aspect you want your physics connect to.
4. Voila! Its done!

**Comment by ivanpopelyshev** [comment]
You'll get the same answer for every other spine runtime, whether its unity or construct2 or cocos2d, or something else
