### ISSUE TITLE
i have no idea

### ISSUE THREAD

**Issue by GoshTag** [pixijs/pixi-spine#376]
`
export class Clock {
    constructor(app) {
        this.app = app;

        PIXI.loader
        .add([
            'images/clock.png',
            'images/hour.png',
            'images/min.png',
        ])
        .load(this.setup.bind(this));

        this.clock;
        this.hour;
        this.min; 
        console.log(this.clock);
    }
    
    resize(width, height) {
        this.clock.position.set(width, height);
    }

    setup() {
        this.clock = new PIXI.Sprite(PIXI.loader.resources['images/clock.png'].texture);
        this.hour = new PIXI.Sprite(PIXI.loader.resources['images/hour.png'].texture);
        this.min = new PIXI.Sprite(PIXI.loader.resources['images/min.png'].texture);
        
        this.app.stage.addChild(this.clock);
        this.app.stage.addChild(this.hour);
        this.app.stage.addChild(this.min);
    }
   
}
`

hi, I've been wandering for 2 hours because of this problem.

How can i put variables in the set-up function into the constructor variables?
I want to receive a value and resize it, but the constructor's variable is still 'undefined'.

**Comment by ivanpopelyshev** [comment]
> constructor's variable is still 'undefined'.

its undefined because "setup" is async. it will be called when everything loads.
you can create sprites in constructor, then assign their textures in `setup` :)

**Comment by GoshTag** [comment]
thank you!
