### ISSUE TITLE
Clip attachments and slot colour/alpha

### ISSUE THREAD

**Issue by TheWyo** [pixijs/pixi-spine#382]
Just ran into this issue trying to figure out why a clipped texture attachment wasn't showing up at all.

https://github.com/pixijs/pixi-spine/blob/ea3fbc921b46c25b273a1c83001cbc79265facc6/src/Spine.ts#L413

Alpha is applied to the containers every update, so we had a slot that in Spine's setup view had an alpha of 0 (artist set all slots alpha to zero so stuff isn't rendering before an anim is first started, first frame of the anims turns on whatever it needs). This caused the object to never render. This doesn't show up this way in the editor though, the editor still played the clip mask of the anim as we wanted it.

I'm not sure what the intended behaviour for a clip's colour property is. I'm guessing if the editor was displaying what we expected to see, that at least alpha is ignored on these if not all of the colour property. Might just need a simple check that the attachment isnt instanceof ClippingAttachment?

**Comment by ivanpopelyshev** [comment]
You did something rare, I want demo of it :)

**Comment by TheWyo** [comment]
Here's a zip with a minimal repro spine project & its export. If you load the export into pixi-spine you shouldn't see anything. Now if you take the JSON and remove the `"color":"ffffff00"` from the slots block, you'll see the anim play. In the editor, the image is visible regardless of the fact that the alpha on the clip's slot is 0.

[Bug_ClippingMask.zip](https://github.com/pixijs/pixi-spine/files/6222057/Bug_ClippingMask.zip)

**Comment by ivanpopelyshev** [comment]
Actually, now I have an idea, even without demo:

https://github.com/pixijs/pixi.js/blob/2c9275da55a866de6268ed5ebfefc0c8dd4868a8/packages/core/src/mask/StencilSystem.ts#L63

calls

https://github.com/pixijs/pixi.js/blob/2c9275da55a866de6268ed5ebfefc0c8dd4868a8/packages/display/src/Container.ts#L577-L580

Guess, we have to add something like `alpha=0.00001` for such elements in clip. Do you want to make a PR? 
workaround: just add an `if` somewhere in `Spine.ts`, see if it rowks

**Comment by TheWyo** [comment]
Setting a tiny alpha seems a bit hacky. I tried the idea about wrapping the alpha assignment with an instanceof check so ClippingAttachments are excluded, and that does indeed fix it, so if you're happy with this as a solution then sure, I'll make a PR for it.

```typescript
if (!(attachment instanceof core.ClippingAttachment))
{
    slotContainer.alpha = slot.color.a;
}
```

**Comment by ivanpopelyshev** [comment]
OK, try 2.1.13 , i changed clippingattachment thingy: https://github.com/pixijs/pixi-spine/commit/608cece12562f3ba84c7f43434ed8deecd5b4e2f

**Comment by TheWyo** [comment]
Yep, that new version fixes the issue. Thanks!
