### ISSUE TITLE
IK Constraints

### ISSUE THREAD

**Issue by bengraphite** [pixijs/pixi-spine#44]
Hi,

I'm new to using Spine and PIXI and I was wondering if anyone was experiencing problems with using IK Constraints and capturing the characters bounds in runtime?

If I import the Goblin example the _bounds object and getLocalBounds function seem to have width and height properties but on my character containing IK everything is set to zero.

I am using the latest version which was compiled on June 7th.

Any help or workarounds would be greatly appreciated.

**Comment by ivanpopelyshev** [comment]
Show me the code. I know that getBounds() works and return world coordinates.

**Comment by bengraphite** [comment]
IK Constraint section part of avatar.json
<pre><code>"ik": [
{
    "name": "LEG2",
    "bones": ["BackUpperLeg", "BackLowerLeg"],
    "target": "LEG2"
},
{
   "name": "LEG1",
   "bones": ["FrontUpperLeg", "FrontLowerLeg"],
   "target": "LEG1"
},
{
    "name": "ARM2",
    "bones": ["BackUpperArm", "BackLowerArm"],
    "target": "ARM2",
    "bendPositive": false
},
{
    "name": "ARM1",
    "bones": ["FrontUpperArm", "FrontLowerArm"],
    "target": "ARM1",
    "bendPositive": false
}]</code></pre>

More or less the same as the examples: http://pixijs.github.io/examples/index.html?s=spine&f=dragon.js&title=Dragon&plugins=pixi-spine 

<pre><code>PIXI.loader.add("avatar", "assets/data/avatar/avatar.json")
.load(function(loader, resources)
{
     this.container = new PIXI.Container();
     this.character = new PIXI.spine.Spine(resources.avatar.spineData);

     /* instantiate the spine animation */
     this.character.skeleton.setToSetupPose();
     this.character.update(0);
     this.character.autoUpdate = false;

     /* measure the spine animation and position it inside its container to align it to the origin */
     var localRect = this.character.getLocalBounds();
     this.character.position.set(-localRect.x, -localRect.y);

     /* create a container for the spine animation and add the animation to it */
     this.container.addChild(this.character);
}
</code></pre>

**Comment by ivanpopelyshev** [comment]
Do you use meshes?

**Comment by bengraphite** [comment]
Nope :/

**Comment by ivanpopelyshev** [comment]
I cant reproduce it :( which version of pixi do you use?

**Comment by bengraphite** [comment]
I'm using PIXI 3.0.2

**Comment by ivanpopelyshev** [comment]
Does it work in latest pixi?

**Comment by bengraphite** [comment]
just updated.

curiously a zero timeout got results

<pre><code>var _this = this;
setTimeout(function()
{
     console.log(_this.character.getLocalBounds());
}, 0);</code></pre>

I must have some dodgy code, I'll keep looking. Thanks for all your help!
