### ISSUE TITLE
FlipX, FlipY issues

### ISSUE THREAD

**Issue by darie8208** [pixijs/pixi-spine#45]
Hi, 

There seems to be a problem with flips. 
To reproduce:
-add a Flip_X key frame in an animation in the Spine editor
-export
-use pixi-spine.js to load and display animation

Note that the flip seems to do nothing.

Notes:
We are not using IK. 

Thanks,
Darie

**Comment by ivanpopelyshev** [comment]
Ok, I'll look at it. I saw some issues with flips too.

**Comment by darie8208** [comment]
Thank you ! 

We've been fiddling with these two functions:
-spine.Bone.prototype:  updateWorldTransform 
-Spine.prototype.update

But failed miserably so far :(

**Comment by ivanpopelyshev** [comment]
I know that there's a problem with global flipY called "spine.Bone.yDown" , which this plugin contains. Original spine runtime doesnt have it.

**Comment by darie8208** [comment]
Hi Ivan,

Here are is our animation .spine file, if it helps you: https://www.dropbox.com/sh/8vh0bvwa53v8xl1/AAAmSpCSG7yCPyl4ljoWrJeqa?dl=0
Animation called "t3" is an example that has Flip-x.

Is there anything I could do to assist you? 

How are things going with fixing this issue, do you think it is fixable, or should we try to avoid using flip-X and flip-Y altogether ? 

Darie

**Comment by darie8208** [comment]
Hi Ivan,

Is there a donations page for this project, we would be very happy to contribute if you could get this issue fixed.

Darie

**Comment by ivanpopelyshev** [comment]
Hey, sorry, I was very busy this days. I'll look at it now.

**Comment by ivanpopelyshev** [comment]
Can you export json and atlas files for me?

**Comment by ivanpopelyshev** [comment]
Please check my build, I made some changes without testing it: https://dl.dropboxusercontent.com/u/46636530/pixi-spine/pixi-spine.js

**Comment by darie8208** [comment]
Thank you for your quick reply !

Unfortunately, this seems to have made things worse. A lot of the bones seem flipped vertically now not sure the horizontal flipping works properly.

Here are some exported animations: 
https://www.dropbox.com/sh/9ry4ge31yw57x2c/AAAiLp0qloPxkYB_o5SQlwS1a?dl=0
Animation "t3" with cat is broken.

https://www.dropbox.com/sh/ot6snrb9evmw7pl/AAA0T9r9txdZCKrRT9A0wYE8a?dl=0
Animation "t5" with gorilla is broken.

Hope this helps.

**Comment by ivanpopelyshev** [comment]
Yes, i see that. Working on it.

**Comment by ivanpopelyshev** [comment]
I fixed flipX: https://dl.dropboxusercontent.com/u/46636530/pixi-spine/pixi-spine.js
Can you help me test flipY?

**Comment by darie8208** [comment]
Hi,

Unfortunately, I have the same issues as before ...
Try the gorilla animation "t5"

I will help you with flip_y 
Will provide an export of an animation that has a flip_y in it soon.

**Comment by ivanpopelyshev** [comment]
Ok, i forgot to update the file. Try now :)

**Comment by ivanpopelyshev** [comment]
New version works for me. The only problem with gorillla "t5" is looping, but you can fix it by adding an extra frame in the end of each flip timeline, as far as I know its original behaviour.

**Comment by darie8208** [comment]
Ok, I will try it now.

Here is the cat animation with a flip_y in it. Try animation "t3". The cat should flip_y right before it jumps, then flip y back when it lands.  
https://www.dropbox.com/sh/ltwnb5q4sy3owvw/AABlmK9P8y4U_VgDCH7rlxpna?dl=0

**Comment by ivanpopelyshev** [comment]
Can you make a gif of it for me? so i see what happens in "spine" and compare it to js runtime

**Comment by ivanpopelyshev** [comment]
@darie8208 you didnt change "t3" :(

**Comment by darie8208** [comment]
I think I did.
This is the link
https://www.dropbox.com/sh/ltwnb5q4sy3owvw/AABlmK9P8y4U_VgDCH7rlxpna?dl=0
If you look in the cat.json you should find flipY somewhere

This is the gif:
https://www.dropbox.com/s/wrbwg7u33inoslt/cat.gif?dl=0

**Comment by darie8208** [comment]
To clarify, that gif shows the cat "t3" animation as exported from Spine in gif format. It looks unnatural because I just added two random flip-y keyframes in it, for the purposes of testing flip-y

**Comment by darie8208** [comment]
I have briefly tested it and it seems flip-y works. 
Thank you very much for you help.

**Comment by ivanpopelyshev** [comment]
It works! I think we can close this issue. There're no donations page in this project (yet), but there are donation projects in my gameofbombs.com :)

**Comment by darie8208** [comment]
OK, we will donate tomorrow :)
