### ISSUE TITLE
Playing multiple animations at once?

### ISSUE THREAD

**Issue by Shadowstep33** [pixijs/pixi-spine#46]
Hi y'all,

I was wondering how to play two animations (this is a question, not bug report). Particularly, I want to set multiple animation states and update them separately. So for example:

```

		bunny.update(0);
		bunny.autoUpdate = true;
		
		bunny.state.setAnimationByName(0, 'idle', true);    	
		bunny.state.setAnimationByName(1, 'growth', true); 

```

so here's the specific questions:

1. How do I set track 1 of the animation to autoUpdate = false while tracks 0 is autoUpdate = true? Do I have to set the overall bunny.autoUpdate = false and then just manually update each animation?

2. How do I manually update the position of a single track and not bunny as a whole? Particularly, I'd like to set it to a certain % of the animation state. So I don't necessarily need to set it to specifically 2 seconds, but just to the halfway mark of the animation (whatever it may be).

3. Are there any docs on .update()? What options do I have?

**Comment by ivanpopelyshev** [comment]
Try this:

```javascript
   //create second AnimationState
   var state2 = new PIXI.spine.SpineRuntime.AnimationState(bunny.stateData);
   //add an animation
   state2.setAnimationByName(0, 'growth', true);
   //set to 50%
   state2.tracks[0].time = state2.tracks[0].animation.duration * 0.5);
   //apply directly
   state2.apply(bunny.skeleton);
```

**Comment by Shadowstep33** [comment]
Awesome, thanks @ivanpopelyshev I will try this momentarily. Going to take a little lunch break. With the code you posted, how would the autoUpdate paradigm work for bunny? Is there a way I can tell track 1 not to autoupdate but track 0 to autoupdate? Track 1 I need to manually control but I still want track 0 to do it's thing

**Comment by ivanpopelyshev** [comment]
there wont be track #1, its different animationState, it applies to skeleton ONLY when you call apply(bunny.skeleton). Autoupdate works for the first state as it worked before.

**Comment by ivanpopelyshev** [comment]
PIXI doesnt know about that "state2", you have to update it manually :)

**Comment by ivanpopelyshev** [comment]
@Shadowstep33 hey.

**Comment by ivanpopelyshev** [comment]
hey2

**Comment by ivanpopelyshev** [comment]
ping

**Comment by Shadowstep33** [comment]
Hey @ivanpopelyshev , sorry. I haven't been checking my personal email (which is tied to my github). Will have to change it too my work email; sup?

**Comment by ivanpopelyshev** [comment]
@Shadowstep33 did it work?

**Comment by Shadowstep33** [comment]
Honestly, I have not rlly given it too in depth of a shot yet. I'll give it a shot today; currently we're working on v0.3 and that includes some more functional improvements versus aesthetic and graphical improvements like that. I basically dropped it a bit lower on my priority list while I fix other stuff :P

**Comment by ivanpopelyshev** [comment]
Hey @Shadowstep33 , did you test it? :)

**Comment by Shadowstep33** [comment]
I still never got to this Ivan :( I'm sorry. If you want you can close this ticket and I'll come back here whenever i get to it. We're still focusing on some other crucial things before dealing with this. I appreciate you coming back to check on this though!

**Comment by Shadowstep33** [comment]
btw it worked ;)

**Comment by ivanpopelyshev** [comment]
nice.
