### ISSUE TITLE
where to attach shaders to individual limbs?

### ISSUE THREAD

**Issue by mreinstein** [pixijs/pixi-spine#47]
@ivanpopelyshev I'm messing around with adding dynamic lighting to spine2d for use with pixi. I'm thinking the easiest way to start with this is to attach shaders to individual elements of these spine instances. e.g., if i want to attach a shader to the sprite representing a skeleton's arm, where in the data structure should I do this?

**Comment by ivanpopelyshev** [comment]
```javascript
//there was a bunny
bunny = new Spine()
//index of slot
var slotNumber = bunny.skeleton.findSlotIndex('arm')
//sprite in the slot
var sprite = bunny.slotContainers[slotNumber].currentSprite
//in case you have several sprites there
var sprite2 = bunny.slotContainers[slotNumber].sprites['armsprite']

sprite.shader = myShader
```

I did not test it , I just looked at the code. I'll help if that wont work.

**Comment by mreinstein** [comment]
awesome that's a great start. Thanks! :) I've gone digging for other related info I think I'll need. 

to get at a slot's uv coordinates:
```
currentSlot = a.skeleton.slots[2]
currentSlot.attachment.uvs
```

uv texture coords go from bottom right clockwise to top right.

My current thinking is I'll attach a shader to each .currentSprite entry, and pass in several variables:
* normal map
* uv coordinates of
* world rotation

then the shader will take those, rotate the normal map's coords based on world rotation, and apply the normal lightmap calculation

thoughts/ideas/issues welcome!

**Comment by ivanpopelyshev** [comment]
That thing will be slow unless you add all these sprites into spriteBatch somehow.

**Comment by ivanpopelyshev** [comment]
Can you create minimal project where we can experiment with it?

**Comment by mreinstein** [comment]
> That thing will be slow unless you add all these sprites into spriteBatch somehow.

Maybe you're right about that being too slow. It might be worth trying this out first since it's conceptually simple though, and then modify it to be more performant. But if you have another idea I'm open for suggestions. This just seemed like the easiest path algorithmically speaking.

> Can you create minimal project where we can experiment with it?

Yeah definitely! I'll set one up today and ping here.

**Comment by ivanpopelyshev** [comment]
Good. add me in skype? jedi_knight2008

**Comment by mreinstein** [comment]
repo is here now, still in progress. 

https://github.com/mreinstein/pixi-spine-lighting

It loads and animates a spine object. Working on setting up a fragment shader and an initial light.

**Comment by mreinstein** [comment]
here's the link to the repo as promised:  https://github.com/mreinstein/pixi-spine-lighting

**Comment by mreinstein** [comment]
I've hooked up the torso to pixi's built-in normal map shader. It is not even remotely working properly though lol. I've pinged pixi contributors for documentation feedback here:  https://github.com/GoodBoyDigital/pixi.js/issues/1646

**Comment by ivanpopelyshev** [comment]
@mreinstein allow me to push some commits there

**Comment by mreinstein** [comment]
@ivanpopelyshev done, sorry about that!

**Comment by ivanpopelyshev** [comment]
@mreinstein ok, now we have problems because pixi-spine reverts coordinates and somehow it affects shadows

**Comment by ivanpopelyshev** [comment]
@mreinstein I'm using pixi-lights at the moment

**Comment by mreinstein** [comment]
my original plan was to use NormalMap but @englercj suggests not to because it's broken, and advised to use pixi-lights instead.

**Comment by ivanpopelyshev** [comment]
@mreinstein ping. where are you?

**Comment by ivanpopelyshev** [comment]
@mreinstein I want to talk, can you please open skype? :)

**Comment by ivanpopelyshev** [comment]
@mreinstein Just a reminder that this thing wont work with [gpupatch](http://www.html5gamedevs.com/topic/18480-pixi-spine-plugin-wip-gpu-patch/), unless you ask me to add lights support in that shader :)

**Comment by ivanpopelyshev** [comment]
Ok, SUMMARY: it wont be possible to attach shaders to individual limbs, however it will be possible to attach other pixi displayObjects to those limbs and to change spine shader.
