### ISSUE TITLE
Spine Skeleton Scale.

### ISSUE THREAD

**Issue by englercj** [pixijs/pixi-spine#5]
Tracking GoodBoyDigital/pixi.js#1344

**Comment by cursedcoder** [comment]
seems to be fixed in #59

**Comment by mspanish** [comment]
Can anybody post an example of how to scale your spine animation? I see this has been closed, but there are no clear examples as to how this could be used. Also, what does "atlas only" mean? Don't all of the spine animations load the atlas? Sorry I'm completely new to Spine. The Pixi runtime so far has worked like a dream, using the demo code everything worked right out of the box w/ no glitches.

**Comment by ivanpopelyshev** [comment]
@mspanish 

You are right!

Added it into 1.4.1, published.

https://github.com/pixijs/pixi-spine/blob/master/examples/choose_skeleton_scale.md - here it is
