### ISSUE TITLE
Firefox39 rendering problem

### ISSUE THREAD

**Issue by darie8208** [pixijs/pixi-spine#50]
Hi,
We have experienced an issue with animations in Firefox 39. Please see GIF below:

(https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/27586/678026/kVRMkimxJroFBKN/monkey.gif)

Weird thing is that we tested on different computers with Firefox39 and the issue is shown only on some of the computers. All computers ran Windows7.

I am not sure what to do about it. Any help would be greatly appreciated. 

Thanks,
Darie

**Comment by ivanpopelyshev** [comment]
WOW! Ok, I'll look at that :) Can you please make minimal code that reproduces that (including your pixi.js and pixi-spine versions)? Because I really dont understand how that thing is possible.

**Comment by darie8208** [comment]
Hi, thanks! 

We are using pixi 3.0.5 and your latest pixi-spine.
Problem is that it might not be reproducible on your computer...
Please go to http://test-tl.sumdog.com/city and login with this: TT32485 and password drive74
Click on the monkey and select a trick to play.

I will try to get some minimal code across as soon as possible.

Thanks,
Darie

**Comment by darie8208** [comment]
Oh and you need to use Firefox version 39, as its OK on other browsers.

**Comment by ivanpopelyshev** [comment]
Does it happen with both WebGL and Canvas renderers?

**Comment by darie8208** [comment]
It happens only with WebGL

**Comment by ivanpopelyshev** [comment]
Then we know where to search - something is wrong with vertex buffers.

**Comment by darie8208** [comment]
Here is a simple project:
https://www.dropbox.com/sh/aokdlgwd2ezyb1e/AAAf5YMcb3ZUniUT9XH4Yq4Pa?dl=0

Problem is the problem does not occur when running this simple project in Firefox39.

Maybe it is because too much is happening on the page on our site http://test-tl.sumdog.com/city, or we are doing something wrong with the animation ...

**Comment by darie8208** [comment]
Update:

The problem seems to be related to transparency. 
If I do:
var renderer = PIXI.autoDetectRenderer(800, 600, {transparent: true});
Then I get the horrible visual glitches.

If I take out the {transparent:true} bit:
var renderer = PIXI.autoDetectRenderer(800, 600);
Then everything is fine. 
 
Here is a page that reproduces the issue:
https://s3.amazonaws...ox39/index.html

Alternatively, if you want the project:
https://www.dropbox....T9XH4Yq4Pa?dl=0

It is probably an issue with PIXI, not your project, but I just wanted to let you know about this.

**Comment by ivanpopelyshev** [comment]
links arent working, "..." in some places

**Comment by darie8208** [comment]
https://s3.amazonaws.com/assets-test-dp.sumdog.com/firefox39/index.html

**Comment by ivanpopelyshev** [comment]
Is that still a thing? Btw, can you please try my gpupatch? 

http://www.html5gamedevs.com/topic/18480-pixi-spine-plugin-wip-gpu-patch/

**Comment by darie8208** [comment]
Thanks for the patch.

It was a Firefox 39 specific issue if I recall correctly. Something to do
with transparency.
As a "fix", we forced Canvas use in Firefox 39.

I am very busy at the moment but we will try your gpu patch as soon as
possible.

**Comment by ivanpopelyshev** [comment]
Just add it as separate js file after pixi-spine.js , and look at FPS or profiler

**Comment by cursedcoder** [comment]
@darie8208 if you still experiencing this, feel free to re-open.
