### ISSUE TITLE
Built files don't play well with other libraries when combined into a single js file.

### ISSUE THREAD

**Issue by andrewstart** [pixijs/pixi-spine#52]
When concatenating libraries into a single libraries.js file, pixi-spine.js interferes with the next self-executing function closure, wanting to run require() on the return value of that function. It appears that the problem is that pixi-spine.js lacks a trailing semi-colon, which is present in pixi.js.

**Comment by ivanpopelyshev** [comment]
Its strange, but I cant find why there's no semicolon. Any Ideas?

**Comment by andrewstart** [comment]
I am completely unfamiliar with the gulp build process, so I have no idea.

**Comment by cursedcoder** [comment]
seems we don't have any gulp now, feel free to re-open if you still have this
