### ISSUE TITLE
Draw crashed image when use trim/crop Spine atlas

### ISSUE THREAD

**Issue by SeminYun** [pixijs/pixi-spine#53]
hi

i repost this issue from pixi.js.

https://github.com/pixijs/pixi.js/issues/2061

thx a lot

**Comment by ivanpopelyshev** [comment]
Can you show me your resource files? Better to share a folder in dropbox so we can checkout it together.

**Comment by ivanpopelyshev** [comment]
OK, please try pixi-spine 1.0.5, this one has fixed it: https://github.com/pixijs/pixi-spine/commit/a7a28e080db900ac909891c2266a48c94078f4d1
