### ISSUE TITLE
Destroy method

### ISSUE THREAD

**Issue by daviestar** [pixijs/pixi-spine#55]
I am using the method you [showed me before](https://github.com/pixijs/pixi-spine/issues/54) to initialise my spine instances inline.

Is there a way I can remove the spine instances from the PIXI canvas once they have been created?  I have searched the plugin for 'destroy' and other usual suspects but struggling to find the correct way.

Thanks.

**Comment by ivanpopelyshev** [comment]
You can create multiple instances for one skeleton data. You can remove them just like any other object. 
```javascript
parent.removeChildren(); //removed
parent.children.splice(index, 1); // remove by index
```

Textures that you loaded cant be removed because they are cached in pixi. Skeleton data can be removed like any other javascript object, its not cached.

**Comment by daviestar** [comment]
Thanks again @ivanpopelyshev , I had found that I could put the Spine instances into a PIXI container and destroy that, but the `removeChildren()` function is what I was looking for :)
