### ISSUE TITLE
Getting to original state

### ISSUE THREAD

**Issue by Jonoh89** [pixijs/pixi-spine#56]
Hi, we have switched from Phaser and implemented Spine into our games and we have drastically reduced our asset sizes so thank you very much!

We want to play an animation then reset it back to how it looks when the asset was first loaded, before the animation was played, or the very first spine state of the animation. I can't see any methods for doing this yet.

Is there an any way to do this? We are currently having to destroy and recreate so we can't pool our objects.

**Comment by ivanpopelyshev** [comment]
Hello! I thought there is spine runtime for phaser.

According to [runtimes](http://ru.esotericsoftware.com/spine-using-runtimes) we can call setToSetupPose after animation ends.


```javascript
spine.state.onComplete = function() { spine.setToSetupPose(); }
```

**Comment by Jonoh89** [comment]
Yeah that's done it

Thanks!
