### ISSUE TITLE
is there a way to access an attachment's oriented bounding box in world space?

### ISSUE THREAD

**Issue by mreinstein** [pixijs/pixi-spine#6]
For example, if you are running the goblin spine animation and want to access the spear attachment's bounding box in world coordinates, is there a way to do this?

**Comment by ivanpopelyshev** [comment]
That will help to find slot/sprite by attachment name:

```javascript
function findBone(skel, attach) {
    for (var i = 0; i < skel.slots.length; i++) {
        if (skel.slots[i].sprites.hasOwnProperty(attach))
            return skel.slots[i].sprites[attach];
    }
    return null;
}

var spearSprite = findBone(spine.skeleton, "spear");
```

**Comment by mreinstein** [comment]
assuming the slot is known ahead of time, I think this is easier to get at the sprite:

```javascript
var spearSprite = skel.findSlot('LEFT HAND');
```

but I guess the question is, at that point you need to take into account rotation, anchor, and world transform?

**Comment by ivanpopelyshev** [comment]
This might work:

```javascript
spearSprite.getBounds()
```

**Comment by mreinstein** [comment]
Ah yes that does seem to return the AABB of the sprite! The only issue here is that it's not taking into account orientation. In my use case, I have weapons (guns) and need to figure out the location of the barrel depending on the weapon attached. In this case I'd need rotation. I'm thinking that maybe the gun's bone worldRotation, and some data on attachment offset, + attachment width/height is needed?

btw do you think it would be helpful to add like a "cookbook" section to this repo? Some common operations on spine objects? I'd be happy to submit some initial attempt at this if you think it would be useful.

**Comment by ivanpopelyshev** [comment]
That methods takes into account rotations and orientation. Do you need absolute bounding box or relative?

https://github.com/GoodBoyDigital/pixi.js/blob/ee3/src/core/sprites/Sprite.js#L212

Yes, cookbook will be nice. I'm noob, how do I create it?

**Comment by mreinstein** [comment]
> Yes, cookbook will be nice. I'm noob, how do I create it?

I can submit a really simple one with a few examples. I'll try to send a pull request a little later today.

**Comment by mreinstein** [comment]
> Do you need absolute bounding box or relative?

This is what I need (the green dot):

![desired](https://cloud.githubusercontent.com/assets/718067/7097023/ec7baca8-df86-11e4-8826-98006d1c6a45.png)

The rocket launcher is an attachment on the gun slot. I could find this if I know the rotation of the sprite in world coordinates, + the center point of the sprite, and the width/height of the sprite. Unless there is a better way?

**Comment by ivanpopelyshev** [comment]
Add +1 invisible attachment that appears exactly on that dot?

**Comment by mreinstein** [comment]
hmm...that's a really interesting idea!

**Comment by mreinstein** [comment]
> Add +1 invisible attachment that appears exactly on that dot?

So, definitely an interesting idea but the problem is guns are of various sizes. It's going to depend on the size of the sprite for the particular equipped gun.

**Comment by ivanpopelyshev** [comment]
Then you need to store parameters of each gun (where is that pixel relative to the bone).
Different gun size => different bones?

```javascript
x += sprite.width/2;
```

**Comment by ivanpopelyshev** [comment]
Sorry, I think I pressed the wrong button :)
Do you still have that problem?

**Comment by mreinstein** [comment]
no worries, I think your solution definitely works; I can hardcode the offset of the gun barrel per weapon. It might be more elegant to have the center point, orientation, and attachment dimensions but it's not a huge problem.

**Comment by cursedcoder** [comment]
closing as it seems to be resolved (at least partially)
