### ISSUE TITLE
Pixi.Spine without loader

### ISSUE THREAD

**Issue by sommerper** [pixijs/pixi-spine#62]
Is there a workaround for generating a spine element without having to rely on the loader?
I already have a base64 encoded image and atlas+json data as a string stored in variables and would like to do something like this:
```new PIXI.spine.Spine(base64EncodedImage, atlasAsString, jsonAsString);```

Any help is appreciated!

**Comment by ivanpopelyshev** [comment]
Look at this: https://github.com/pixijs/pixi-spine/issues/54

```!javascript
var rawSkeletonData = JSON.parse("$jsondata"); //your skeleton.json file here
var rawAtlasData = "$atlasdata"; //your atlas file 

var spineAtlas = new spine.Atlas(rawAtlasData, "pathToAtlasImage/"); //specify path, image.png will be added automatically

var spineJsonParser = new PIXI.spine.SkeletonJsonParser(new PIXI.spine.AtlasAttachmentParser(spineAtlas));
var skeletonData = spineJsonParser.readSkeletonData(rawSkeletonData);

//now we can create spine instance
var spine = new PIXI.spine(skeletonData);
```

**Comment by sommerper** [comment]
hi,

yes i already saw that one but it still requires the image to be loaded:

```var spineAtlas = new spine.Atlas(rawAtlasData, "pathToAtlasImage/"); ```

I already have the image loaded in a base64 encoded variable.

**Comment by ivanpopelyshev** [comment]
https://github.com/pixijs/pixi-spine/blob/master/src/spineRuntime/atlas.js uses BaseTexture.fromImage to load images:

```javascript
BaseTexture.fromImage = function (imageUrl, crossorigin, scaleMode)
{
    var baseTexture = utils.BaseTextureCache[imageUrl];

    if (crossorigin === undefined && imageUrl.indexOf('data:') !== 0)
    {
        crossorigin = true;
    }

    if (!baseTexture)
    {
     //use loader
    }
}
```

Put your preloaded texture into utils.BaseTextureCache[imageUrl].

**Comment by sommerper** [comment]
Got it working. Thanks!

**Comment by ivanpopelyshev** [comment]
Awesome!
