### ISSUE TITLE
goto delta time (question not issue)?

### ISSUE THREAD

**Issue by macguffin** [pixijs/pixi-spine#64]
Hi not really an issue just a question. Is there a way to jump to a specific time/delta. I'm looking in the AnimationState.js but can't see what to use.

Thanks

**Comment by ivanpopelyshev** [comment]
Something like that:

```javascript
spine.state.tracks[0].time = ...
spine.state.update(0);
```

**Comment by macguffin** [comment]
Thanks for the pointer. :)

**Comment by macguffin** [comment]
spine.state.tracks[0].time is null in this animation. I've just cloned the repository so I will have a look round.

Do you have any idea what happens if animating on a crappy device, will frames be skipped? 

I basically am using events to drive other bits of code and and wondering if there is a possibility that these events could be missed, or skipped over. 

The gotoAndStop(time or frame)  would be a safety measure to force the animation to the correct frame when it has finished.

Thanks

**Comment by ivanpopelyshev** [comment]
Did you start the animation first? 

```javascript
state.setAnimationByName(0, "animation1", true);
```

**Comment by ivanpopelyshev** [comment]
Events wont be missed, that's for sure.

**Comment by macguffin** [comment]
That's great to know!

**Comment by macguffin** [comment]
I am starting the animation just not looping it

    state.setAnimationByName(0, "animation1", false);

**Comment by ivanpopelyshev** [comment]
When animation is complete, tracks[0] will dissappear. Are you sure that tracks[0] is defined when you do that thing with time?

**Comment by macguffin** [comment]
Ok that will be what it is. 

I think maybe I'm being over cautious. If events will definitely fire and the animation will always show its final frame that should be enough. 

When I used another spine runtime with createjs in the past I had an issue with a frame not being shown correctly when stopping the animation. I would have to manually set the delta time to be sure.   I haven't had anything like that with your stuff.

Thanks for your help and your time.
BTW do you have an official forum for these sorts of questions?

**Comment by ivanpopelyshev** [comment]
Posting the issue here is fastest way of finding solution for your problem :)

Pixijs subforum on html5gamedevs: http://www.html5gamedevs.com/forum/15-pixijs/

**Comment by macguffin** [comment]
Thanks

Last question I promise :)

Can you pause the animation via an event?
Is there something that would do the equivalent of:

    spine.state.pause();

**Comment by ivanpopelyshev** [comment]
```javascript
spine.autoUpdate = false;
```

stops all animations.

**Comment by macguffin** [comment]
Awesome thanks very much that is just what I need.
