### ISSUE TITLE
Incorrect Transparency Amount With Additive Slots

### ISSUE THREAD

**Issue by MattOstgard** [pixijs/pixi-spine#68]
Attached is an image of the issue and a zip with files to reproduce the problem. It appears as if the color tinting is being applied twice to slots with additive blend modes and as a result a faded out slot can appear barely visible, while the same values when viewed in the spine editor it would still be clearly visible. The bottom two gradient bars is how it should look, the top is incorrect.

I created it by making 11 white sprites and tinting the alpha of each at increments of 10 percent and setting the blend mode to additive.

https://dl.dropboxusercontent.com/u/36289/xfer/2015/pixi-spine_additive_transparency_bug.zip
![pixi-spine_additive_bug_sshot](https://cloud.githubusercontent.com/assets/6550818/11759814/162c771c-a039-11e5-8e8e-805cd4217a83.png)

**Comment by ivanpopelyshev** [comment]
Bug shows only in webgl. That's strange.

**Comment by MattOstgard** [comment]
Tried looking through the code, couldn't figure out what was going on, but wrote a script as a workaround for the moment. It multiplies the rgb values by the alpha values and sets the alpha to 1 for any slot that is additively blended. This is a bad work around though, because by doing this when you fade to zero it will actually be fading to black and desaturating any colors while transitioning. For the moment though it's better than any alternative that I could think of.

Just supply the script with your .json spine file and it will spit out another json with a "issue_68_work_around" suffix.  Windows users should be able to drag and drop the json file onto the script. Only tested with python3 and on windows.

Get it here: https://gist.github.com/MattOstgard/245617e60d8079c22bb6

**Comment by ivanpopelyshev** [comment]
So its premultiplied alpha problem, i think.

**Comment by ivanpopelyshev** [comment]
Wait, I see that both spine and pixijs are the same. so its "Pixi js additive" vs "Pixi js normal" problem

**Comment by MattOstgard** [comment]
Ah you are right sorry about that.

**Comment by ivanpopelyshev** [comment]
Yeah, please copy that to https://github.com/pixijs/pixi.js , we'll have a consilium there.

And add yourself to https://gitter.im/pixijs/pixi.js , we need more people :+1:

**Comment by ivanpopelyshev** [comment]
And if you're gonna use a huge number of spine anims in your project, please test https://github.com/pixijs/pixi-spine/blob/gpupatch/gpupatch/SkinnedMeshPatch.js , its patch to next version, I didnt merge it to master branch yet.
