### ISSUE TITLE
Spine "src" Restructuring

### ISSUE THREAD

**Issue by adamdanielsdesign** [pixijs/pixi-spine#7]
**Overview:**

Spine.js & SpineRuntime.js would be broken down into a new "src" folder and their respective dir.
```
src/
  Spine/
  SpineRuntime/
Spine.js
SpineRuntime.js
```
then...
```
Spine/
  root.js
    ^ contains any bootstrapping type code
  Spine.js
    ^ contains the header code and @class/@module statement for documentation
  update.js
    ^ method
  autoUpdateTransform.js
    ^ method
  ...
```

**Summary:**

This would separate out all major methods and properties of both Spine and SpineRuntime making them easier to modify and update. 

**Usage:**

- Rather than one large single file, this would make many smaller files.
- Each file would be either a method or a property

**Implementation:**

- Option 1: Use a grunt tool to concat the files together.
  * This would be easy enough to use and a more basic implementation. Requires the files to be manually ordered in the Gruntfile.
- Option 2: Use a require() type system making each sub file it's own module.
  * Would still require manual ordering in the Gruntfile, however would open up options for including other modules as sub modules of the plugin later on for added functionality.

**Comment by ivanpopelyshev** [comment]
My proposition : two steps / two commits: 
1) 
  a) use grunt
  b) separate SpineRuntime.js

```
src/
  Spine.js
    ^ old spine.js
  Atlas.js
    ^ all regarding atlas
  Skeleton.js
    ^ bones, constraints, skeleton
  Parser.js
    ^ json parser/loader
  Animation.js
    ^ animation, timelines
```

2) Create folder for animations: every Timeline in separate file.

**Comment by englercj** [comment]
> use ~~grunt~~ gulp, and separate SpineRuntime.js

Fixed that for you :)

**Comment by ivanpopelyshev** [comment]
yes, "gulp" is shorter^W better way to concat 6-10 files :)

**Comment by adamdanielsdesign** [comment]
The grouping of the methods makes sense, however it brings up another topic; that SpineRuntime consists of a group of additional modules.

Basically, from there, using the 'Animation' module as an example...

```
src/
  Animation/
    root.js
    Animation.js
    binarySearch.js
    binarySearch2.js
    linearSearch.js
    ...

  also...
  (just a side note)
  c_ << denoting the file as a Class
  m_ << denoting the file as a Method  
  p_ << denoting the file as a Property
  
  Animation/
    root.js
    c_Animation.js
    m_binarySearch.js
    m_binarySearch2.js
    m_linearSearch.js
    ...
```
What my main focus is on eventually, is later being able to add more documentation comments. These generally can take up a few paragrahs easily.

Also, when working on a function, having it totally separated into it's own file, for me anyways, visually it's easier to define it's purpose and more easily trade out the file for a test file without needing to copy/paste( or make additional copies of copies with multiple changes are getting done throughout the document ).

**Comment by ivanpopelyshev** [comment]
Too many files => too many tabs in editor. I can navigate through 200-300 lines of code without problems. Also ctrl+F works better that way. @englercj what do you think about it?

**Comment by adamdanielsdesign** [comment]
Also, this is advanced, actually I did similar to @ivanpopelyshev on my local, I just literally broke it down using the inplace namespacing.

I'll upload the repo in a sec you can look at it.

**Comment by englercj** [comment]
Imho having each function in a separate file is too much, splitting makes sense when the file is too big or the stuff in there are not logically connected. I would start with @ivanpopelyshev's suggestion, then split further if it makes sense as you work.

**Comment by adamdanielsdesign** [comment]
https://github.com/adamdanielsdesign/SpineRuntime

**Comment by adamdanielsdesign** [comment]
Also, I did all this like last week (pretty sure) so it's using an old version. Would need to re-break it down for actual committing.

**Comment by adamdanielsdesign** [comment]
@englercj  @ivanpopelyshev 
If we're all in agreement, I could break it down and set up gulp, then send over a pull?

**Comment by englercj** [comment]
@adamdanielsdesign PRs are never a bad idea, gives a great place to start iterating.

**Comment by adamdanielsdesign** [comment]
Cool

**Comment by adamdanielsdesign** [comment]
@ivanpopelyshev Actually, it might be better if you broke this down, because you might have dev builds that haven't been committed. If I go and break it down it would be double work maybe for you, to have to go and copy/paste all the possible changes you may have going on.

let me know, if it won't be too much of a hastle then I'll go ahead and break it down today, otherwise this may be something to wait till everything is sync'd up.

**Comment by ivanpopelyshev** [comment]
@adamdanielsdesign I have no builds at the moment :) I was very busy with launch of  http://actimel.ru/actikids/game/ (press big button two times). That's where my team is using spine.

**Comment by adamdanielsdesign** [comment]
Works, I'll go ahead then, tx!

**Comment by adamdanielsdesign** [comment]
Ok,
**Details of pull:**
```
Spine.js << left as is, it seems to already be a class type object.
SpineRuntime.js << held a bunch of classes, so broke it down to those classes.
src/
  spine. << used as prefix, not sure if it's needed, however it matches the implementation.
```

**Comment by adamdanielsdesign** [comment]
Merged/Closed: https://github.com/pixijs/pixi-spine/pull/8
