### ISSUE TITLE
Tint property not working

### ISSUE THREAD

**Issue by barbarosso** [pixijs/pixi-spine#71]
Is there a possibility to get the tint property working on spines?
I tried it with the gpu patch, because i saw following post. [http://www.html5gamedevs.com/topic/18480-pixi-spine-plugin-wip-gpu-patch/](url)

> Ok, now that tint and interaction work, you can download and include this file just after pixi-spine and look at differences for your project :)

But no luck so far.

**Comment by ivanpopelyshev** [comment]
Tint works only if you included it in spine animations itself, general tint isnt working yet, and I dont think it works even without this patch.

**Comment by ivanpopelyshev** [comment]
I'll fix it :)

**Comment by barbarosso** [comment]
@ivanpopelyshev That would be highly appreciated, if it's fixable.

**Comment by ivanpopelyshev** [comment]
There's an idea about adding worldTint like worldAlpha in every pixi container. I think its good :)

**Comment by barbarosso** [comment]
Any news on the worldTint feature?

We have a work around, but it's not that clean/performant.
And we are planning to use pixi v4, how will spine integrate into the v4 branch?

Thanks
Pascal

**Comment by ivanpopelyshev** [comment]
I plan it in v4.1 , as one of big breaking changes :)

**Comment by ivanpopelyshev** [comment]
Also, old pixi-spine is working in v4, and latest pixi-spine (for spinev3) working too

**Comment by ivanpopelyshev** [comment]
It is done : https://github.com/pixijs/pixi-spine/commit/8cddf6413867e9bbf192889b3fe928d45ecf7979

**Comment by orrkislev** [comment]
Is it possible to tint a specific slot?
