### ISSUE TITLE
How to initialize pixi-spine without using Loaders?

### ISSUE THREAD

**Issue by damirm** [pixijs/pixi-spine#73]
Hey. I have loaded atlas and skeleton (it loads during game initialization). How to pass it into pixi-spine directly, without passing url and loading via Loaders?

**Comment by ivanpopelyshev** [comment]
Privet!

I'll add it to docs later.

```
var rawSkeletonData = JSON.parse("$jsondata"); //your skeleton.json file here
var rawAtlasData = "$atlasdata"; //your atlas file 

var spineAtlas = new spine.Atlas(rawAtlasData, function(line, callback) {
        //pass the image here.
        callback(PIXI.BaseTexture.fromImage(line));
    }); //specify path, image.png will be added automatically

var spineJsonParser = new PIXI.spine.SkeletonJsonParser(new PIXI.spine.AtlasAttachmentParser(spineAtlas));
var skeletonData = spineJsonParser.readSkeletonData(rawSkeletonData);

//now we can create spine instance
var spine = new PIXI.spine(skeletonData);
```

**Comment by damirm** [comment]
Хм. Cигнатура spine.Atlas вот такая:
`spine.Atlas = function (atlasText, baseUrl, crossOrigin)`

Вторым аргументом не получится передавать функцию. Версия pixi-spine@1.0.7

**Comment by damirm** [comment]
Обновил до 1.0.9 - вижу что сигнатура измнилась. Похоже то что нужно :-) Спасибо!

**Comment by ivanpopelyshev** [comment]
Its 1.0.9:

https://github.com/pixijs/pixi-spine/blob/master/src/SpineRuntime/Atlas.js

I changed the signature, that way it can be sync (fromImage), async (loader.add) and anything you want :)

**Comment by funkypaul** [comment]
Hey, would it be possible to create a skeleton without using spine atlas format? Im using texture packer json hash format for my app, would like to keep the spine images in one common texture file. Would this be possible?

Cheers,
P.

**Comment by ivanpopelyshev** [comment]
@funkypaul The problem is that spine atlasParser uses different classes: AtlasPage and AtlasRegion instead of BaseTexture and Texture. That was made to preserve API of original spine runtime for libgdx.

We can either implement a converter either somehow force spine to use PIXI classes instead of their spine runtime equivalents. Better discuss it in team slack. Whats your email?

**Comment by funkypaul** [comment]
pawel.stanislawczuk@gmail.com

**Comment by ivanpopelyshev** [comment]
@funkypaul invited.
