### ISSUE TITLE
weightedmesh

### ISSUE THREAD

**Issue by scottmcdonnell** [pixijs/pixi-spine#74]
I guess these are not supported? 
We used bones in Spine 3.0.11 to apply a weight mesh warp to a texture. The json exports with a skin:
```
 {
				"type": "weightedmesh",
				"uvs": [ 0, 0, 0.2, 0, 0.4, 0, ... ],
				"triangles": [ 16, 22, 23, 23, 26, 27,...],
				"vertices": [ 1, 1, -0.87, -18.85, ... ],
				"hull": 20
			}
```
in pixi-spine 1.0.9 it throws an error for type "weightedmesh" in `spine.SkeletonJsonParser.readAttachment()`

looking at the src code there is no matching AttachmentType.
```
spine.AttachmentType = {
	    region: 0,
	    boundingbox: 1,
	    mesh: 2,
	    skinnedmesh: 3
};
```

Is there another way of exporting as a skinned mesh?

**Comment by ivanpopelyshev** [comment]
not yet, i'll add it ASAP

**Comment by scottmcdonnell** [comment]
New to pixi-spine so a PR would take me an ice age to complete, sure you would have it done by the time I have it cloned :)

**Comment by rpurushotma** [comment]
I also get the error message:

> Uncaught Unknown attachment type: undefined
>   spine.SkeletonJsonParser.readAttachment	
>   spine.SkeletonJsonParser.readSkeletonData

When I try to import the Spine project at [langwidge.com/timey_anim_basic.zip ](http://www.langwidge.com/timey_anim_basic.zip) with code that works for more simple Spine projects. Is this the same issue?

**Comment by abyrne85** [comment]
+1 Need weighted meshes too

**Comment by scottmcdonnell** [comment]
Perfect! Works great.
