### ISSUE TITLE
Can't change slot color for mesh parts

### ISSUE THREAD

**Issue by beanhedge** [pixijs/pixi-spine#77]
For some reason, I'm unable to change the colors of mesh slots. Non-mesh slots work fine.  In this picture, I've set all slot colors to only green. However, only the non-mesh slots are colored correctly.  The Alpha, on the other hand, works like a charm.

![selection_001](https://cloud.githubusercontent.com/assets/11011326/13565239/badd7c8a-e403-11e5-82af-f37aed0ecc42.png)

My simple example:
https://www.dropbox.com/s/f7odzdvbd6kz8mr/pixi-test.tar.gz?dl=0

It's basically this [example](http://pixijs.github.io/examples/index.html?s=spine&f=dragon.js&title=Dragon&plugins=pixi-spine&v=v3.0.10):, all I did was replace it with the raptor example files, and add:

```
for(var i=0; i<dragon.skeleton.slots.length; i++) {
        dragon.skeleton.slots[i].b = 0;
        dragon.skeleton.slots[i].g = 1;
        dragon.skeleton.slots[i].r = 0;
        dragon.skeleton.slots[i].a = .3;
    }
```

**Comment by ivanpopelyshev** [comment]
Does it work if you include https://github.com/pixijs/pixi-spine/blob/master/gpupatch/SkinnedMeshPatch.js ?

**Comment by beanhedge** [comment]
Hmm how do I use that file? If I just include it on top of everything else, I get `SkinnedMeshPatch.js:655 Uncaught TypeError: Cannot read property 'program' of undefined`

**Comment by ivanpopelyshev** [comment]
That's magic patch that makes all meshes significantly faster for rendering. Its magic patch so in some cases it wont work :(

**Comment by beanhedge** [comment]
What cases does it not work in? Can the official non-gpu plugin fix this problem?

**Comment by beanhedge** [comment]
Also, do you know where the code that sets color = slot color * attachment color is located?  I can't seem to find it in pixi-spine or gpupatch

**Comment by ivanpopelyshev** [comment]
Yeah, we need to fix this color/tint/alpha problems :)

**Comment by ivanpopelyshev** [comment]
So the problem was in pixi.js. I have fixed it:

https://github.com/pixijs/pixi-spine/commit/f2d54bf4a0c8be08e1b0e1794615ab5fbf9698fb
https://github.com/pixijs/pixi.js/commit/ea658b0b34b2b5a8182005401c3b619080e12d7e

Wait for new pixi.js and pixi-spine builds
