### ISSUE TITLE
bower.json

### ISSUE THREAD

**Issue by funkypaul** [pixijs/pixi-spine#78]
Hey! 

Thanks for supporting spine!

Would it be possible to add bower.json file?

Cheers,
P.

**Comment by ivanpopelyshev** [comment]
I didnt work with bower. Do you want to create it for me?

**Comment by funkypaul** [comment]
Hey!

Thanks for answering.
I'm not good in taht stuff too, but adding file bower.json with content:

`{
	"name": "pixi-spine
	"version": "1.0.11",
	"main": "bin/pixi-spine.min.js",
	"dependencies": {
		"pixi.js": "*"
	},
	"ignore": [
		"gpupatch",
		"gulp",
		"src",
		"test",
		".editorconfig",
		".gitignore",
		".jshintrc",
		"docs.json",
		"gulpfile.js",
		"jsdoc_docs_conf.json",
		"package.json"
	]
}
`

(please check if dependencies are OK)

And then just register:
http://bower.io/docs/creating-packages/#register
