### ISSUE TITLE
The load function doesn't get called for spine json (exported from latest spine version)

### ISSUE THREAD

**Issue by faizanabidnaqvi** [pixijs/pixi-spine#79]
Hi there!
We have been trying to use pixi to create a web widget that runs Spine animations from our game. I am trying to load a spin json asset which has been exported from the latest version. When I add the json to the loader, it doesn't call the 'Asset Loaded' function. Here is my code:

`var renderer = PIXI.autoDetectRenderer(800, 600);
	document.body.appendChild(renderer.view);

	// create the root of the scene graph
	var stage = new PIXI.Container();

	// load spine data
	PIXI.loader
	    .add('boy', 'assets/cassie/cassei-cutscene-01.json')
	    .load(onAssetsLoaded);

	stage.interactive = true;

	function onAssetsLoaded(loader, res)
	{
	    // create a spine boy
	    var spineBoy = new PIXI.spine.Spine(res.boy.spineData);

	    // set the position
	    spineBoy.position.x = renderer.width / 2;
	    spineBoy.position.y = renderer.height;

	    spineBoy.scale.set(1.5);
	    stage.addChild(spineBoy);
		
	}

	requestAnimationFrame(animate);

	function animate()
	{
	    requestAnimationFrame(animate);
	    renderer.render(stage);
	}`

The onAssetLoaded function never gets called with my asset. There is no error thrown or anything. But if I use one of the example files, it works fine.

I tried this with the latest stable release as well as the 4.0.0 rc.

The exported files from spine are:
cassei-cutscene-01.atlas
cassei-cutscene-01.json
cassei-cutscene-01.png

I have attached the json and atlas files for reference.

[json-atlas-files.zip](https://github.com/pixijs/pixi-spine/files/207914/json-atlas-files.zip)

**Comment by ivanpopelyshev** [comment]
Hey! Ok, im going to test it. I didnt implement all features from spine v3, may be I'm missing sometehing. And all "throw new Error" that exist in libgdx runtime are absent here, so its not easy to determine whats wrong :)

**Comment by ivanpopelyshev** [comment]
It works for me.

Do you know that "complete" function will be called only once per loader? If you want to load multiple resources with multiple callbacks, you can either pass a callback to "add()" method, either use new loader each time.

Also, try latest pixi-spine.js from this repo, the one in npm cant work with spinev3 yet

**Comment by faizanabidnaqvi** [comment]
Hey! Thanks so much for your quick reply!

I know it's called once. But in my case, it's not called at all. I am using the latest pixi-spine.js for this repo.

When you say it works for you, do you mean it is able to load the json file? Did you modify the code in any way to make it work.

I am sorry for asking so many questions. I have just been stuck on this since yesterday.

**Comment by faizanabidnaqvi** [comment]
Hey man!

Just tried again with the latest version. I apologize. I may have been using an incorrect file. But it works now!

Thanks so much!!

**Comment by ivanpopelyshev** [comment]
Ok, I'm going to update it in npm then. I'm glad it works :)
