### ISSUE TITLE
Some parts of the Spine asset appear flipped

### ISSUE THREAD

**Issue by faizanabidnaqvi** [pixijs/pixi-spine#80]
Hi there!

I am using a Spine v3 asset on the stage. It appears that some parts of the assets are flipped vertically. It looks fine in Spine, though.

I also rechecked the exported data through Spine's 'Skeleton Viewer' and it works fine on that. I read around some places that it maybe because Pixi's Y axis is different from Spine's Y axis but I didn't find a solution for it. When I try to flip the Skelton through skeleton.flipY, it results in not showing the asset at all.

The attached files show the result from 'Skeleton viewer' as skeleton-viewer.jpg and from pixi-spine as pixi-spine.jpg. The eyes and the belt are flipped in pixi-spine.

**pixi-spine.jpg:**
![pixi-spine](https://cloud.githubusercontent.com/assets/5749036/14374247/4523177e-fd86-11e5-9b59-1497e6b546b3.png)

**skeleton-viewer.jpg:**
![skeleton-viewer](https://cloud.githubusercontent.com/assets/5749036/14374248/452b3990-fd86-11e5-82b3-1ec8dc31c87d.png)

I am using the latest pixi-spine.js from this repo.

**Comment by ivanpopelyshev** [comment]
That can also be rotation bug: eyes are rotated on 180 degrees.

**Comment by faizanabidnaqvi** [comment]
Hey! Thanks for your reply.
I just checked with my artist and we are not using IK. He is using FK.

is there any way I could sort of manually fix this?

**Comment by ivanpopelyshev** [comment]
I just found one of buys, I dont know if its yours, please test it again.

If its still wrong, please look at what did I do wrong:

https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-libgdx/spine-libgdx/src/com/esotericsoftware/spine/Bone.java

VS 

https://github.com/pixijs/pixi-spine/blob/master/src/SpineRuntime/Bone.js

my version stores matrices in form (a,c,b,d) and flipY is compared to spine.yBone.down, like in previous pixi-spine version.

**Comment by ivanpopelyshev** [comment]
Are you there?

**Comment by ivanpopelyshev** [comment]
Hey, try again please! I fixed it!

**Comment by faizanabidnaqvi** [comment]
Hey man!

I am so sorry. I was away on the weekend. Going to test out now. Thank you so much for your prompt response!

**Comment by faizanabidnaqvi** [comment]
It works man! Just tested it. 

I am going to working on more of it and let you know if I find anything else. I am sorry that I couldn't help you much with the source. I am just a beginner. But I can help you test as much as I can!

Thank you so much, again!
