### ISSUE TITLE
Shear timeline not supported for Spine 3.2

### ISSUE THREAD

**Issue by scottmcdonnell** [pixijs/pixi-spine#89]
as per title Shear is now available in Spine interface v3.2, is there any way to implement shear in Pixi?

**Comment by scottmcdonnell** [comment]
Until its supported maybe the throwing of the error could be removed so that all other timelines except shear are implemented.

```
    throw "Invalid timeline type for a bone: " + timelineName + " (" + boneName + ")";
```

**Comment by ivanpopelyshev** [comment]
Yeah, I didnt implement it yet. Nice catch, ill fix that!

**Comment by ivanpopelyshev** [comment]
Hey!

Look at my last commit https://github.com/pixijs/pixi-spine/commit/c1672fab4fb820acecc85f324fc7fb77193d1d10 . Built version is here: https://dl.dropboxusercontent.com/u/46636530/pixi-spine/pixi-spine.js

Unfortunately, I dont have animation with Shear or TransformConstraint. Can you create an example for me? Please export it in json and make small video so I'll have something to compare to.

**Comment by ivanpopelyshev** [comment]
ShearTimeline works. I dont know about TransformConstraint yet

**Comment by scottmcdonnell** [comment]
Great stuff, away from office for a few days but look forward to testing it. Thanks

**Comment by ivanpopelyshev** [comment]
UPD. TransformConstraint now works too, new version is 1.0.20

**Comment by ivanpopelyshev** [comment]
@scottmcdonnell TEST IT!!!

**Comment by scottmcdonnell** [comment]
ha! I have been busy with a beta delivery of  a game using a lot of spine, so I didn't get a chance! Just did a quick test and it all looks to be working great. 

I did a Dragon Shear here:
http://scottmcdonnell.github.io/pixi-examples/index.html?s=spine&f=dragon-shear.js&title=Dragon%20Shear&plugins=pixi-spine

**Comment by ivanpopelyshev** [comment]
@scottmcdonnell nice! Be sure to merge with latest examples, it has one more plugin and updated local pixi version.

**Comment by scottmcdonnell** [comment]
Yep, that is working with the latest examples. cheers.
