### ISSUE TITLE
Rotation on bones broken, when "Inherit rotation" turned off in Spine animation

### ISSUE THREAD

**Issue by rich-earth** [pixijs/pixi-spine#90]
Hello, 

FYI this problem has occured since updating to latest PIXI and pixi-spine, worked fine in 1.0.18  

Using latest version of PIXI v3 and pixi-spine.  If bones have Inherit rotation un-ticked in spine, the rotation of bones breaks when rendered in pixi.

See example, 2 skeletons which are the same but one has Inherit rotation de-selected on bones in Spine before exporting:
https://www.dropbox.com/s/5gibe5md0musf7x/bird%20test.zip?dl=0

**Comment by ivanpopelyshev** [comment]
Which version of spine are you using?

**Comment by ivanpopelyshev** [comment]
Yep, its really broken

**Comment by rich-earth** [comment]
3.0.11

**Comment by rich-earth** [comment]
Thanks yeah rotation just seems to be flipped, tested inherit Scale off and that works fine

**Comment by ivanpopelyshev** [comment]
Published 1.0.21.

**Comment by rich-earth** [comment]
Fixed! No thank YOU sir :)
