### ISSUE TITLE
Point to add new Sprite

### ISSUE THREAD

**Issue by gurmukhp** [pixijs/pixi-spine#91]
Hi

I've got an animation created in Spine, exported in JSON and integrated with Pixi, it looks awesome on the canvas.

What I'd like to do, is define a point on the character so I'm able to add an asset to it. For example, add a hat whilst the character runs.

If I define the point in Spine, am I able to access it in Pixi and therefore add a PIXI.Sprite to it and ensure it moves as the character animates?

Thanks

**Comment by ivanpopelyshev** [comment]
The easiest way is to add an attachment in Editor with a fake region and change it texture in PIXI. I'll make sure to add more ways of editing Spine model instance, but right now its either that, either adding a hat sprite as a child to one of existing sprites.

**Comment by ivanpopelyshev** [comment]
You can access position of a point relative to some bone, 

```js
var xy = [x1, y1];
spineModel.skeleton.bones[0].localToWorld(xy);
//xy[0], xy[1] is your new point, it is relative to spine object.
```

**Comment by gurmukhp** [comment]
That's really useful, thank you!

**Comment by ivanpopelyshev** [comment]
Btw, If you use second way, its better to update spine instances manually 

```js
spine.autoUpdate = false;
//or this
PIXI.spine.Spine.globalAutoUpdate = false;
//inside your RAF
dt = clamp((Date.now() - prev)*0.001, 0, 1);
spineObj1.update(dt);
spineObj2.update(dt);
```

**Comment by gurmukhp** [comment]
When you say create a fake region, do you mean to add an empty transparent png 1px x 1px?

**Comment by ivanpopelyshev** [comment]
yeah :)

**Comment by gurmukhp** [comment]
I've created a region called 'fake', could you help me find the region in the object and apply a texture to it?

```
var animation = new PIXI.spine.Spine(resources.alien.spineData);
```

animation.spineData doesn't have any region related stuff in it.

Some super high level example code would be really useful, thanks!

**Comment by ivanpopelyshev** [comment]
animation.slots[some_number].currentSprite is your sprite. Which number is it? depends on z-order you applied in spine. correct slot will have currentSpriteName='fake'

**Comment by gurmukhp** [comment]
animation.slots doesnt exist, but I've checked animation.skeleton.slots[16], unfortunately currentSprite isn't there but it is for other slots.

I think this is a problem on my end. Once I have a reference to the currentSprite (typeof Sprite), how can I change the texture on it?

Thanks

**Comment by ivanpopelyshev** [comment]
ok, not slots but animation.slotContainers or animation.children

**Comment by gurmukhp** [comment]
Only animation.skeleton.slots contains any reference to currentSprite, I think this might be the right one?

How do I change currentSprite to have the texture I want?

**Comment by gurmukhp** [comment]
I'm trying to manually update the sprites, so have tried your solution above but it doesn't seem to obey the timescale set, do you know what it should be? I've looked through the pixi-spine source to try and copy it from there, but I couldn't see anything similar:

```
var prev = Math.max(0, Math.min((Date.now()) * 0.001, 1));

function animate() {
  requestAnimationFrame(animate);
  renderer.render(stage);

  var dt = Math.max(0, Math.min((Date.now() - prev) * 1, 1));
  for (var sprite in allSprites) {
    allSprites[sprite].update(dt);
  }

  prev = dt;
}
```

**Comment by ivanpopelyshev** [comment]
prev = dt is wrong

```js
var curTime = Date.now();
var dt = ...
prev = curTime;
```

but its easier to use PIXI.ticker:

```js
PIXI.ticker.shared.add(funtion(deltaTime) {
  for (var sprite in allSprites) {
    allSprites[sprite].update(deltaTime); // may be divide y thousand here
  }
  renderer.render(stage);
});
```

if you want it start not right now but later:

```js
PIXI.ticker.shared.autoStart = false;
PIXI.ticker.shared.add(...);

function onAssetsLoad() {
   ...
   PIXI.ticker.shared.start();
}
```

If you want your own instance of ticker

```js
var ticker = new PIXI.ticker.Ticker();
ticker.autoStart = false;
ticker..add(...);

function onAssetsLoad() {
   ...
   ticker.start();
}
```
