### ISSUE TITLE
Load images separately

### ISSUE THREAD

**Issue by gurmukhp** [pixijs/pixi-spine#92]
Is it possible to load images separately like in this example?

https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-js/example/index.html

Ideally, I wouldn't want to have an Atlas file, instead I'd want the JSON file to be read and the images loaded from that. The reason I want this is because ultimately, I want to load in SVG files instead of PNG files as the rendering can be quite poor if the assets are exported at too large a size and then scaled down.

**Comment by ivanpopelyshev** [comment]
There's code in README.MD :

```js
var spine = PIXI.spine;
var loader = new PIXI.loaders.Loader();
loader.add('spritesheet', 'myspritesheet.json', function(res1) {
    var atlas = new spine.Atlas();
    atlas.addTextureHash(res1.textures, true);
    //second parameter is stripExtension=true because we dont need '.png' inside region names 

    //res1 is the same as loader.resources['spritesheet']
    loader.add('spineboy', 'spineboy.json', { metadata: { spineAtlas: atlas } }, 
        function(res2) {
            var mySpineBoy = new spine.Spine(res2.spineData);
            stage.addChild(mySpineBoy);
        });
})
```

addTextureHash accepts object with keys as texture names and values as PIXI.Texture.

**Comment by gurmukhp** [comment]
Awesome thanks, it wasn't clear that addTextureHash accepts an object, you're a star!!

**Comment by gurmukhp** [comment]
TexturePacker creates an Atlas file, do you know of any generator that can create the json file automatically?

**Comment by ivanpopelyshev** [comment]
TexturePacker creates json with hash. And ShoeBox too, but its free. There's nothing stopping you from creating your own loader or passing to addTextureHash collection of SVG generated textures.

**Comment by gurmukhp** [comment]
Awesome, I've got a working version, whoooo! The code was slightly different to what was in the readme, would you mind me doing a quick PR showing the right commands?

**Comment by ivanpopelyshev** [comment]
yes

**Comment by gurmukhp** [comment]
Done!

**Comment by meganvanwelie** [comment]
Hi @gurmukhp and @ivanpopelyshev,

I may be misunderstanding the original conversation, but I was wondering if there is a recommended way to extract the texture hash from the TexturePacker JSON file generated at export. According to the [examples doc](https://github.com/pixijs/pixi-spine/blob/master/examples/dynamic_texture_atlas.md), it looks like you need the attachment name and attachment path of all images you want to use included in a hash obj. The exported JSON file seems to include this data in the "skins" field, but is this directly readable by addTextureHash()?

Thanks for your help

**Comment by ivanpopelyshev** [comment]
`addTextureHash` and `hackTexture` were made for different case - use pixi textures and different atlas than one supplied with spine. 

If you want to use spine atlas you have to load it through spine atlas parser and then use combination of loaders. What's your case?

**Comment by meganvanwelie** [comment]
No, I don't want to use the spine atlas. I want to load individual PNG image files as textures, which are referenced in the Spine skeleton. I'm looking to avoid the long export time associated with generating the atlas PNG files.

**Comment by ivanpopelyshev** [comment]
Yes, that's valid case that people use.

https://github.com/pixijs/pixi-spine/blob/master/src/loaders.ts#L58

You can specify your own imageLoader

```js
 function myLoaderAdapter(loader, namePrefix, baseUrl, imageOptions) {
    return function(callback) {
         //somehow get the resource by namePrefix and return the baseTexture
     }
}

loader.load('spinename', 'spinepath.json', {
    metadata: {
        imageLoader: myLoaderAdapter
    }
}) ;

for example you can load synchronously:

```js
 function myLoaderAdapter(loader, namePrefix, baseUrl, imageOptions) {
    return PIXI.spine.syncImageLoaderAdapter(baseUrl);   
}

loader.load('spinename', 'spinepath.json', {
    metadata: {
        imageLoader: myLoaderAdapter
    }
}) ;
```

I wrote code from scratch so it might not work,. but something like that existed in past issues. Sorry for that chain of callbacks ;)

**Comment by ivanpopelyshev** [comment]
Oh , wait, sorry, its for the case if you need to load baseTexture..

Yeah, your best bet is hackTexture :) Or you can change the way you load the atlas somehow, dig into loader/spineAtlas sources. ..

**Comment by meganvanwelie** [comment]
Ok great, thanks for the advice! I'll look more closely and see what I can come up with :)
