### ISSUE TITLE
Skins with tints are not rendered.

### ISSUE THREAD

**Issue by gurmukhp** [pixijs/pixi-spine#94]
This plugin is really useful, it's great to be able to define sprites in Spine and have them rendered on the web!

I'm having an issue with tinting and was hoping you'd be able to help? 

Basically there is a sprite with a default skin. A new skin has been added by reusing the default skin images with a tint added. In Spine, the preview looks fine but when rendered in WebGL and CanvasRenderer, the default skin image is shown with no tints. If the skin has a different image then this works as expected.

```
    allSprites[sprite].skeleton.setSkinByName(skinName);
```

Any idea what could be wrong?

Thanks!

**Comment by ivanpopelyshev** [comment]
By the way, please look at new fork:

Example: https://gameofbombs.github.io/pixi-bin/index.html?s=flip&f=cards.js&title=Cards
Fork: https://github.com/gameofbombs/

**Comment by gurmukhp** [comment]
Attached are the files, I'll test the new fork now :)

[Archive.zip](https://github.com/pixijs/pixi-spine/files/293755/Archive.zip)

**Comment by ivanpopelyshev** [comment]
How exactly is it supposed to look?

**Comment by gurmukhp** [comment]
There is a dark and a light skin, when changing skins, the boys face, arms and legs should change colour.

**Comment by ivanpopelyshev** [comment]
Can you make a screen please?

**Comment by gurmukhp** [comment]
Sure thing, please see attached
<img width="303" alt="screen shot 2016-06-06 at 15 38 35" src="https://cloud.githubusercontent.com/assets/899769/15825725/cc3d2b10-2bfc-11e6-9687-296934fa7de2.png">
<img width="355" alt="screen shot 2016-06-06 at 15 38 30" src="https://cloud.githubusercontent.com/assets/899769/15825726/cc3f92f6-2bfc-11e6-8123-238e8b5cd9e4.png">

**Comment by ivanpopelyshev** [comment]
Please try this one : https://dl.dropboxusercontent.com/u/46636530/pixi-spine/pixi-spine.js

**Comment by ivanpopelyshev** [comment]
Never mind, i see the problem

**Comment by ivanpopelyshev** [comment]
try it now please

**Comment by ivanpopelyshev** [comment]
Ok, that's it, I need original spine file. I cant find any tint in json file at all

**Comment by gurmukhp** [comment]
It works! Setting the skin to 'darker' or 'lighter' makes the images get tinted.

That's excellent!

**Comment by ivanpopelyshev** [comment]
ok, im going to up the version and new build
