### ISSUE TITLE
Changing skins only works the first time

### ISSUE THREAD

**Issue by gurmukhp** [pixijs/pixi-spine#96]
Hey!

For some reason, when changing skins, it only seems to work if I set the skin to null first:

```
    allSprites[0].skeleton.skin = null;
    allSprites[0].skeleton.setSkinByName('darker');
```

If I don't then only the first skin change works, consequent skin changes result in no change. When viewing the sprite in Spine, everything looks ok.

Do you know why this might be? Could it be because the default skin is defined and always shows above other skins?

**Comment by ivanpopelyshev** [comment]
Can you please look up the code, may be you see it better than me? I'll try to fix that and tint today or tomorrow.

**Comment by gurmukhp** [comment]
Thank you, this makes sense!

**Comment by ivanpopelyshev** [comment]
So, basically setSkin(null) will help you.

Can you make a simple code and explanation to add it in README?

**Comment by ivanpopelyshev** [comment]
I want to invite you to our pixijs slack team. Whats your email?

**Comment by gurmukhp** [comment]
awesome!

gurmukhp@gmail.com

thx

**Comment by staff0rd** [comment]
I read the docs prior to them being updated with this, so was confused at first when it didn't work.  I wonder, would you accept a PR that adds something like `skin.resetSkinByName(skinName)` which would call `skin = null` prior to calling `setSkinByname`?  This would at least help to allow someone to determine the correct operation without relying on the README...

**Comment by djmisterjon** [comment]
work with `.skeleton.setSlotsToSetupPose();`

```javascript
            //this.avatar1.skeleton.skin = null; // not work, this keep hold skin slots
            this.avatar1.skeleton.setSkinByName("local_"+valueIn.localID);
            this.avatar1.state.setAnimation(1, 'idle_local_'+valueIn.localID, true);
            this.avatar1.skeleton.setSlotsToSetupPose(); // work
```

**Comment by gonnavis** [comment]
For convenient, add a link of the related official doc:
http://en.esotericsoftware.com/spine-runtime-skins
